### PR TITLE
Added Regex for different website's language versions

### PR DESCRIPTION
**Pull request by DarkVillager**
Added url Regex for different language versions.
image

### CODE REVIEW

**Review by Slowlife01 — CHANGES_REQUESTED** [review]
Bump version

**Comment by DarkVillager** [comment]
> Bump version

I did.

**Comment by Slowlife01** [comment]
No, you didn't your fork was outdated

**Comment by EncryptedDev** [comment]
Bump minor instead of patch

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
