### PR TITLE
added Codenames & Bug fixes for TikTok

### PR DESCRIPTION
**Pull request by Bas950**
image

@SlowLife1661

### CODE REVIEW

**Comment by ririxidev** [comment]
fix deepcode lol

**Comment by Bas950** [comment]
> fix deepcode lol

bruh this aint a sql, this is no error.

**Comment by Bas950** [comment]
image

**Review by Timeraa — APPROVED** [review]

**Comment by Timeraa** [comment]
DeepCode removed for now.

**Review by StrikerFRFX — APPROVED** [review]

**Review by StrikerFRFX — APPROVED** [review]

**Pull request merged**
