### PR TITLE
Update URLs for Sparked Host

### PR DESCRIPTION
**Pull request by hwalker928**
Sparked Host has changed some of their website URLs, thus I have updated the extension.

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
maybe just do regex instead of this massive url array ;-;

**Comment by hwalker928** [comment]
It's not regex, but it is better than the massive array.

**Comment by ririxidev** [comment]
I'm talking about metadata too

**Comment by hwalker928** [comment]
@ririxidev See above changes.

**Review by rxri — APPROVED** [review]

**Comment by ririxidev** [comment]
sorry for waiting

**Pull request merged**
