### PR TITLE
feat(Robloxforum): adds presence

### PR DESCRIPTION
**Pull request by liechtenberg**
## Description 
This adds robloxforum.com as a presence (unofficial Roblox forum website)

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
image
image
image
image
image

</details>

### CODE REVIEW

**Comment by sybetjeh** [comment]
image
Is this normal?

**Comment by ImRodry** [comment]
On Windows yes. You have CI checks on this PR that you should make sure they pass

**Comment by ImRodry** [comment]
Also delete all miscellaneous changes you made in this PR

**Comment by sybetjeh** [comment]
I'm sorry, but how do you delete miscellaneous changes? Do you mean the commits?

**Pull request closed without merging**
