### PR TITLE
Added and edited SoundCloud presence

### LINKED ISSUE #3986: [Presence | Feature Request] SoundCloud
**Is your feature request related to a problem? Please describe.**
It would be nice to add buttons to SoundCloud, as some already have them, including music related. Well, the request isn't even mine, I'm doing it at the suggestion of MeaN#4832 on Discord, but it would be very interesting for me too.

**Describe the solution you'd like**
Add buttons to presence, just like YouTube Music presence has, for example.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by itsmelouis**
Added button and edited some stuff

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
prettify with prettier and use array deconstructing in timestamps. and don't set startTimestamp

**Comment by Kozou4ever** [comment]
already used prettier but what do you mean by "array deconstructiing"?

**Comment by theusaf** [comment]
> already used prettier but what do you mean by "array deconstructiing"?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of it working

**Comment by Kozou4ever** [comment]
image

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
