### PR TITLE
Added 000webhost 

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #4856
Added Full Support for 000webhost.
Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_5
Screenshot_4

### CODE REVIEW

**Comment by Slowlife01** [comment]
Run `eslint . --fix` in your folder

**Comment by Slowlife01** [comment]
Install eslint package globally

**Comment by Slowlife01** [comment]
@DarkVillager also run it in the service folder not as whole

**Comment by EncryptedDev** [comment]
Resolve CodeFactor

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
