### PR TITLE
chore(Wikia.org): remove presence

### PR DESCRIPTION
**Pull request by Hans5958**
## Description

Wikia.org is now officially being merged to the Fandom domain (e.g. https://world-war-2.wikia.org to https://ww2-history.fandom.com), so this presence is now rendered useless.

I have no idea what message to use with this conventions, so here's my try. Tell me if I need to change it.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

### CODE REVIEW

**Comment by RisingSunLight42** [comment]
Since fix() is for bug fixes and feat() for additions, etc... refactor() seems ok for me for a presence deletion.
But wait for Encrypted or Bas950

**Comment by down-bad** [comment]
chore()

**Review by EncryptedDev — APPROVED** [review]

**Review by DarkVillager — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Comment by DarkVillager** [comment]
@Bas950 @EncryptedDev still getting errors from this with the checks.

**Comment by EncryptedDev** [comment]
> @Bas950 @EncryptedDev still getting errors from this with the checks as seen in #6562

Yes, it is because the files cannot be fetched to be validated as they were removed. Deploy passed so it is fine

**Pull request merged**
