### PR TITLE
Add juniper.bot to presences store

### PR DESCRIPTION
**Pull request by MrLivixx**
Adding the juniperbot site to the presences store, more in pl #1968

### CODE REVIEW

**Comment by MrLivixx** [comment]
> fix deepscan errors

@fr0r fixed

**Comment by Bas950** [comment]
Then just remove the || true for now :/

**Comment by doomlerd** [comment]
Closing in 4 days.

**Comment by MrLivixx** [comment]
> Closing in 4 days.

Fixed, and updated fork

**Review by doomlerd — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
