### PR TITLE
Jira Software - Website 

### PR DESCRIPTION
**Pull request by isladot**
# Hya. 
I made a Rich Presence for Jira Software, a website for planning and tracking the development process of a project.
I use it a lot at work, so I said to myself..why not build a PreMiD presence for it..and voilà.
It's made up of a lot of pages, subpages and sections, so the screenshots will be quite a lot. sry.

- Presence settings: https://i.imgur.com/uc7VADf.png
### "Your work" section
- Homepage: https://i.imgur.com/Nnc28hl.png

### "Project" section:
- Homepage:  https://i.imgur.com/n1ilke2.png
- "Roadmap" subsection: https://i.imgur.com/J3uVMsP.png
- "Backlog" subsection: https://i.imgur.com/dS6IvB1.png
- "Board" subsection: https://i.imgur.com/CiA42HL.png
- "Reports" subsection:
  - Homepage: https://i.imgur.com/IrhpQYj.png
  - "Burnup" subsection: https://i.imgur.com/FCE9xhN.png
  - "Burndown" subsection: https://i.imgur.com/bv78pcb.png
  - "Velocity" subsection: https://i.imgur.com/dvYHlOY.png
  - "Cumulative" subsection: https://i.imgur.com/uEOThcg.png
- "Issues" subsection:
  - No issue selected: https://i.imgur.com/NiHkfa9.png
  - Issue selected: https://i.imgur.com/NWAA67n.png
- "Code" subsection: https://i.imgur.com/vrDiCkf.png
- "Releases" subsection: https://i.imgur.com/B21Bz1m.png
- "Pages" subsection: https://i.imgur.com/Slj0S6n.png
- "Settings" subsection:
  - if "showSettingsSubsections" setting is false: https://i.imgur.com/F04YyuT.png
  - "Details" subsection: https://i.imgur.com/BpBd0ap.png
  - "Access" subsection: https://i.imgur.com/3bRaV9R.png
  - "Issue types" subsection: https://i.imgur.com/c4zEVDZ.png
  - "Notifications" subsection: https://i.imgur.com/AZgXkQZ.png
  - "Features" subsection: https://i.imgur.com/C4C1C9Z.png
  - "Apps" subsection: https://i.imgur.com/IuTjbH3.png & https://i.imgur.com/EGMOMhu.png

### "Filters" section:
- Homepage: https://i.imgur.com/RwsF9rO.png
- "Advanced Issue Tracking" subsection landing page: https://i.imgur.com/r0QRsba.png
- "Advanced Issue Tracking" subsection example: https://i.imgur.com/mhVW3IX.png 
_works also with other sections, ill not provide you screenshots cause i think Imgur is gona kill me._

### "Dashboards" section:
- Homepage: https://i.imgur.com/1VpJxrT.png
- Dashboard example page: https://i.imgur.com/1u7JqF5.png

### "Users & Teams" section:
- Homepage: https://i.imgur.com/bhSQzou.png
- User profile page: https://i.imgur.com/jEX8Ul3.png
- Team profile page: https://i.imgur.com/yx1GBrZ.png

### "Personal settings" section:
- Homepage: https://i.imgur.com/akZQw9C.png

there you go, aside the fact that I'll be killed by Imgur for this, i think i covered all the sections.

thanks in advice, isladot AKA Luca Biagetti.

### CODE REVIEW

**Review by ririxidev — CHANGES_REQUESTED** [review]
You should add to description warning that it only works on atlassian domains, since jira can be selfhosted too and on different domain than atlassian one.

**Comment by isladot** [comment]
> You should add to description warning that it only works on atlassian domains, since jira can be selfhosted too and on different domain than atlassian one.

of course! unfortunately I was not aware of it .. I'm sorry. 
If can i ask, would you have any suggestions to support self-hosted domains too?
I was thinking of removing the first RegExp that actually checks the hostname, but I'm afraid I'd break everything.

**Comment by ririxidev** [comment]
Someone already made suggestion about this, and we are thinking about making it in next release (v3) of PreMiD. So for now, there isn't any way to do this.

**Comment by Bas950** [comment]
You can check the whole url with regex, so maybe there is something that is ALWAYS in the url then you can use that.
See presences like emby or jellyfin.

**Comment by ririxidev** [comment]
Jira, doesn't have anything that is always in url so there's no way to this unfortunately

**Review by ririxidev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
