### PR TITLE
Basic Cleanup of the GBAtemp presence

### PR DESCRIPTION
**Pull request by NightYoshi370**
Needs testing, but it should be good to go. I'll look over it later to see if I could clean anything else up

### CODE REVIEW

**Comment by NightYoshi370** [comment]
image

**Comment by NightYoshi370** [comment]
To what? To the end user, this is exactly the same but the entire backend has been rewritten.

**Comment by Alanexei** [comment]
Change the version in the metadata. It's the way the server updates presences that requires the version to be changed.

**Comment by Alanexei** [comment]
Another thing, the only file changed was the typescript. Make sure you compile the typescript file and commit the changes.

**Comment by NightYoshi370** [comment]
I'm too busy unfortunately to do all this. I'll close the PR myself, and re open when I could do it again

**Pull request closed without merging**
