### PR TITLE
Add MemeFileServer to presence list

### PR DESCRIPTION
**Pull request by oxmc**
**Describe the changes in this pull request:**

Add memefileserver presence to premid.

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

18 01 22-k2cbp

</details>

### CODE REVIEW

**Comment by Slowlife01** [comment]
The Presence is too low quality. Thank you for your contribution.

**Comment by oxmc** [comment]
> The Presence is too low quality. Thank you for your contribution.

How can i make it higher quality?

**Comment by Slowlife01** [comment]
> > The Presence is too low quality. Thank you for your contribution.
> 
> How can i make it higher quality?

I just noticed that the site also uses a free domain, so this still won't be accepted even if you managed to make its quality better

**Comment by oxmc** [comment]
> 



> > > The Presence is too low quality. Thank you for your contribution.
> > 
> > 
> > How can i make it higher quality?
> 
> I just noticed that the site also uses a free domain, so this still won't be accepted even if you managed to make its quality better

oh, what's the issue with the free domain?

**Comment by oxmc** [comment]
oh, i see.

**Pull request closed without merging**
