### PR TITLE
Update Gamepedia presence (1.1.4)

### PR DESCRIPTION
**Pull request by Hans5958**
## Preword

Alright, here's an update as requested, along with minor updates that I done.

## Changelog

- Changed things for consistency
- Removed a unnecessary code function
- Changed default presence texts (request from staff members)

## Images

| Image                                                                                                                        | Link visited                                                         |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
|  | https://www.gamepedia.com/                                           |
|  | https://mysterydungeon.gamepedia.com/Rescue_Team/Pok%C3%A9mon_Square |

### CODE REVIEW

**Comment by Bas950** [comment]
> Update the version number.

lol I missed that 🤦

**Comment by Hans5958** [comment]
> 
> 
> Update the version number.

blame the daily qa

**Comment by Hans5958** [comment]
@doomlerd (ping because merged)

> 
> 
> Because you keep removing the empty line at the end of the file, I'll see if I can do anything about it.
> 
> EDIT: can't, make sure to read this : https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

it was not necessarily about the errors, it's about the daily qa  that makes me need to pull updates more often

**Comment by doomlerd** [comment]
> like, lax it off by just doing it in like wednesday or something

it doesn't even run anymore i guess

**Comment by Hans5958** [comment]
> 
> 
> > like, lax it off by just doing it in like wednesday or something
> 
> it doesn't even run anymore i guess

seeing that you responded three days later

**Pull request merged**
