### PR TITLE
refactor(Gmail): general recode and add localization support

### PR DESCRIPTION
**Pull request by EncryptedDev**
**Describe the changes in this pull request:**
Added localization support and recoded the presence as it was overdue a recode

PreMiD/Localization#7010

### CODE REVIEW

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Comment by Bas950** [comment]
@EncryptedDev conflicts

**Review by Syjalo — CHANGES_REQUESTED** [review]
``` ts
  const pages: Record<string, PresenceData> = {
    "#category/primary": {
      details: strings.categoryPrimary
    },
```
Add forgotten category (line 64)
_I can't add suggestion to approved pr_

**Comment by ImRodry** [comment]
Title does not follow commitlint

**Comment by Bas950** [comment]
When is this merge-ready?

**Pull request closed without merging**
