### PR TITLE
feat(Genius): add /new presence and polish description for presence

### PR DESCRIPTION
**Pull request by xKubsoneQ**
## Description 
Presence for /new path and polish description for presence.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

image

</details>

### CODE REVIEW

**Comment by xKubsoneQ** [comment]
why this old commits are visible here

AAAAAAAAA

**Comment by DarkVillager** [comment]
Split the pr into a pr for genius and one for trakt.

**Comment by xKubsoneQ** [comment]
> Split the pr into a pr for genius and one for trakt.

@DarkVillager trakt presence is already merged #6270

**Comment by DarkVillager** [comment]
> > Split the pr into a pr for genius and one for trakt.
> 
> @DarkVillager trakt presence is already merged #6270

Then make a new branche for these changes

**Comment by xKubsoneQ** [comment]
> > > Split the pr into a pr for genius and one for trakt.
> > 
> > 
> > @DarkVillager trakt presence is already merged #6270
> 
> Then make a new branche for these changes

but... this is a new branch

image

**Comment by DarkVillager** [comment]
Create a new branch and only change the genius description.

**Comment by Bas950** [comment]
Please make a PR for each presence

**Pull request closed without merging**
