### PR TITLE
Add Xbox presence

### PR DESCRIPTION
**Pull request by QkeleQ10**
Added a presence for Xbox.com with support for all the main pages on the site, including Xbox Cloud Gaming.

### CODE REVIEW

**Comment by ririxidev** [comment]
ban, errors & no screenshots 😠

**Comment by QkeleQ10** [comment]
These brace-style "issues" were intentional to improve legibility. Should I fix them?
To be completely honest I have no idea what is meant by prefer-destructuring and I would have no idea how to fix this. I Googled it but it doesn't really seem to apply to this scenario.
I'll fix the other two issues even though they exist in most other presences.

**Comment by ririxidev** [comment]
> Should I fix them?

yes

> To be completely honest I have no idea what is meant by prefer-destructuring and I would have no idea how to fix this. I Googled it but it doesn't really seem to apply to this scenario.

example:
```javascript
[endTimestamp, startTimestamp] = timestamps
```

**Comment by QkeleQ10** [comment]
> yes
Great, let me see how I can keep it legible :+1: :+1:
> example:
> [endTimestamp, startTimestamp] = timestamps
How is that supposed to work in this scenario (`String.split("|")[0]`) 😐 

Screenshots: 
image
image
image
image
image
image

**Comment by ririxidev** [comment]
> How is that supposed to work in this scenario (String.split("|")[0]) 😐
```javascript
[splittedString] = String.split("|");
```
:wink

**Comment by QkeleQ10** [comment]
You're telling me this
`presenceData.state = document.title.split("|")[0];`

becomes this?
`[splitString] = document.title.split("|");
presenceData.state = splitString;`

I really don't understand why your bot thing wants this - am I doing it right??

**Comment by ririxidev** [comment]
```javascript
const [splitString] = document.title.split("|");
presenceData.state = splitString;
```

**Review by Bas950 — DISMISSED** [review]

**Comment by ririxidev** [comment]
There are still issues.

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
