### PR TITLE
grailed presence fix

### PR DESCRIPTION
**Pull request by kznvii**
fixed glitching issue for presence

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Fix merge conflict (update fork)
Bump version

**Comment by kznvii** [comment]
idk what happened, but my visual studio code was being weird. hopefully no more issues

**Comment by kznvii** [comment]
also i think i updated it correctly. lmk if anything else needs to be fixed

**Comment by Bas950** [comment]
Looks like something went wrong, look at the files changed.

**Comment by kznvii** [comment]
uh, i just re did the cloning of the repository n now theres lots of files changed. not sure if that is how its supposed to be

**Comment by kznvii** [comment]
it says "This branch is 6 commits ahead of PreMiD:master.", so i think i successfully updated it

**Comment by kznvii** [comment]
i also fixed other bugs/spacing issues, so thats why a lot in my presence was changed

**Comment by Bas950** [comment]
I guess re-fork, since its still f*ed

**Pull request closed without merging**
