### PR TITLE
feat(Backpack.tf): add buttons, new images and links

### PR DESCRIPTION
**Pull request by Ali-Joon**
**Describe the changes in this pull request:**
Added Buttons, some new links and changed largeImageKeys
<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

backpack_tf2-1

backpack_tf2-2
</details>

### CODE REVIEW

**Comment by EncryptedDev** [comment]
resolve ts errors

**Comment by Ali-Joon** [comment]
> resolve ts errors

@EncryptedDev Right now, I don't see any errors after the latest commit...

**Comment by EncryptedDev** [comment]
> > resolve ts errors
> 
> @EncryptedDev Right now, I don't see any errors after the latest commit...

You clearly arent looking hard enough...
image

**Comment by Ali-Joon** [comment]
@EncryptedDev oh... I see...

**Review by Bas950 — APPROVED** [review]
https://discord.com/channels/493130730549805057/607524579874832446/928096461994987540

**Comment by Ali-Joon** [comment]
> [](https://discord.com/channels/493130730549805057/607524579874832446/928096461994987540)

Yeah the URLs are not more than 256 characters

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
