### PR TITLE
New translation tool

### PR DESCRIPTION
**Pull request by callumok2004**

### CODE REVIEW

**Review by StrikerFRFX — CHANGES_REQUESTED** [review]
Squash commits

**Comment by callumok2004** [comment]
no

**Review by StrikerFRFX — CHANGES_REQUESTED** [review]
Squash commit

**Review by Bas950 — CHANGES_REQUESTED** [review]
Squash commits, and undo the changes to the presences

**Review by Bas950 — APPROVED** [review]
LGTM

**Comment by ririxidev** [comment]
Closing for now. 
 - I bet no one wants to translate every presence description in order.
 - no skip option.
 - if there would be option to select what presences you would like to translate would be better. (i dont mean by category or whatever).

**Comment by ririxidev** [comment]
I said something - else it will be reverted.

**Comment by callumok2004** [comment]
I will take your message as a "requesting changes". the pull request can stay open and the changes will be pushed as requested.

**Comment by StrikerFRFX** [comment]
Nvm new PR will be made

**Comment by ririxidev** [comment]
> Nvm new PR will be made

Yeah literally, the best communication ever.

**Comment by callumok2004** [comment]
> > Nvm new PR will be made
> 
> Yeah literally, the best communication ever.

ikr, 10/10

**Pull request closed without merging**
