### PR TITLE
New presence for DramaCool

### PR DESCRIPTION
**Pull request by SlowLife1661**
image
image
image
image

### CODE REVIEW

**Comment by SlowLife1661** [comment]
The new scanner thingy checks other files xd

**Review by Bas950 — CHANGES_REQUESTED** [review]
Why you use that logo as largeimagekey? Use the same as logo in metadata
AND THANKS FOR MAKING THIS!

I do wish it had a special logo for RM but okay xD

**Comment by SlowLife1661** [comment]
The logo wasn't caching at that time lol

**Comment by ririxidev** [comment]
Site is not 2 months old 
image
Sorry 🤷

**Comment by SlowLife1661** [comment]
It was their new domain xd that's fine then

**Comment by ririxidev** [comment]
What can I say, new presence = you follow guidelines like new domain. If it would be update for old presence it would be fine.

**Pull request closed without merging**
