### PR TITLE
Update multiple presences (29/07/2022)

### PR DESCRIPTION
**Pull request by Hans5958**
Hello, everyone.

This PR is an accompaniment of the PR #6534 which updates these presences with the same codebase. For more information, please see #6534. Relevant changelogs will be listed here.

This PR includes updates for the following presences:

- Fandom 1.3.0
- Miraheze 1.1.0

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Changelog

- Update base script
  - Update metadata schema to 1.7
  - Change position to save `let`/`const` keyword (Bas950)
  - Adjust to support hiding certain presence data fields

- Adjust codebase from Wikimedia
- Fandom: Update store page logo and thumbnail
- Fandom: Deprecate Fandom/Gamepedia migration code to support all Fandom wikis
- Fandom: Add support for login pages on auth.fandom.com

### Side-by-side

This section only demonstrates Fandom, but it should work on all of the presences, because of the same codebase.

| Image | Link visited |
| ----- | ------------ |
|  | https://fridaynightfunking.fandom.com/wiki/Funkipedia_Mods_Wiki (with button and timestamp) |
|  | https://fridaynightfunking.fandom.com/wiki/Funkipedia_Mods_Wiki (with button only) |
|  | https://fridaynightfunking.fandom.com/wiki/Funkipedia_Mods_Wiki (with timestamps only) |
|  | https://fridaynightfunking.fandom.com/wiki/Funkipedia_Mods_Wiki (without button and timestamp) |

### Variations

| Image | Link visited |
| ----- | ------------ |
|  | https://fridaynightfunking.fandom.com/wiki/Funkipedia_Mods_Wiki |
|  | https://fridaynightfunking.fandom.com/wiki/Plants_vs._Rappers |
|  | https://www.fandom.com/ |
|  | https://terribletvshows.miraheze.org/wiki/Terrible_Shows_%26_Episodes_Wiki |
|  | https://terribletvshows.miraheze.org/wiki/Sonic_Underground |
|  | https://www.miraheze.org/ |

### CODE REVIEW

**Comment by EncryptedDev** [comment]
The title of this PR does not follow the repo's commit conventions

**Comment by Hans5958** [comment]
> The title of this PR does not follow the repo's commit conventions

Please see #6537, #6538, #6539, #6540, #6541, #6542, #6543, #6544, #6545, #6546, #6547, and #6548.

**Comment by RisingSunLight42** [comment]
@Hans5958 why did you closed this one since you just have to renam this PR according to the commit/PR convention for this PR to be ok...

**Comment by RisingSunLight42** [comment]
Plus, your other PR doesn't follow the required description

**Comment by Hans5958** [comment]
> why did you closed this one since you just have to rename this PR according to the commit/PR convention for this PR to be ok...

I wish to keep the messages in accordance to one presence, one scope convention. Having a scope that calls something that I only know is not good.

Also, a rebase is a better way to merge this, but I don't know why this can't be done.

> Plus, your other PR doesn't follow the required description

If they can't just click the link refer to this PR, then I don't know what to say.

**Pull request closed without merging**
