### PR TITLE
Adding Komikcast.com

### PR DESCRIPTION
**Pull request by fenismonjaa**
Komikcast is the largest manga reading platform in indonesia,  i made a presence for them. already tested.

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Please attach proof of working

**Comment by crazykarpenter** [comment]
prove 1
prove 2
prove 3
prove 4
prove 5
Prove 6
prove 7
prove 8

**Comment by crazykarpenter** [comment]
> Please attach proof of working

that is the prove, bro

**Comment by crazykarpenter** [comment]
im closing the pull request because want to edit the anotaion of folder name.

**Pull request closed without merging**
