### PR TITLE
:sparkles: Updates.

### PR DESCRIPTION
**Pull request by TheDropX**
image
image

image

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Fix codacy errors

**Review by Bas950 — APPROVED** [review]
LGTM

**Review by ririxidev — CHANGES_REQUESTED** [review]
Heya @TheDropX!
You should check out thing(s) that I requested to change in my review. Please look at them!

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Review by ririxidev — CHANGES_REQUESTED** [review]
Heya @TheDropX!
You should check out thing(s) that I requested to change in my review. Please look at them!
- Fix conflicts since there is 0 file changes.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Pull request merged**
