### PR TITLE
Migrate Presences

### PR DESCRIPTION
**Pull request by Alanexei**
Transferred DooM's presences to the bot account. He will be missed.

### CODE REVIEW

**Review by Bas950 — APPROVED** [review]

**Comment by fr0r** [comment]
Oy @ririxichan, i would appreciate merging this pr, though i'm kinda concerned about the ’’HBO Max’’ presence if you're going to actually maintain it.

**Comment by ririxichan** [comment]
about this idk tbh, someone else could maintain this.

**Comment by fr0r** [comment]
Then if you're not pretending to actively maintain the presence, I would recommend moving those presences to PreMiD or, at least, find someone to do that, so it doesn't be a pain in the ass to you.

**Comment by ririxichan** [comment]
@Alanexei change HBO Max author then to bot.

**Pull request merged**
