### PR TITLE
fix(presenceUpdater): correctly detect changed folders

### PR DESCRIPTION
**Pull request by theusaf**
## Description 

* Corrects the order of sources in getting diffs
  * Allows new presences to be detected and uploaded
  * Allows deleted presences to be detected and deleted
* Adds a check for changed presences before writing
  * Avoids preventing a presence from being deleted

## Acknowledgements
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Has this been tested/

**Comment by theusaf** [comment]
> Has this been tested?

I've tested the git commands and the `getDiff` method using the following steps:
1. On the `main` branch, compile tools and create a dummy presence, create a commit
2. Run `node tools/auto/compileChanged.js push`
3. Observe "No Presences changed, exiting..."
4. Switch to `fix-presence-updater` branch and create a dummy presence + commit
5. Run `node tools/auto/compileChanged.js push`
6. A new presence is detected and compiled

I can't test the presenceUpdater but it logically should work.

**Comment by Slowlife01** [comment]
I think the issue is with `--diff-filter` and not this.
I've tested this via GitHub Actions and new files still wouldn't work.

https://github.com/PreMiD/Presences/actions/runs/3428525954/jobs/5712922409
This failed because  `getDiff("removed")` returned the new files, and `getDiff()` returned nothing

**Comment by theusaf** [comment]
> I think the issue is with `--diff-filter` and not this. I've tested this via GitHub Actions and new files still wouldn't work.
> 
> https://github.com/PreMiD/Presences/actions/runs/3428525954/jobs/5712922409 This failed because `getDiff("removed")` returned the new files while `getDiff()` returned nothing

The reason `getDiff("removed")` returned the new files in that run is because when comparing `HEAD` to `HEAD^` with the `D` (deleted) filter applied, `HEAD^` does not contain the new files in `HEAD`, and is, therefore "deleted."
If swapping them, `getDiff("removed")` would return nothing.

**Comment by Slowlife01** [comment]
*Just tested again, and now it works* Had to edit my script

**Review by Timeraa — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
