### PR TITLE
Crowdin update: support for all websites, pages, buttons and bug fixes

### PR DESCRIPTION
**Pull request by ImRodry**
This PR completely overhauls the Crowdin presence, adding support for all Crowdin websites and pages, as well as buttons and a wider variety of small image keys. Below you can find a bunch of screenshots with the most relevant features but do keep in mind that this list is not extensive and there are other minor changes.

# Support
### API V2 dynamic section updates:
image
### Support articles:
image
### Searching: 
image

# App store
### Browsing apps:
image
### Specific app:
image
### Search:
image

# Status website
### Viewing status:
image
### Subscribing to status updates:
image

# Blog website:
### Main page:
image
### Specific blog post:
image
### Browsing a tag:
image
### Search:
image

# Main website
### View project buttons
image
### Translate project buttons
image
### Crowdin pages
image
### Release notes
image

### CODE REVIEW

**Comment by ImRodry** [comment]
there's another todo 🤔

**Comment by ImRodry** [comment]
I fixed all the codacy issues, the thing is just drunk and doesn't wanna update

**Comment by ririxidev** [comment]
image
did you?

**Comment by ImRodry** [comment]
These are the issues I get, but sure I'll fix those as well
image

**Comment by ririxidev** [comment]
bc you are in fixed issues tab lol

**Comment by ImRodry** [comment]
I was in the tab it sent me to :/

**Comment by ririxidev** [comment]
bc it's default tab

**Comment by ImRodry** [comment]
Hopefully that's all

**Review by rxri — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
