### PR TITLE
feat(aniwatch): add regex to support alternative domains

### PR DESCRIPTION
**Pull request by MohammedBakr44**
## Description 

Add regular expression matching to support alternative domains as the current presence only supports aniwatch.to which is blocked in some countries. The expression matches the string `aniwatch` followed by any prefix to support domains such as [aniwatchtv.to](https://aniwatchtv.to), it also matches any TLD as I personally use [aniwatch.nz](aniwatch.nz).

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

### Before regex update

image_2024-02-17_10-42-43

### After regex update

image_2024-02-17_10-49-12

image_2024-02-17_10-48-31

*tested on `aniwatch.nz` and `aniwatchtv.to`*
</details>

### CODE REVIEW

**Comment by MohammedBakr44** [comment]
updated version to `1.0.3`

**Comment by mallusrgreatv2** [comment]
image
I would personally go with a regex such as `aniwatch.*[.]...?`

**Comment by theusaf** [comment]
Any updates for this PR?

**Comment by MohammedBakr44** [comment]
Sorry about that. I noticed the issue with regex and decided to fix it later but got carried out in life.
Now I applied a fix and tested it(Thanks to @mallusrgreatv2).

**Comment by theusaf** [comment]
When your changes are ready, make sure to resolve merge conflicts and mark the PR as ready.

**Comment by theusaf** [comment]
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

**Pull request closed without merging**
