### PR TITLE
feat(OpenSea): add presence

### LINKED ISSUE #5235: OpenSea | opensea.io
### Discussed in https://github.com/PreMiD/Presences/discussions/5000

<div type='discussions-op-text'>

<sup>Originally posted by **elijaholmos** December  6, 2021</sup>
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's the name of the service?** 
OpenSea

**What should the Presence display?** 
Which page is being viewed, eg "Browsing Collection $COLL_NAME", "Looking at BillionaireZombiesClub #2558"

**If possible, please provide a logo for the service (512x512 minimum)** 
opensealogo
</div>

### PR DESCRIPTION
**Pull request by joerkig**
## Description 

Added a presence for OpenSea
resolves #5235

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Discord_r3A7IpQlgS
Discord_vXksx5Gkto
bPFpaIOsGH
Discord_Ac1JzTiQBk
Discord_BKnjGnvLNE
Discord_Luacqz3e7M
Discord_nSSkbUWC1p

</details>

### CODE REVIEW

**Review by RisingSunLight42 — COMMENTED** [review]
You could create a variable to store `pathname.split("/")` since you're using it multiple times

**Comment by joerkig** [comment]
> You could create a variable to store `pathname.split("/")` since you're using it multiple times

@RisingSunLight42 got any suggestions for naming such a variable cause my brain is blanking

**Comment by RisingSunLight42** [comment]
> > You could create a variable to store `pathname.split("/")` since you're using it multiple times
> 
> @RisingSunLight42 got any suggestions for naming such a variable cause my brain is blanking

I usually name it pathnameArray, because... It's an array obtained from the pathname xD

**Comment by EncryptedDev** [comment]
> > > You could create a variable to store `pathname.split("/")` since you're using it multiple times
> > 
> > 
> > @RisingSunLight42 got any suggestions for naming such a variable cause my brain is blanking
> 
> I usually name it pathnameArray, because... It's an array obtained from the pathname xD

Or `pathArr` for short

**Review by RisingSunLight42 — APPROVED** [review]

**Review by DarkVillager — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
