### PR TITLE
feat(Wordle): add domain

### PR DESCRIPTION
**Pull request by kyrie25**
**Describe the changes in this pull request:**
Change URL of the presence as it is moved to NY Times
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

image
image

</details>

### CODE REVIEW

**Comment by EncryptedDev** [comment]
I still use the powerlanguage website and a lot of other people do :/

**Comment by kyrie25** [comment]
> I still use the powerlanguage website and a lot of other people do :/

Wait that is still up? When I access the site it redirects me and all of my friends also to the `nytimes` site
msedge_wWfSxTJ1I4

**Comment by kyrie25** [comment]
> I still use the powerlanguage website and a lot of other people do :/

Added the old URL back, not sure how long it will stay up tho but yeah

**Comment by fr0r** [comment]
The powerlanguage version is also redirecting me to the nytimes.com one.

**Review by Bas950 — APPROVED** [review]

**Comment by elijaholmos** [comment]
I'm getting redirected to NYtimes as well and this is causing the presence to not function

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
