### PR TITLE
feat(Tune-In): artwork and fixes

### PR DESCRIPTION
**Pull request by DarkVillager**
**Describe the changes in this pull request:**
Long Time fix for tune-in. And added Artwork.
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

tunein-4
tunein-1
tunein-2
tunein-3

</details>

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Resolve SV, lint and use tabs

**Comment by ImRodry** [comment]
to answer your commit question, no you didn't fix it

**Comment by DarkVillager** [comment]
> to answer your commit question, no you didn't fix it

Then what should I change?

**Comment by ImRodry** [comment]
A quick glance at the diff should tell you what’s wrong

**Comment by DarkVillager** [comment]
> A quick glance at the diff should tell you what’s wrong

Okay?

**Comment by DarkVillager** [comment]
> A quick glance at the diff should tell you what’s wrong

https://streamable.com/l8homa

**Comment by ImRodry** [comment]
Also title of the PR does not follow commit lint

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
