### PR TITLE
feat(presense): add updated 9anime presence

### PR DESCRIPTION
**Pull request by julianxchang**
## Description 
Replaced if/else branch with switch statement
Multi-word search results aren’t concatenated with ‘+’
Presence now supports all paths

## Acknowledgements
- [ Yes ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ Yes ] I linted the code by running `yarn format`
- [ Yes ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

home
result
watching

</details>

### CODE REVIEW

**Comment by DarkVillager** [comment]
feat(9anime): add presence

**Review by DarkVillager — APPROVED** [review]
LGTM

**Review by Bas950 — CHANGES_REQUESTED** [review]
9anime already exists, please rebase your fork.

**Comment by julianxchang** [comment]
Sorry but what do you mean by that? Should I resolve the merging conflicts?

**Comment by DarkVillager** [comment]
> Sorry but what do you mean by that? Should I resolve the merging conflicts?

yes

**Comment by julianxchang** [comment]
ok I resolved the merging conflicts

**Review by Bas950 — APPROVED** [review]

**Review by DarkVillager — APPROVED** [review]
<LGTM>

**Review by theusaf — APPROVED** [review]

**Pull request merged**
