### PR TITLE
Added https://discordmerch.com/

### PR DESCRIPTION
**Pull request by ScypterDev**
image

Added from #2669

### CODE REVIEW

**Comment by Bas950** [comment]
Just add it to the Discord presence

**Comment by ScypterDev** [comment]
> Just add it to the Discord presence

What do you mean?

**Comment by ScypterDev** [comment]
> Just add it to the Discord presence

It is a different domain is that possible?

**Comment by Bas950** [comment]
> > Just add it to the Discord presence
> 
> It is a different domain is that possible?

Array of URL, or use regex.

**Pull request closed without merging**
