### PR TITLE
Bump Jstris Ver to 1.1.2 - Emergency Hotfix to Fix Presence for Non-Signed in Users.

### PR DESCRIPTION
**Pull request by jy1263**
With signed in:
image

Without signed in:
image

Buttons with Sign In:
image

Buttons without Sign In:
image

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Review by StrikerFRFX — CHANGES_REQUESTED** [review]
Show proof of presence still working for a non signed in user as well as a signed in user

**Comment by jy1263** [comment]
oki

**Review by StrikerFRFX — APPROVED** [review]
As long as that last button on your 3rd screenshot is removed when they're not signed in, all good (if they can access that page or whatever when not signed in)

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
