### PR TITLE
Added DC Cache to .gitignore

### PR DESCRIPTION
**Pull request by N0chteil**
Added **.dccache** to _gitignore_

### CODE REVIEW

**Review by callumok2004 — CHANGES_REQUESTED** [review]
ye no, this one made me and a couple others laugh. but srsly, no

**Comment by EncryptedDev** [comment]
As Callum said, there's no point

**Review by StrikerFRFX — CHANGES_REQUESTED** [review]
If there was a need for this I would say yes, but we have never had any issues (afaik) with deepcode cache. If you need to use a gitignore, make one in any working directories in the future.

**Comment by StrikerFRFX** [comment]
And if this is needed, myself or someone else can add it manually to the .gitignore ourselves

**Comment by ririxidev** [comment]
Lol

**Pull request closed without merging**
