### PR TITLE
Add Contributor to SimulatorHits

### PR DESCRIPTION
**Pull request by HuckinB**
Please see Ticket [#05312](https://discord.com/channels/493130730549805057/775471751291338762)
GitHub of Contributor: @KylePython

### CODE REVIEW

**Comment by HuckinB** [comment]
Note I understand I have my presence ban so I have removed YSR and added Kyle as a contributor to continue the uphold of the presence

**Comment by ririxichan** [comment]
Okay like, as far I know from this ticket owner and presence id had to be transferred to owner. Contributor is only when they add do something in code (e.g. rewrite etc.)

**Comment by HuckinB** [comment]
Yes I understand he wasn't sure what to write in the ticket. He just needs access to continue working on the presence.

**Comment by HuckinB** [comment]
Feel free to ask this in the ticket.

**Comment by ririxichan** [comment]
Like, everyone can edit presence when they want to fix or whatever, you can't add him to contributors since he didn't do anything to this presence. You can only change author if you want, or he doesn't need to be in metadata to update presence etc :)

**Comment by HuckinB** [comment]
He did do some parts with me. But in terms of continuation, he can just make comits and pea even with my ban?

**Comment by ririxichan** [comment]
Actually resolved in discord ticket.

**Pull request closed without merging**
