### PR TITLE
Rythm: Translation strings and a more future-proof bot detection

### PR DESCRIPTION
**Pull request by ACertainCoder**
**Name:**
Rythm

**Changes:**
- Translation links (see https://github.com/PreMiD/Localization/pull/6608)
- A more future-proof bot detection (the presence can now detect new Rythm bots that match the normal naming schema)

**Screenshots:**
No screenshots provided because the main functionality of the presence didn't change and the strings are currently missing.

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
Upload screenshots since pr on Localization repo has been merged.

**Comment by ACertainCoder** [comment]
It seems like the api doesn't return the strings yet.
grafik
grafik

**Comment by ririxidev** [comment]
Try now because like always they broke API and had to restart it to get strings in it.

**Comment by ACertainCoder** [comment]
👍 Now it works. Here you go:
grafik
grafik

**Review by rxri — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
