### PR TITLE
Update for the Rythm presence

### PR DESCRIPTION
**Pull request by ACertainCoder**
**Name:**
Rythm

**Changes:**
- New website url
- Support for the dashboard
- Cleanup of the existing code

**Screenshots:**

### CODE REVIEW

**Review by Bas950 — APPROVED** [review]

**Comment by Bas950** [comment]
Really good job

**Review by StrikerFRFX — COMMENTED** [review]
I'm impressed, a lot. Good job, I see nothing wrong on glance and I trust myself at 2am but I'll take a second look when I wake up.

**Review by StrikerFRFX — APPROVED** [review]

**Comment by ririxidev** [comment]
Hi @ACertainCoder,

I'm writing here because literally I don't know where I can contact you. I'm writing to you because of getPegeletiable function that you made that you can access custom JS code. For me, this function shouldn't be even possible. Presence shouldn't be allowed to run custom JS code in anyway. If you really need more information from me please contact me on discord ririri#2721, but for now, please change your code and remove this custom function.

Thanks,
ririxi (Contact: mail@ririxi.dev, ririxi#2721)

**Comment by ACertainCoder** [comment]
@ririxidev excuse me but this pull request already got accepted? You could/should have told me that earlier.
Anyway, PreMiD's built-in getPegeletiable function freezes the browser entirely to the point where you have to kill the process via task manager. It's not possible to access the data via the document variable by any meaningful way and as you can see in my code, it's not executing anything harmful - it just accesses two variables.

I'm on the PreMiD Discord server if you want to message me via Discord (ACertainCoder#9011).

**Comment by ririxidev** [comment]
Heya @ACertainCoder again,
I sent you friend request so we can talk at DMs about it.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Pull request merged**
