### PR TITLE
feat(PayPal): add presence

### PR DESCRIPTION
**Pull request by CrypticXT**
**Describe the changes in this pull request:**
Added PayPal Presence

Images:
 Discord_DzDrD6pO3t
Discord_PeNt9spzcx
Discord_yBlcEIJ2fx

### CODE REVIEW

**Comment by ImRodry** [comment]
Protip: don't commit the yarn.lock file

**Comment by CrypticXT** [comment]
> Protip: don't commit the yarn.lock file

Sorry wasn't intended.

**Comment by EncryptedDev** [comment]
> > Protip: don't commit the yarn.lock file
> 
> Sorry wasn't intended.

Remove it then

**Comment by CrypticXT** [comment]
Sorry for the mess creating a new PR

**Pull request closed without merging**
