### PR TITLE
Update metadata.json

### PR DESCRIPTION
**Pull request by Gabriel4927**
Update site url to "www.superanimes.com"

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Upload proof showing it is working 😄

**Comment by Gabriel4927** [comment]
> Upload proof showing it is working

Has it been updated yet?

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of it working

**Comment by Gabriel4927** [comment]
It is not working at the moment
https://imgur.com/5UYdiXw

**Comment by ririxidev** [comment]
🤦 Compile presence with edited metadata and load it as DEV presence and show screenshots.

**Comment by Gabriel4927** [comment]
>  Compile presence with edited metadata and load it as DEV presence and show screenshots.
I don't know much about programming, can I report it as a bug?

**Comment by ririxidev** [comment]
Yes.

**Pull request closed without merging**
