### PR TITLE
Updated ShiftDelete.Net!

### PR DESCRIPTION
**Pull request by eggsywashere**
So now it detects when you're creating a new post! Amazing right? Look at this beautiful view! OMG!

WOOWowoOWOo-DUUD

### CODE REVIEW

**Comment by eggsywashere** [comment]
> Privacy gone

whay, you won't start a discussion about por~~n~~ on a technology forum. _do you :Timeraa:_

**Comment by Bas950** [comment]
> > Privacy gone
> 
> whay, you won't start a discussion about por~n~ on a technology forum. _do you :Timeraa:_

you dont care about privacy at all when you add an NSFW presemce

**Comment by eggsywashere** [comment]
> > > Privacy gone
> > 
> > 
> > whay, you won't start a discussion about por~n~ on a technology forum. _do you :Timeraa:_
> 
> you dont care about privacy at all when you add an NSFW presemce

should I add one then? :^)

**Comment by Kritosna** [comment]
I like your work. :)

Sites like Donanımhaber, Watchill, Ekşi Sözlük can also be added.

**Comment by eggsywashere** [comment]
@Kritosna I already made ekşi sözlük (https://premid.app/store/presences/ekşi%20sözlük) and you can use DiziBOX, yabancıdizi or dizilab for now. I can't promise about doing those 2.

**Comment by Kritosna** [comment]
> @Kritosna I already made ekşi sözlük ([https://premid.app/store/presences/ekşi%20sözlük](https://premid.app/store/presences/ek%C5%9Fi%20s%C3%B6zl%C3%BCk)) and you can use DiziBOX, yabancıdizi or dizilab for now. I can't promise about doing those 2.

It's beautiful.
I suggest you check Watchill. Certainly more advanced than others. Most people don't use the others while Watchill is there.

**Comment by eggsywashere** [comment]
> It's beautiful.
> I suggest you check Watchill. Certainly more advanced than others. Most people don't use the others while Watchill is there.

Well it doesn't show up on the search results of "yabancı dizi izle", you know what that means anyways. And it's the first time I'm hearing that was existed to be honest. Never heard of it before. I can do it for sure but you have to create an issue [here](https://github.com/PreMiD/Presences/issues/new?template=service_request.md).

**Comment by Kritosna** [comment]
I suggest you check these words. 

"friends izle" and "random series name izle"

I discovered while watching friends.

I follow your projects. achievements. :)

**Comment by eggsywashere** [comment]
@Kritosna open an issue, I already started making it.

**Pull request merged**
