### PR TITLE
Dutch translations and logo updates

### PR DESCRIPTION
**Pull request by QkeleQ10**
I translated some of the most popular presences' descriptions to Dutch. I also updated the icons for Facebook and Roblox to accommodate their new logos.

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
update version

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump versions

**Comment by QkeleQ10** [comment]
@Bas950 yes hi I DMed you, which versions? All of them, or only the ones I changed the icon of?

**Comment by StrikerFRFX** [comment]
> @Bas950 yes hi I DMed you, which versions? All of them, or only the ones I changed the icon of?

@QkeleQ10 update them all to an appropriate version (since minor changes, go 1 up on the last number e.g 1.0.0 -> 1.0.1)

**Review by Bas950 — DISMISSED** [review]

**Comment by StrikerFRFX** [comment]
Can you remove Skribbl? I can add this string manually myself on this actual Repo but until #3171 is merged, can't and won't work since there would be conflicting files unless you remove and I add the NL description X)

**Comment by QkeleQ10** [comment]
@StrikerFRFX Reverted.

**Comment by QkeleQ10** [comment]
f*nk it wiped bas' review lol

**Comment by StrikerFRFX** [comment]
> f*nk it wiped bas' review lol

das is fine, double check everything is as it should be before merge and make any edits now?

**Comment by QkeleQ10** [comment]
Should all be fine except Skribbl, but you said you'd take care of that

**Review by StrikerFRFX — APPROVED** [review]

**Pull request merged**
