### PR TITLE
Fixes the extension to show all the features

### PR DESCRIPTION
**Pull request by carterdacat**
Hey all! I was using the GH extension, but it didnt work for most things, like the all repo features, or other ones that needed to get data from the site its self, not just the URL. Cheers

### CODE REVIEW

**Comment by carterdacat** [comment]
PR 2020, oh lord help me

**Review by Cairo2k18 — CHANGES_REQUESTED** [review]
Please show proof of the presence actually working (screenshots of the presence on your profile)

**Comment by carterdacat** [comment]
Screen Shot 2020-08-25 at 4 23 43 AM
Screen Shot 2020-08-25 at 4 23 19 AM

**Comment by carterdacat** [comment]
Screen Shot 2020-08-25 at 4 26 09 AM
Screen Shot 2020-08-25 at 4 26 17 AM
This is before

**Review by Cairo2k18 — CHANGES_REQUESTED** [review]
You need to fix the code quality issues DeepScan found: [https://deepscan.io/dashboard/#view=project&tid=6792&pid=8925&bid=113944&subview=pull-request&prid=456201](https://deepscan.io/dashboard/#view=project&tid=6792&pid=8925&bid=113944&subview=pull-request&prid=456201)

**Comment by carterdacat** [comment]
@Cairo2k18 fixed

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
