### PR TITLE
Update to Version 2.0.0

### PR DESCRIPTION
**Pull request by HuckinB**
• Added Support for Staff Panel
• Added More Pages

### CODE REVIEW

**Comment by HuckinB** [comment]
Proof of Page Update


Proof for Staff Panel

**Comment by doomlerd** [comment]
Resolve the branch conflicts.

**Comment by HuckinB** [comment]
The conflict is the URL being converted from a String to an Array. There is no way to fix it. I have also seen the same layout on other projects.

**Comment by frozaum** [comment]
uhhh...
image

**Comment by Alanexei** [comment]
Make sure your fork is up to date.

**Comment by HuckinB** [comment]
> uhhh...
> image

Strange I forked it right before I done it... Ill redo it

**Comment by HuckinB** [comment]
• Closing to re-fork

**Pull request closed without merging**
