### PR TITLE
New: Presence Pylon

### PR DESCRIPTION
**Pull request by cembkoztekin**
Discord_ds9TxWJGX8
Discord_k5K6i7nYhG
Discord_Plr7tH5tpQ
Discord_qh68Vqiaj9
Discord_RmxiWtHMHO
Discord_UOKsAVip0V

----

GIF:
MDxreRFdHQ

### CODE REVIEW

**Comment by Roi3575** [comment]
very nice boomer

**Comment by cembkoztekin** [comment]
> very nice boomer

thanks

**Comment by ba-e** [comment]
DAMN AWESOME... we need the this

**Comment by cembkoztekin** [comment]
> Fix deepscan errors and version should be 1.0.0

Done

**Pull request closed without merging**
