### PR TITLE
IBL Extension

### PR DESCRIPTION
**Pull request by MaximKing1**
This is for the bot list InfinityBotList - https://infinitybots.xyz/

### CODE REVIEW

**Comment by ririxidev** [comment]
Heya @MaximKing1 ! We have some news for you that you should take look at:
We are so sorry but we need to deny your pull request regarding this presence due of:
 - We are not accepting anymore discord bots list that no one heard of.
 - Codacy errors.
 
Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by Connor200024** [comment]
Hi,

I understand that you are not accepting this... But there has to be a better reason behind this?

"We are not accepting anymore discord bots list that no one heard of." <-- I don't think that's true on that.. Because the amount of bot lists you have listed, at all no announcements or any sort of social media posts was made about this?

We have a new management now, due to the old Owner selling the list...

If you wish to speak to me via discord dm's then please let me know.

Thanks,

Have a good day! 😊

**Comment by ririxidev** [comment]
Hey @Connor200024,
We are so sorry, but you literally confirmed that this site has been sold to you and yeah. We already have a lot of discord bot lists presences and we don't need more and more reasons that we don't want to speak.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by Connor200024** [comment]
Hey @ririxidev,

Thanks for getting back to me quick.

No worries, I fully understand..

Thanks,

Connor200024

**Pull request closed without merging**
