### PR TITLE
Update Meta Change

### PR DESCRIPTION
**Pull request by ItsHarryGB**
Updated Main and New Editor for PreMid!

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
If you change the author, you need to own the assets of the rich presence too

**Review by ItsHarryGB — COMMENTED** [review]
Hey, our assets come from our website so I hold them too.

**Comment by ItsHarryGB** [comment]
Hey there,

Client ID Has now been changed. :)

**Review by ItsHarryGB — COMMENTED** [review]
Updated Client ID and more on presence.ts

**Review by EncryptedDev — DISMISSED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — DISMISSED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
