### PR TITLE
Add NetEase Cloud Music Presence

### LINKED ISSUE #1155: 网易云音乐 (NetEase Cloud Music) | music.163.com
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
_fastcall#1337

**What's the name of the service?** 
网易云音乐 ( NetEase Cloud Music ) | https://music.163.com

**What should the Presence display?** 
Music currently playing, like YoutubeMusic and soundcloud.

**If possible, please provide a logo for the service (512x512 minimum)** 

**Other**
Wikipedia page:https://en.wikipedia.org/wiki/NetEase_Music

### PR DESCRIPTION
**Pull request by SnoweyFoxx**
Resolves #1155

### CODE REVIEW

**Comment by SnoweyFoxx** [comment]
image

**Comment by doomlerd** [comment]
What about www.163.com ?

**Comment by Bas950** [comment]
On Hold - We are changing some rules regarding presence creation, we will update you soon.

**Comment by Bas950** [comment]
Please code your presence in TypeScript (TS).
For more info see:
https://discordapp.com/channels/493130730549805057/607524579874832446/704792826025869393

**Pull request closed without merging**
