### PR TITLE
Update multiple presences (FandomDesktop skin)

### LINKED ISSUE #3883: [Presence | Feature Request] Fandom
**Is your feature request related to a problem? Please describe.**
Fandom has updated, and received a new interface (FandomDesktop), and since it is a new interface, presence is no longer working on this particular one.

**Describe the solution you'd like**
Add support for the new theme.

**Describe alternatives you've considered**
None.

**Additional context**
I just didn't put it as a bug because presence is still supporting the old theme (Oasis):
image

### PR DESCRIPTION
**Pull request by Hans5958**
## Description

Here's a PR that tackles a quite simple problem IMO. Somehow it took a while due to complications on my workspace, but it's all okay. This PR adds support of FandomMobile and future FandomDesktop skin, along with tackling some issues.

This PR resolves #3883 and is related to Hans5958/PreMiD-Presences-Personal#6

This PR includes updates to the following presences:

- Fandom (1.2.6)
- Gamepedia (1.2.6)

## Changelog

- Support FandomMobile and future FandomDesktop skin (Fandom, Gamepedia)
- Simplify Fandom/Gamepedia detection (Fandom, Gamepedia)
- Remove support for Community Central-specific namespaces (Fandom)
- Add support for more namespaces (Fandom, Gamepedia)
- Sync code for search page from Gamepedia
- Fix ESLint warnings and errors

## Images

All variations will give the same presence data, so to prove there are no smoke and mirrors, all screenshots are full-screen.

| Image | Link visited |
| ----- | ------------ |
|  | https://sonic.fandom.com/wiki/Miles_%22Tails%22_Prower |
|  | https://sonic.fandom.com/wiki/Miles_%22Tails%22_Prower?useskin=fandomdesktop |
|  | https://sonic.fandom.com/wiki/Miles_%22Tails%22_Prower?useskin=fandommobile |
|  | https://minecraft.fandom.com/wiki/Java_Edition_1.16.5 |
|  | https://minecraft.fandom.com/wiki/Java_Edition_1.16.5?useskin=fandomdesktop |
|  | https://minecraft.fandom.com/wiki/Java_Edition_1.16.5?useskin=fandommobile |

### CODE REVIEW

**Comment by Hans5958** [comment]
Wow, even after force-pusing the branch the leaky DeepScan errors (errors and warnings from other files) is still there. There should be a compesation for this.

**Comment by ririxidev** [comment]
Just ignore DeepScan then

**Review by rxri — APPROVED** [review]
ok to me 👍

**Review by Slowlife01 — APPROVED** [review]

**Comment by ririxidev** [comment]
good pr 👌

**Pull request merged**
