### PR TITLE
Added AniTube Presence

### PR DESCRIPTION
**Pull request by JetPlet**
image
image

### CODE REVIEW

**Comment by Bas950** [comment]
> image
> 

No details?

**Comment by JetPlet** [comment]
image
I forgot to put the other print

**Review by Bas950 — CHANGES_REQUESTED** [review]
Fix codacy issues

**Comment by JetPlet** [comment]
> Fix codacy issues

But where are the problems?

**Comment by ririxidev** [comment]
https://github.com/PreMiD/Presences/pull/2838/checks?check_run_id=1729676257 ...

**Comment by Bas950** [comment]
> > Fix codacy issues
> 
> But where are the problems?

image

**Comment by ririxidev** [comment]
one pr or nothing. decide

**Pull request closed without merging**
