### PR TITLE
fix(Netflix): presence not showing

### LINKED ISSUE #5495: Netflix not displaying on status
### Description

Everything other than netflix comes up on status but not not netflix

### Steps to Reproduce

image

image

### Screenshots

_No response_

### Expected Behavior

to show netflix on status

### Actual Behavior

nothing is being display when netflix is being used

### Page URL

no where

### Operating System (OS)

Windows 11

### Browser

Firefox

### Browser Version

95.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by 7loud**
**Describe the changes in this pull request:**

image
For some people `netflix.appContext.state.playerApp.getState().videoPlayer.videoMetadata` returns:
image

<details>
<summary> Proof to proving the creation/modification working </summary>
<br>

</details>

### CODE REVIEW

**Comment by N0chteil** [comment]
image

How can I fix this?

**Comment by Slowlife01** [comment]
> image
> 
> How can I fix this?

Does `this` work as you expected in that context tho

**Comment by N0chteil** [comment]
> > image
> > How can I fix this?
> 
> Does `this` work as you expected in that context tho

yeah

**Comment by Slowlife01** [comment]
> > > image
> > > How can I fix this?
> > 
> > Does `this` work as you expected in that context tho
> 
> yeah

I highly doubt that lol. Just make it a variable?

**Comment by EncryptedDev** [comment]
This isn’t the only issue for Netflix, sometimes largeImageKey links are larger than 256 characters which Discord doesn’t accept. Please look into this and incorporate this into your pull request (:

**Comment by EncryptedDev** [comment]
Resolves #5495

**Comment by Timeraa** [comment]
> This isn’t the only issue for Netflix, sometimes largeImageKey links are larger than 256 characters which Discord doesn’t accept. Please look into this and incorporate this into your pull request (:

Use the new function Bas and I made in #presence-dev

@PreMiD/presence-verifiers You still on track with this?

**Comment by N0chteil** [comment]
> > This isn’t the only issue for Netflix, sometimes largeImageKey links are larger than 256 characters which Discord doesn’t accept. Please look into this and incorporate this into your pull request (:
> 
> 
> 
> Use the new function Bas and I made in #presence-dev
> 
> 
> 
> @PreMiD/presence-verifiers You still on track with this?

https://github.com/PreMiD/Presences/commit/5765c24a8da9c3167c6d6882cfc7a230b3fef974

**Comment by ImRodry** [comment]
Title does not follow commitlint

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
