### PR TITLE
Minehut presence

### PR DESCRIPTION
**Pull request by Setloth**
Presence for https://minehut.com & https://shop.minehut.com
-> Minehut is a free minecraft server hosting service

### CODE REVIEW

**Comment by Echological** [comment]
I'm going to head to bed, guess I will continue this later

**Comment by Echological** [comment]
Where's the template, for things like concatenation, what should it look like besides from what I currently have?

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — COMMENTED** [review]
Run prettier please (`yarn pretty`)

**Comment by Echological** [comment]
also, when i ran yarn pretty, i think more than just my file got edited.

**Comment by Echological** [comment]
ok now im getting errors not even related to my thing. should i just make a new pr?

**Comment by Echological** [comment]
I am going to rebuild my project, and recommit.

**Review by Slowlife01 — COMMENTED** [review]
And I assume you have a reason why you have to fetch the url?

**Comment by Slowlife01** [comment]
And just use prettier extension installed

**Comment by Echological** [comment]
> And I assume you have a reason why you have to fetch the url?

yeah, for the status code/ok.

**Comment by Echological** [comment]
> And just use prettier extension instead

as i said earlier, when I did it applied to other files, giving me a larger amount of problems, I ran it within my folder, doing what Encrypted stated.

**Comment by Slowlife01** [comment]
> > And I assume you have a reason why you have to fetch the url?
> 
> yeah, for the status code/ok.

I know that you used it for status check but why

**Comment by Slowlife01** [comment]
> > And just use prettier extension instead
> 
> as i said earlier, when I did, it applied to other files, giving me a larger amount of problems, I ran it within my folder, doing what Encrypted stated.

**extension**

**Comment by Slowlife01** [comment]
either that you didn't use prettier or not used our configs

**Comment by Echological** [comment]
> either that you didn't use prettier or not used our configs

maybe say that before i run the extension.

**Comment by Echological** [comment]
> Well, if you clone this repo it will use our configs

then i dunno how to explain it.

**Review by Bas950 — DISMISSED** [review]
Upload proof of it working

**Review by Slowlife01 — CHANGES_REQUESTED** [review]
*and address my reviews*

**Review by Setloth — COMMENTED** [review]
now what

**Review by Slowlife01 — CHANGES_REQUESTED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
