### PR TITLE
updated the main link

### PR DESCRIPTION
**Pull request by InvincibleAlex**
just trying to help...

### CODE REVIEW

**Review by StrikerFRFX — CHANGES_REQUESTED** [review]
Please provide proof of working on this new URL :smile:

**Comment by ririxidev** [comment]
und bump version lol

**Review by Bas950 — CHANGES_REQUESTED** [review]
Bump version, upload proof

**Comment by Bas950** [comment]
No response for a long time from @InvincibleAlex.

**Pull request closed without merging**
