### PR TITLE
chore(4chan): abandoning presence

### PR DESCRIPTION
**Pull request by Slowftw**
## Description 
I will no longer maintain this presence for ethical reasons.
I would like to delete it, but as it still works, I can only remove it from my profile ig.
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

### CODE REVIEW

**Review by EncryptedDev — APPROVED** [review]

**Comment by Slowftw** [comment]
@EncryptedDev I'm thinking of deleting the app

**Comment by EncryptedDev** [comment]
> @EncryptedDev I'm thinking of deleting the app

That's all good by Bas and I, go ahead

**Comment by Bas950** [comment]
Please delete the presence and metadata file in this pr

**Comment by Slowftw** [comment]
> Please delete the presence and metadata file in this pr

the entire folder?

**Review by Bas950 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
