### PR TITLE
Added mgservers presence

### PR DESCRIPTION
**Pull request by thevalleyy**
menu
Webinterface
Forum

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
lets start here i guess

**Review by EncryptedDev — COMMENTED** [review]
Countering that commit name, you haven't actually merged anything :/

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
this lmao

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
look at my review, please run eslint, fix the issues from eslint and prettify your code

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
run `prettier --write presence.ts` in the presence folder followed by `eslint --fix`

**Review by Slowlife01 — CHANGES_REQUESTED** [review]

**Review by Slowlife01 — CHANGES_REQUESTED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
