### PR TITLE
Exaroton -> exaroton

### PR DESCRIPTION
**Pull request by BluewyDev**
exaroton is supposed to not be capitalized according to its own branding rules.

### CODE REVIEW

**Comment by ririxidev** [comment]
ehhhh, doesn't really matter 🤔

**Comment by BluewyDev** [comment]
If that doesn't matter, then i don't see why it would matter to merge it..
The way it's done in this presence goes against exaroton's guidelines, imo neglecting those entirely because to you it doesn't matter seems a bit unlogical.

**Comment by ririxidev** [comment]
How big first letter is against exaroton's guidelines??? Guidelines are being accepted by user when they have account in their service, but not when you write their name somehere.

**Comment by BluewyDev** [comment]
They're not public, but the employees of exaroton have mentioned this lots of times.

Thanks anyway

**Pull request merged**
