### PR TITLE
Update Mangayabu

### PR DESCRIPTION
**Pull request by salvagod**
Mangayabu doesn't works since the dominion changed from ".com" to ".top"

### CODE REVIEW

**Comment by ririxidev** [comment]
Nor this, nor this doesn't work.

**Comment by salvagod** [comment]
> Nor this, nor this doesn't work. 

Understudied, sorry for the inconvenience.

**Comment by ririxidev** [comment]
I mean it is maybe for me only, site can be region locked, maybe someone else can check this?

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of the presence working with this change

**Comment by ririxidev** [comment]
no response from author - closing. feel free to open new pr after having proof of working presence

**Pull request closed without merging**
