### PR TITLE
S.to | s.to -> serien.sx

### PR DESCRIPTION
**Pull request by VirusBLITZ**
Fix for domain name changes.
see #4956

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Bump version and upload proof of working

**Review by VirusBLITZ — COMMENTED** [review]
bumped version

**Comment by VirusBLITZ** [comment]
How do I test this tho? :/

**Comment by VirusBLITZ** [comment]
How do I test this tho? :/

**Comment by EncryptedDev** [comment]
https://docs.premid.app/en/dev/presence#compiling

**Comment by VirusBLITZ** [comment]
hey again :D,
took me a bit to load the plugin but i'm sure its working :)
### Proof
-[Start page](https://i.imgur.com/ewbtiKS.png)
-[Watching](https://i.imgur.com/aSM6aZI.png)

thanks in advance!

**Comment by VirusBLITZ** [comment]
@EncryptedDev

**Review by EncryptedDev — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
