### PR TITLE
if you're reading this, i'm dumb (wip)

### PR DESCRIPTION
**Pull request by fr0r**

### CODE REVIEW

**Comment by ririxidev** [comment]
if it's wip why you do the pull request? bruh

**Comment by fr0r** [comment]
@ririxidev I WANTED TO BUMP MY FORK, THEN DO THE PR XDDDDDDDDDDDDDDDDDDDDD

**Comment by fr0r** [comment]
aight give me some minutes to do the proper description of this thing

**Comment by ririxidev** [comment]
:bruh:

**Comment by fr0r** [comment]
just going to close this, so i can do this properly this time xd

**Pull request closed without merging**
