### PR TITLE
fix(movie-web): update domains

### PR DESCRIPTION
**Pull request by vvirtues**
## Description 

`mw.lonelil.com` redirects to `mw.lonelil.ru` , so it hasnt been working, at least for me
should fix https://github.com/PreMiD/Presences/issues/8031 even though its smth else
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image
image
image

</details>

### CODE REVIEW

**Comment by vvirtues** [comment]
do I have to update a version number?

**Comment by vvirtues** [comment]
aight bet

**Review by theusaf — CHANGES_REQUESTED** [review]
To add a new domain, also update the `url` list.
Also, please provide proof of the change working.

**Comment by vvirtues** [comment]
proof added

**Review by DarkVillager — APPROVED** [review]
LGTM

**Review by vvirtues — COMMENTED** [review]
how do I remove ur requested changes bruh its broken

**Review by theusaf — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
