### PR TITLE
feat(HBO GO): add Asian url

### LINKED ISSUE #5614: HBO GO Asian Region
### Presence name

HBO GO

### Description

Discord Activity Not Displaying While Streaming On HBO GO in Asian Region.
The Link For HBO GO Asian Region is : https://www.hbogoasia.my/

### Alternatives

_No response_

### Additional context

HBO GO Asian Region

### PR DESCRIPTION
**Pull request by Northernside**
**Describe the changes in this pull request:**
Added www.hbogoasia.my (according to [this issue](https://github.com/PreMiD/Presences/issues/5614)) as an url (for the Asian HBO Go).

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

image

</details>

### CODE REVIEW

**Comment by ImRodry** [comment]
This should need a rebase

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Bump metadata version

**Review by EncryptedDev — DISMISSED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
rebase / solve conflicts

**Comment by Northernside** [comment]
@Bas950 Can you tell me how to implement your requested changes? I tried doing it but it still shows me unsolved changes.

**Comment by Bas950** [comment]
> @Bas950 Can you tell me how to implement your requested changes? I tried doing it but it still shows me unsolved changes.

seems like you only need to bump version rn

**Comment by Northernside** [comment]
> > @Bas950 Can you tell me how to implement your requested changes? I tried doing it but it still shows me unsolved changes.
> 
> seems like you only need to bump version rn

Done now but this still shows:
image

**Review by Bas950 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
