### PR TITLE
Added Manacube

### PR DESCRIPTION
**Pull request by Jackelele**
Fixed all issues and updated the logo and thumbnail.

### CODE REVIEW

**Review by Slowlife01 — DISMISSED** [review]
Looks good to me, I guess

**Review by Bas950 — CHANGES_REQUESTED** [review]
Just do setActivity once at the bottom...

**Review by Bas950 — CHANGES_REQUESTED** [review]
use `.textContent` instead of `.innerText`.
Upload new proof of it working afterwards

**Comment by Jackelele** [comment]
Applied changes as mentioned above.

new2
new1
new3

**Comment by Jackelele** [comment]
Bumping this it's been a while👍

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
