### PR TITLE
Added picotube.online Presences

### PR DESCRIPTION
**Pull request by picotube**
Finally Done the Pull request. Please Approve My site. Thank You

### CODE REVIEW

**Comment by SlowLife1661** [comment]
Isn't this a copy of Shiro, I-  

( ~~Also copy of my Presence~~ )

**Comment by picotube** [comment]
Yes We Have Same Script

**Comment by ririxidev** [comment]
@SlowLife1661 good point. Because of copying other website and copying presence code - I'm closing this pull request same with presence request. It's not acceptable for me to copy others work 1:1.

**Comment by picotube** [comment]
Who said it's copy and Do you even Know that shiro is dubbedanime.vip 's
copy. I Buy that script and I didn't copy the presences my friend write
that code..

**Comment by ririxidev** [comment]
shiro.is:
image
dubbedanime.vip:
image
and well I see that shiro.is is using either Vue or React so I know that their website is legit.

**Comment by picotube** [comment]
Bro It's Available for buying and the Script Owner is my frined. If you
still don't believe me then contact to the Shiro owner and ask him about
Rockey

**Comment by ririxidev** [comment]
🤷 This pull request is not going further anyway because of copying presence of @SlowLife1661. About site - I will talk about it with others and we will decide what to do with it (reopen service request or leave it closed)

**Comment by picotube** [comment]
And I don't Copy please don't say that. My friend write the copy and I just
added the file to my Folder.. I request you to Check that code again or If
you give me a chance then i can rewrite the code again Myself

**Comment by ririxidev** [comment]
We will decide what to do it.

**Comment by ririxidev** [comment]
@picotube Well, after discussing - your site is not going to be allowed on our store because of:
 - Lying to us:
   - First saying that shiro is copy of dubbedanime.vip then saying that shiro sells "script" I think you mean site. So technically you are trying to find some excuse why your site is copy too.
   - Well, We don't care if this presence was made by your friend or not - you still wanted to add it and it's copy of SlowLife's shiro's presence.

**Pull request closed without merging**
