### PR TITLE
fix(dアニメストア): discord rich-presence

### LINKED ISSUE #6633: dアニメストア
### Steps to Reproduce

I think it's using their old url in metadata.

Also if anyone is going to work on this, add altnames:
1. Docomo Anime Store
2. dAnime
3. dmkt

### Expected Behavior

Working

### Actual Behavior

Not working

### Page URL

https://animestore.docomo.ne.jp/

### Screenshots

_No response_

### Operating System

Windows 11

### Browser and Version

Edge

### Additional Comments

_No response_

### LINKED ISSUE #7183: About d anime store
### Steps to Reproduce

①add d anime with premid
②start playing
③Not reflected in status

### Expected Behavior

Not reflected in status

### Actual Behavior

Nothing happens

### Page URL

https://animestore.docomo.ne.jp

### Screenshots

_No response_

### Operating System

windows 11

### Browser and Version

110.0.5481.96

### Additional Comments

Edited to new link but d anime store doesn't work.
Anyone know the cause?

### PR DESCRIPTION
**Pull request by Gattxxa**
## Description 
The problem of opening the corresponding web page not being reflected as a Discord Rich Presence is resolved.
Resolves #6633
Resolves #7183 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by Isa27-0** [comment]
Add to your pull request description:

Resolves #6633
Resolves #7183

**Comment by Gattxxa** [comment]
changed description.

**Review by Bas950 — COMMENTED** [review]
tbh I dont see how this would've broken the presence before...

**Comment by Gattxxa** [comment]
It started with a friend saying that Presence was not reflected, and I tried it in my environment, but when I opened the web page and played the video, it was not reflected in Presence. Is it working in your environment?
https://animestore.docomo.ne.jp/animestore/sc_d_pc?partId=10463999
___

I am not familiar with typescripts so I can't be sure, but I think the cause is (await strings).play & (await strings).paused in [presence.ts](https://github.com/PreMiD/Presences/pull/7410/files#diff-fa90310da4fafa65e5dc960e06e3ee4a1ee2b0bb62ba5578d652a57f2b66f8a0L25-L27) I interpret these as notations when multiLanguage is set to true in metadata.json. And the following is a possible fix.

```typescript
smallImageText: isPlaying
  ? "string text"
  : "string text",
```
```typescript
// No display texts when mouse over smallImage. but, working.
smallImageText: isPlaying
  ? await strings.play
  : await strings.pause,
```
```typescript
// No display texts when mouse over smallImage. but, working.
smallImageText: isPlaying
  ? strings.play
  : strings.pause,
```

https://docs.premid.app/en/dev/presence/class#getstringsobject
https://docs.premid.app/en/dev/presence/guidelines#settings

**Comment by theusaf** [comment]
I'm closing this because I'm unable to reproduce the issue, and there's been no updates from anyone else in a while. it may be a random extension-related bug, but I wasn't able to find any obvious issues there either.

**Pull request closed without merging**
