### PR TITLE
Adding Neverlose Support

### PR DESCRIPTION
**Pull request by Africanized**
Making support for Neverlose.cc.

### CODE REVIEW

**Comment by ririxidev** [comment]
lol no

**Comment by GangMemberOreo** [comment]
huh?

**Comment by ririxidev** [comment]
we are not going to support csgo hacks forums ty thanks

**Comment by fir3z** [comment]
saw this on a discord.

this sudden closure of a pull request seems quite biased and tainted.
i suggest further review by someone else.
considering a rich presence does not necessarily promote or endorse it unless the viewer is interested?

**Comment by GangMemberOreo** [comment]
I completely understand your response, but isn't this a cheating forum? https://github.com/PreMiD/Presences/pull/629

**Comment by ririxidev** [comment]
Sorry, but in this time there was no checks if website is OK or not; It's 2021, I'm here and others as well. We are not trying to get our presence store to highest quality as possible. My check is not biased, but still like I said. We don't really want cheating forums on our store and probably eggsy's presence will be removed soon when there will be changes to presence to get them to our ESLint rules.

**Comment by GangMemberOreo** [comment]
Completely understandable, but it wasn't completely clear in the rules while I was making this presence.

**Comment by ririxidev** [comment]
I'm sorry for that as well; I will try to include it as soon as I will have time.

**Comment by GangMemberOreo** [comment]
Thanks! Hope you have a good rest of your day.

**Pull request closed without merging**
