### PR TITLE
🎉 Tailwind CSS and OneDrive Presences!

### PR DESCRIPTION
**Pull request by tarikcoskun**
A utility-first CSS framework that can be composed to build any design, directly in your markup.

moment1

moment2

moment3

moment4

### CODE REVIEW

**Comment by tarikcoskun** [comment]
OneDrive is an online file storage and sharing service from Microsoft.

moment1

moment2

moment3

moment4

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
You shouldn't use setActivity many times in the presence, you should use if, else if, else statements to declare presence details and at the end of the file, outside of your if, else if and else statements, but in your overall UpdateData, you should use <presence>.setActivity()

**Comment by tarikcoskun** [comment]
That was my first Presence so I was testing stuff and there are just some junks I left behind

**Comment by tarikcoskun** [comment]
@Bas950 got everything done, i guess

**Review by StrikerFRFX — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
