### PR TITLE
Added Linus Tech Tips Forum

### PR DESCRIPTION
**Pull request by DubStepMad**
**Name:** Linus Tech Tips Forum
**About:**
First commit, includes requested features from the following suggestion.
closes https://github.com/PreMiD/Presences/issues/2120

image

image

image

image

### CODE REVIEW

**Review by Bas950 — DISMISSED** [review]
Would look better if the logo background was transparent

**Comment by DubStepMad** [comment]
Changed the logo to be transparent.

**Comment by Bas950** [comment]
> Changed the logo to be transparent.

did you do for the presence itself as well?
If so please upload screenshot

**Review by Bas950 — APPROVED** [review]

**Comment by DubStepMad** [comment]
Currently it is still cached but I have updated it

image

**Comment by Bas950** [comment]
> Currently it is still cached but I have updated it
> 
> image

did you update the one in art assets (presence art assets) too?

**Comment by DubStepMad** [comment]
Updated my comment, I forgot to include a screenshot of that.

**Comment by Bas950** [comment]
> Updated my comment, I forgot to include a screenshot of that.

Yea I see! Aight you are all good then :)

**Review by Alanexei — APPROVED** [review]

**Pull request merged**
