### PR TITLE
Metadata File: Name Corrections

### PR DESCRIPTION
**Pull request by sineckers**

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Update versions, and if yasar was another dude you can add him as contributor.

**Comment by sineckers** [comment]
> Restore tsconfig.json to your presence folder. metadata.json too

wdym restore?

**Comment by kawakami** [comment]
My bad, nothing. I read wrong

**Comment by sineckers** [comment]
> Update versions, and if yasar was another dude you can add him as contributor.

It is my real name I was using it and changed now
updating versions 1.0.6

**Review by Bas950 — APPROVED** [review]

**Comment by sineckers** [comment]
when will it be merged ?

**Pull request merged**
