### PR TITLE
feat(Neovel): add regExp and showCover setting

### PR DESCRIPTION
**Pull request by RisingSunLight42**
### Changelog

- Add regExp to avoid useless list in the "url" metadata, I've removed the previous URLs to only keep `neovel.io`, the others are handled by the regExp. It's to avoid sensitive case like the site adds new URLs for new languages.
- Add showCover setting since it's frequently asked to the others presences, so I've anticipated a potential feature request.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

neovel_proof_1

neovel_proof_3

neovel_proof_2
</details>
<details>
<summary> Proof showing the regExp is working as expected </summary>

neovel_proof_4

</details>
<details>
<summary> Proof showing everything works fine after the change requested by Encrypted </summary>

neovel_proof_6

neovel_proof_7

neovel_proof_8

neovel_proof_5

</details>

### CODE REVIEW

**Review by EncryptedDev — COMMENTED** [review]
Storing the path as a variable and using it on reference may be less repetitive, what do you think?

**Comment by RisingSunLight42** [comment]
> Storing the path as a variable and using it on reference may be less repetitive, what do you think?

Totally true !

**Comment by RisingSunLight42** [comment]
> Storing the path as a variable and using it on reference may be less repetitive, what do you think?

I've done it in ebddbab6b5bedf210941973035d162c7145152eb, I don't know if there's a better way to do so, I'm not too much used in strings manipulation with TypeScript

**Comment by EncryptedDev** [comment]
That looks much better. Double check that works please and upload more proof

**Comment by RisingSunLight42** [comment]
> That looks much better. Double check that works please and upload more proof
Everything works as it should ! (I'll add those new screens in the PR's desc)

<details>
<summary>New screenshots</summary>

neovel_proof_6

neovel_proof_7

neovel_proof_5

neovel_proof_8
</details>

**Review by EncryptedDev — APPROVED** [review]

**Review by DarkVillager — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
