### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Baconz2**
Changed the tutorial, the way it was didn't work
Also changed some formatting.

### CODE REVIEW

**Comment by doomlerd** [comment]
It's not needed, at least on Windows.

**Comment by Baconz2** [comment]
weird, i couldn't get it working without the command line operator

**Comment by doomlerd** [comment]
What OS ( distro? ) are you using?

**Comment by doomlerd** [comment]
Closing this in 2 days if not answered.

**Comment by Baconz2** [comment]
Sorry, I totally didn't notice this

**Pull request closed without merging**
