### PR TITLE
Gmail presence | New logo update

### PR DESCRIPTION
**Pull request by blacbrue**
gmail new logo update

### CODE REVIEW

**Comment by SlowLife1661** [comment]
Bump version and the logo need to be updated in the Discord developer portal as well.

Better logo:

**Comment by jaydenkoh** [comment]
> Bump version ~and the logo need to be updated in the Discord developer portal as well~ or _was it already upfated_.
> 
> Better logo:
> 

yup I forgot about the discord developer thing but I will change the logo

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of it being changed in the Discord app too.

**Comment by jaydenkoh** [comment]
@Bas950 
Discord_YUmCF55dH1

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
