### PR TITLE
Youtube presence fix & upgrade

### PR DESCRIPTION
**Pull request by Rubensei**
Fixed the issue with duplicated channel name while viewing a video
Before fix:
image

After fix:
image

Added support for community post view page
image

EDIT: Added fix images

### CODE REVIEW

**Comment by doomlerd** [comment]
that's afaik only the TV version you updated which really isn't broken right now

**Comment by Rubensei** [comment]
Although that's actually fixing the issue, because if you check the lines 114-119 on `presence.ts`, the state assignment uses that value before any other

**Comment by Rubensei** [comment]
Sorry totally forgot the version 🤦‍♂

**Comment by Bas950** [comment]
uhm also upload a screen of the normal video thing working

**Pull request merged**
