### PR TITLE
🔼 Updated Radio.net

### PR DESCRIPTION
**Pull request by ACertainCoder**
1. Added new domains and pages
2. Fixed issues caused by structure changes on the site

- Tags will now be displayed again

- Play time will now be displayed correctly

- The play time no longer resets if the page updates or the song changes

### CODE REVIEW

**Comment by frozaum** [comment]
Hello, as of right now, we won't be able to review your pull request due to the temporarily locking of this repository that we announced in #1946, so we gladly request your patience until everything is sorted out. :)

**Comment by Bas950** [comment]
Unlocked (No longer on hold) - Please update your fork to get your Pull Request reviewed, if you don't do it within the next 3 days the Pull Request will be closed.

**Comment by doomlerd** [comment]
Update it again, it's still behind the main repo.

**Comment by ACertainCoder** [comment]
Done 👍

**Pull request merged**
