### PR TITLE
Added AniTube Presence

### PR DESCRIPTION
**Pull request by JetPlet**
image

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Dont think that apple is their logo?

**Comment by JetPlet** [comment]
> Dont think that apple is their logo?

I talked to the people on the site, and they told me that this is the other, but if you want I can put the other

**Comment by Bas950** [comment]
> > Dont think that apple is their logo?
> 
> I talked to the people on the site, and they told me that this is the other, but if you want I can put the other

I looked at their website and couldnt find anything related it :/

**Comment by JetPlet** [comment]
> > > Dont think that apple is their logo?
> > 
> > 
> > I talked to the people on the site, and they told me that this is the other, but if you want I can put the other
> 
> I looked at their website and couldnt find anything related it :/

I'll put the other one, ok?

**Comment by JetPlet** [comment]
image

**Review by ririxidev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
