### PR TITLE
Fixed TSC errors/warnings | Tesla presence

### PR DESCRIPTION
**Pull request by N0chteil**
https://github.com/PreMiD/Presences/runs/2291858848?check_suite_focus=true#step:7:20

Proof: 
Screenshot_315

### CODE REVIEW

**Comment by ririxidev** [comment]
No downgrade of version? Bump it to 1.0.4 doesn't matter.

**Comment by N0chteil** [comment]
1.0.2 -> 1.0.4*

**Review by ririxidev — APPROVED** [review]
Yes.

**Review by Bas950 — APPROVED** [review]
LGTM

**Pull request merged**
