### PR TITLE
Update Carl-bot

### PR DESCRIPTION
**Pull request by NMW03**
This PR fixes a bug on server name.

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Comment by Kai-JB1345** [comment]
The "Jump to Etc Etc"

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof

**Comment by NMW03** [comment]
gif

**Review by Bas950 — APPROVED** [review]

**Comment by NMW03** [comment]
docs gif

**Review by Bas950 — APPROVED** [review]

**Review by ririxidev — APPROVED** [review]

**Pull request merged**
