### PR TITLE
Fixed "Unknown page" for Games and Catalog

### PR DESCRIPTION
**Pull request by GRIPPERTV**
I saw that when going to "/games/" or "/catalog/", the path was different (on my Chrome). It was "/games#/" and "/catalog?Category=", and in the code checks if includes "/games/" and "/catalog/", so I just removed the "/" from the end (and worked perflecty).

The modifications are simple to resolve, but I am uncomfortable having to go to "/games" and the presence results is "Unknown page".

### CODE REVIEW

**Review by ririxichan — CHANGES_REQUESTED** [review]
bump version also give proof of working

**Comment by GRIPPERTV** [comment]
> bump version also give proof of working

image
As you can see, the first statement checks if the path includes `/games/`, and the result is false
In the second statement checks if the path includes `/games` (without the `/` at the end), and the result is true
Well, I think you can already consider that it works

After some redirect tests, the `#` is always included in the path, even if redirecting to `www.roblox.com/games`
image

**Comment by ririxichan** [comment]
I meant proof by showing on presence status but ok

**Comment by GRIPPERTV** [comment]
> I meant proof by showing on presence status but ok still bump version

Oh, 2.3.6

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of the presence working

**Comment by ririxichan** [comment]
No proofs from pull request creator. Closing.

**Pull request closed without merging**
