### PR TITLE
chore(Komik Indo): update website URL and version to 1.0.3

### PR DESCRIPTION
**Pull request by 1intan99**
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
image
Changing Komik Indo URL from `komikindo.tv` to `komikindo.cx`
image

### CODE REVIEW

**Comment by darkvillager2** [comment]
Provide screenshots of ur change working

**Comment by 1intan99** [comment]
> Provide screenshots of ur change working

It's there, on my VSCode

It says "You commited ...."

**Comment by darkvillager2** [comment]
> > Provide screenshots of ur change working
> 
> It's there, on my VSCode
> 
> It says "You, 3 minutes ago ...."

Show that the presences works...

**Review by theusaf — CHANGES_REQUESTED** [review]
The URL here doesn't appear to be correct (at least in my country). Since it seems to change often, consider using the `regExp` field.

**Comment by theusaf** [comment]
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

**Pull request closed without merging**
