### PR TITLE
feat(Prime Video): rewrite presence

### PR DESCRIPTION
**Pull request by veryCrunchy**

### CODE REVIEW

**Comment by theusaf** [comment]
Doesn't this collide with the Amazon presence? The url should already be matching through the regex

**Comment by veryCrunchy** [comment]
Url isn't used if there's a regex right?
Added the url for looks.
So users can see that it actually work's when watching on amazon.com on the store page.

**Comment by theusaf** [comment]
> Url isn't used if there's a regex right? Added the url for looks. So users can see that it actually work's when watching on amazon.com on the store page.

Here's the current extension's code: It uses `url` if `regExp` doesn't match.
```ts
presence = presences.find((presence) => {
				const { url, regExp } = presence;

				// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
				if (regExp && new RegExp(regExp).test(tab.url!)) return true;

				// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
				if (Array.isArray(url) && url.some((url) => tab.url!.includes(url)))
					return true;

				// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
				if (!Array.isArray(url) && tab.url!.includes(url)) return true;

				return false;
			});
```

**Comment by veryCrunchy** [comment]
I see, even then it shouldn't be an issue.
The pages the presence check for don't exist on the amazon website, so those will never match anyway

**Comment by veryCrunchy** [comment]
But I should test it, thank you for bringing that up.
Will mark this pr as a draft for now.

**Comment by theusaf** [comment]
Closing for inactivity. This may be reopened later if needed.

**Pull request closed without merging**
