### PR TITLE
Update Aternos presence.

### PR DESCRIPTION
**Pull request by Allvaa**
- fix "Home Page" text on presence when it is on the panel page
- change "Configuring Server" to "Panel"
image

### CODE REVIEW

**Comment by doomlerd** [comment]
Why did you remove TypeScript files?

**Comment by Allvaa** [comment]
> Why did you remove TypeScript files?

Sometimes I forget to compile it, so i use js instead

**Comment by doomlerd** [comment]
> Sometimes I forget to compile it, so i use js instead

Just revert to TS, we'll remind you if you forget it.

**Comment by Allvaa** [comment]
ok done. could this merged right now?

**Pull request merged**
