### PR TITLE
feat(jut.su): more paths, some grammar corrections, switch case

### PR DESCRIPTION
**Pull request by StavZ**
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

image

image

image

</details>

### CODE REVIEW

**Review by EncryptedDev — APPROVED** [review]

**Comment by DarkVillager** [comment]
@StavZ Please take over the presence.

**Comment by StavZ** [comment]
> @StavZ Please take over the presence.

Should I create new application? For presence

**Comment by StavZ** [comment]
as I can see you changed the client id when took the ownership
image

**Comment by DarkVillager** [comment]
> > @StavZ Please take over the presence.
> 
> Should I create new application? For presence

sure

**Comment by StavZ** [comment]
> 

Can I get assets for play/pause icon?

**Comment by DarkVillager** [comment]
> Can I get assets for play/pause icons?

```ts
enum Assets {
	Paused = "https://i.imgur.com/4iyMINk.png",
	Play = "https://i.imgur.com/OLaz6JN.png",
}
```

**Comment by StavZ** [comment]
ty

**Comment by StavZ** [comment]
<details>
<summary> Screenshots with new application </summary>


image

image

image

image

</details>

**Review by DarkVillager — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
