### PR TITLE
fix(9anime): fix presence

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

* Added video detection, instead of url detection due to changes in variants of 9anime
* Added button
* Added more title/episode options
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by DarkVillager** [comment]
> fyi, 9animetv.to is a fake website. For all the official domains go to 9anime.me

Okay good for u.

**Comment by Extiriority** [comment]
> > fyi, 9animetv.to is a fake website. For all the official domains go to 9anime.me
> 
> Okay good for u.

it's like supporting a fake clone bank website that steals your info. Also just make sure it works the same as the official domains if it's 1 to 1.

**Comment by DarkVillager** [comment]
> > > fyi, 9animetv.to is a fake website. For all the official domains go to 9anime.me
> > 
> > 
> > Okay good for u.
> 
> it's like supporting a fake clone bank website that steals your info. Also just make sure it works the same as the official domains if it's 1 to 1.

I get that. Since the domain changes that often we support all 9anime sites but recommend to only use the official ones.

**Comment by Slowlife01** [comment]
> > > > fyi, 9animetv.to is a fake website. For all the official domains go to 9anime.me
> > > 
> > > 
> > > Okay good for u.
> > 
> > it's like supporting a fake clone bank website that steals your info. Also just make sure it works the same as the official domains if it's 1 to 1.
> 
> I get that. Since the domain changes often we support all 9anime sites but recommend to only use the official ones. 

Why are you adding additional selectors then

**Comment by DarkVillager** [comment]
> > > > > fyi, 9animetv.to is a fake website. For all the official domains go to 9anime.me
> > > > 
> > > > 
> > > > Okay good for u.
> > > 
> > > 
> > > it's like supporting a fake clone bank website that steals your info. Also just make sure it works the same as the official domains if it's 1 to 1.
> > 
> > 
> > I get that. Since the domain changes often we support all 9anime sites but recommend to only use the official ones.
> 
> Why are you adding additional selectors then. I think the selectors I wrote only work on the official site

They work on some pages of the official website.

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
