### PR TITLE
CoinMarketCap presence

### PR DESCRIPTION
**Pull request by jonasrdl**

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Hello, once again, I will be closing your pull request due to the following reason: 
- Low quality presence - presence does not have much to it and should support more features (if applicable)

Before opening another pull request, please take a moment to read the [presence guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md). Alternatively, open a discussion requesting the presence to be made for you.

**Comment by jonasrdl** [comment]
Hello,
sorry for the inconvenience. Unfortunately, I don't quite understand how I can improve the presence. I oriented myself to other presences that are structured in a similar way to mine. But thanks anyway :).

**Comment by EncryptedDev** [comment]
I had a quick look at the website and I can see they have lots of features that you just haven't supported.

**Comment by jonasrdl** [comment]
Okay, I'll take another look at the website and add more features. Thank you very much!

**Pull request closed without merging**
