### PR TITLE
Adding MyDramaList to the presence store

### PR DESCRIPTION
**Pull request by kikocodes**
Browing the homepage
image

Browsing Articcles
image

Reading an article:

image

Searching for a show:

image

Looking at a show page:

image

Looking at actors:

image

### CODE REVIEW

**Comment by frozaum** [comment]
Hello, as of right now, we won't be able to review your pull request due to the temporarily locking of this repository that we announced in #1946, so we gladly request your patience until everything is sorted out. :)

**Comment by Bas950** [comment]
Unlocked (No longer on hold) - Please update your fork to get your Pull Request reviewed, if you don't do it within the next 3 days the Pull Request will be closed.

**Comment by Bas950** [comment]
Its okay to not be okay was really good btw xD

**Comment by kikocodes** [comment]
> Its okay to not be okay was really good btw xD

Yes it was hahaha, I really enjoyed it. And how should I update the fork, sorry it's my first time using GitHub in years 😅

**Comment by Bas950** [comment]
> > Its okay to not be okay was really good btw xD
> 
> Yes it was hahaha, I really enjoyed it. And how should I update the fork, sorry it's my first time using GitHub in years 😅

I think you have to go to https://github.com/kikocodes/Presences/compare/master...PreMiD:master and make the pr.
I usually do it in github desktop.. way easier...

**Pull request merged**
