### PR TITLE
Added Max16K

### PR DESCRIPTION
**Pull request by OGMatrix**
ss2
ss3

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Seems really basic; not much too it 🤷🏼

**Comment by EncryptedDev** [comment]
And the category in the metadata.json is broken xD

**Comment by ririxidev** [comment]
Heya @OGMatrix! We have some news for you that you should take look at:
We are so sorry but we need to deny your pull request regarding this presence due of:
 - Low quality site and presence.
 
Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by OGMatrix** [comment]
> Heya @OGMatrix! We have some news for you that you should take look at:
> We are so sorry but we need to deny your pull request regarding this presence due of:
> 
> * Low quality site and presence.
> 
> Thanks,
> **ririxi**. PreMiD Reviewer Team.
> Contact: [mail@ririxi.dev](mailto:mail@ririxi.dev), ririxi#2721

I have made one really low quality Presence too and it got accepted so why this got declined?

**Comment by EncryptedDev** [comment]
> > Heya @OGMatrix! We have some news for you that you should take look at:
> > We are so sorry but we need to deny your pull request regarding this presence due of:
> > 
> > * Low quality site and presence.
> > 
> > Thanks,
> > **ririxi**. PreMiD Reviewer Team.
> > Contact: [mail@ririxi.dev](mailto:mail@ririxi.dev), ririxi#2721
> 
> I have made one really low quality Presence too and it got accepted so why this got declined?

You're literally checking their URL and setting static data - at least try to grab elements from the DOM. Anyway, nice honesty lmao

**Pull request closed without merging**
