### PR TITLE
Added 5Mods Presence

### PR DESCRIPTION
**Pull request by OfficialCRUGG**
Added Presence for 5Mods / https://www.gta5-mods.com/ (They call themselves 5Mods and thats also their logo)
This had been lying around on my hard drive for a few weks now already, but I just checked and it's still working.
image
image

### CODE REVIEW

**Comment by doomlerd** [comment]
Imo the presence is not suited for the games category as the site's not a game

**Comment by OfficialCRUGG** [comment]
Then NameMC, Steam, Game Jolt, Aternos, MinecraftForge, LabyMod, TruckersMP and many more shouldn't be in there either. Also I even asked on the discord and everyone said yes. Basically 80% of sites in that category are Gaming Wikis, Mod Stores, Mods themselves etc.

**Comment by frozaum** [comment]
As what @OfficialCRUGG said, we have a lot of presences that aren't games, but are game-related (like wikis, game/mod stores, minecraft servers, etc) on the games category since the category was launched.

**Comment by frozaum** [comment]
This presence is game-related, showing mods, free to download, for the game GTA V.

**Pull request merged**
