### PR TITLE
BestRP.pl | Website Presence

### PR DESCRIPTION
**Pull request by Dom-in**
Looks of it -> https://cdn.discordapp.com/attachments/770033408100401183/787995436292112394/unknown.png

Presence is made by me for forum of fivem server

### CODE REVIEW

**Comment by ririxidev** [comment]
Sorry but We can't get any whois data from this domain. Could you give us some proof that this domain is 2 months old?

**Comment by Dom-in** [comment]
> Sorry but We can't get any whois data from this domain. Could you give us some proof that this domain is 2 months old?

Its not 2 month old its like 1 month old i think. :(

**Comment by Dom-in** [comment]
oh sorry
i know problem i did

**Comment by ririxidev** [comment]
So we can't merge it even if it would be presence without any errors from Codacy. Sorry. Feel free to open new pull request when it will be 2 months old

**Comment by Dom-in** [comment]
I puted wrong domain its BestRP.pl

**Pull request closed without merging**
