### PR TITLE
Added GTA5 Mods Presence

### PR DESCRIPTION
**Pull request by Cobbrou**
Name of the service:
GTA5-Mods

URL to website:
https://www.gta5-mods.com

Issue related : 
https://github.com/PreMiD/Presences/issues/3882

Screenshots:
image
image
image
image
image

_This is my first pull request and contributing to a repo so don't be rude 👍🏻_

### CODE REVIEW

**Comment by ririxidev** [comment]
I'm sorry but we need to decline your presence due of;
 - Presence doesn't use DOM a lot and only uses it to show name of something?
 - No support for forums
 - Not a lot of functionality.
 - No imgur links
 - By using array deconstructing you broke your code 
 ```javascript
[ searchMod ] = "";  //* not working
[, , searchMod] = ""; //* working
 ```

**Comment by Cobbrou** [comment]
Okay no problem :) But if I fix everything, can I remake an PR or the presence for GTA5 Mods can't be accepted ?

**Comment by ririxidev** [comment]
Yes site is qualified for presence but your presence just needs more things. And yes you can do another one.

**Comment by Cobbrou** [comment]
Okay thanks ! I will try to make my best to do it ! :)

**Pull request closed without merging**
