### PR TITLE
Marktplaats Updated to 1.0.2

### PR DESCRIPTION
**Pull request by DarkVillager**
Added Search
Added Cars
Added Car Search

### CODE REVIEW

**Review by ririxidev — CHANGES_REQUESTED** [review]
Show proof of working presence on new sites

**Comment by DarkVillager** [comment]
markplaats1 1
marktplaats2 1
marktplaats3 1

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Comment by DarkVillager** [comment]
> bump version

I did. Original version was 1.0.0 this one is 1.0.1

**Review by ririxidev — APPROVED** [review]
Looks fine for me!

**Pull request closed without merging**
