### PR TITLE
Added Harmony Radio Presence

### PR DESCRIPTION
**Pull request by xxdjbobbyxx**
I have added Harmony Radio as a Presence and removed the Symphony files as Symphony cannot be released yet.

I will attach a image of the presence working  below

image

### CODE REVIEW

**Comment by ririxidev** [comment]
We need stats from this radio station because as far I know it only has >10 listeners and fix codacy errors.

**Comment by xxdjbobbyxx** [comment]
I never saw this and that is correcct there stats are below those requirements

**Comment by ririxidev** [comment]
So sorry, but we can't accept this radio station then. There are a lot of radio stations that has >10 listeners + have same software everywhere and same presence ofc (getting everything from api). So, sorry but we can't accept this then.

**Comment by xxdjbobbyxx** [comment]
Can I just ask where can I find that rule?

**Comment by ririxidev** [comment]
https://github.com/PreMiD/Presences/blob/master/.github/CONTRIBUTING.md

**Pull request closed without merging**
