### PR TITLE
Add imgs.bar presence

### PR DESCRIPTION
**Pull request by ghost**
proof
settings

### CODE REVIEW

**Comment by SlowLife1661** [comment]
Hello, we've decided to **decline** your Pull Request due to the following reasons:
- **Low quality** Presence.
    - Not reading much DOM, show small amount of info.
    - Low quality code.
- **Unable** to review the site.
    - As the site is apparently invite-only, therefore we were unable to review the site.

**Comment by f7nl4y** [comment]
how the fuck did pays.host geta presence nigga they are invite only

**Comment by f7nl4y** [comment]
@SlowLife1661

**Comment by f7nl4y** [comment]
XDXDXDXDXDXDXDXDXDXDXDXDXD

**Comment by f7nl4y** [comment]
DXDXD COCK

**Pull request closed without merging**
