### PR TITLE
Presences cleanup

### PR DESCRIPTION
**Pull request by brunohpaiva**

### CODE REVIEW

**Comment by Bas950** [comment]
@brunohpaiva why you rewriting presences themself? I dont think you should.

**Comment by CobyPowers** [comment]
I don't see very much of a point in this.

**Comment by Bas950** [comment]
yea same @CobyPowers, I mean he can do the presence system like he did here: https://github.com/PreMiD/Presences/pull/225/commits/a603049ba1ab0891228da26ad6d24e0d7d674d9c

But I dont think he should do the presences themself. Like now I have to look back at the presence I wrote and see how he changed it. If he added stuff to it I wouldn't have a problem with it but he is "rewriting" the whole presence. It isn't broken so I dont get why he is rewriting it. He didn't even ask the presence makers if he could do this.

**Comment by Timeraa** [comment]
Okay, lets give my point in this:
I don't have anything against improving code, yes it may make reading the presence harder but hey, we are open source, everyone can improve or make things different. That's the point of Open Source.

**Comment by Bas950** [comment]
I mean whats the point of making a presence if bruno comes along and rewrites it? Why doesn't he just make all presences then @Timeraa ? I am putting time and effort into it and it just gets rewritten without notifying me on forehand. So no sorry but I don't agree with it.

**Comment by brunohpaiva** [comment]
Hello,
This pull request is just a _draft_, project maintainers can just close it...
Speaking of _your_ Amazon presence, in my view it's not a rewrite, I just simplified the IF's, removed some duplicate/unused code, and improved the `#searchDropdownBox` presence to respond to `onchange` events.

```JavaScript
if(document.location.hostname == "www.amazon.com" || document.location.hostname == "www.amazon.com.au" || document.location.hostname == "www.amazon.de" || document.location.hostname == "www.amazon.ca" || document.location.hostname == "www.amazon.cn" || document.location.hostname == "www.amazon.es" || document.location.hostname == "www.amazon.fr" || document.location.hostname == "www.amazon.nl" || document.location.hostname == "www.amazon.in" || document.location.hostname == "www.amazon.co.jp" || document.location.hostname == "www.amazon.ae" || document.location.hostname == "www.amazon.co.uk" || document.location.hostname == "www.amazon.com.tr" || document.location.hostname == "www.amazon.com.br") {
  //
}
```

I've changed the [above IF statement](https://github.com/PreMiD/Presences/blob/master/Amazon/presence.ts#L48) in your version to just this regex test:

```JavaScript
const AMAZON_URL_REGEX = /www\.amazon\.(de|ca|cn|es|fr|nl|in|co\.jp|ae|co\.uk|com(\.(tr|br|au))?)/;

if (hostname.match(AMAZON_URL_REGEX) === null) {
  presence.setActivity();
  presence.setTrayTitle();
  return;
}
```

> whats the point of making a presence if bruno comes along and rewrites it?

The presence is for the community, you wrote the presence and I just wanted to improve it.

#### Astiga presence

- Removed some unnecessary variables, methods and IF statements
- Simplified the current time and duration calculations

#### BraniTube presence

- Fixed the `video` element query selector
- Removed unnecessary call to `document.querySelector` inside `UpdateData` event handler
- Simplified `presenceData` assignments

#### AniList presence

- Removed unnecessary calls to `delete`
- Better user page and search page details
- Changed some variable's position/name

#### Anime4You presence

- Removed unnecessary calls to `presence.setActivity` inside IF statements

#### Change.org presence

- Fixed `innerText` calls to undefined elements in finalized petitions

Not considering the file size decrease in some presences

**Comment by Bas950** [comment]
@brunohpaiva 
Thanks for your reply, for me it just looked like you wanted to rewrite them so they suite your writing taste as there was also not a "changelog" or something like you did now explaining why you did it and what. About the amazon presence, I thought regex wasn't working yet thats why I wasn't using it. I see the changes you made, they aren't how I would write them but I hope it works, it also kinda makes it easier to read. Sorry that I was kinda triggered about it, because of how I viewed it; for me you just came out of the blue and "rewrote" the whole presence. Maybe you could send me a message on discord how I could improve the current way of how I write the presences, as I still have a big list todo so you don't have to clean them up. (Bas950#0950) I see why you are doing it, but to me it still kinda looks like a waste of time for you if nothing changes for the presence itself, just the code. But I guess you like cleaning up code 👍 

Sorry again, Bas

**Comment by Bas950** [comment]
Also @brunohpaiva at the moment none of your changes will work since you didnt update the version in metadata for each presence you changed 😉

**Comment by Timeraa** [comment]
> Also @brunohpaiva at the moment none of your changes will work since you didnt update the version in metadata for each presence you changed 😉

They do but in the next beta this behaviour will change

**Comment by OfficialCRUGG** [comment]
Looks pretty okay so far, however, could you please add the timestamp function in my Anime4You Presence back? While it is currently unused, I'm just waiting for @Timeraa to update how Iframe Scripts work so I can use timestamps.

**Comment by brunohpaiva** [comment]
I'll close this pull request for now, college and work are taking up a lot of my time.

**Pull request closed without merging**
