### PR TITLE
📺 Added BluTV and Diziay Presence

### LINKED ISSUE #886: Request | diziay.me
**Prerequisites and essential questions** 
* [ ] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?**  
♔ ♕ 【Emir「SmileFate」】#9595
**What's the name of the service?** 
https://diziay.me | diziay
**What should the Presence display?** 
series and movie tracking information
**If possible, please provide a logo for the service (512x512 minimum)** 
https://diziay.me/views/default/assets/img/logo.png

### PR DESCRIPTION
**Pull request by emirkabal**
closes #886 

# BluTV

browsing
watching series
watching movies
watching tv channels

# Diziay

browsing
watching series
watching movies

### CODE REVIEW

**Comment by doomlerd** [comment]
add "closes #886" to the description of your PR.

**Comment by Bas950** [comment]
also maybe use these small image keys: https://github.com/PreMiD/Presences/tree/master/.resources
since they are used by a lot of other presences so we keep them kinda the same over other presences.

**Comment by emirkabal** [comment]
> also maybe use these small image keys: https://github.com/PreMiD/Presences/tree/master/.resources
> since they are used by a lot of other presences so we keep them kinda the same over other presences.

blutv
diziay

**Comment by doomlerd** [comment]
> add "closes #886" to the description of your PR.

**Comment by emirkabal** [comment]
> > add "closes #886" to the description of your PR.

yey

**Comment by Bas950** [comment]
> > > add "closes #886" to the description of your PR.
> 
> yey

No you need to add it in here (the PR (pull request)), you edit your message all the way at the top so it includes closes #886

**Comment by emirkabal** [comment]
> > > > add "closes #886" to the description of your PR.
> > 
> > 
> > yey
> 
> No you need to add it in here (the PR (pull request)), you edit your message all the way at the top so it includes closes #886

ok

**Pull request merged**
