### PR TITLE
fix(presenceUpdater): use api types in compiler options

### PR DESCRIPTION
**Pull request by theusaf**
## Description 

* Should fix compilation of presences.
* See https://github.com/microsoft/TypeScript/issues/23564#issuecomment-383092947

## Acknowledgements
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

### CODE REVIEW

**Comment by Slowlife01** [comment]
Needs to do this for `target` too. I tested it.
And why not just hard code it?
image

**Comment by theusaf** [comment]
> Needs to do this for `target` too. I tested it. And why not just hard code it? image

Strangely, I didn't have that problem with `target`, but I'll add that just in case. The reason I'm not hardcoding it is so that only the `tsconfig.json` file needs to be changed to change the `target`/`moduleResolution`

**Comment by Slowlife01** [comment]
> > Needs to do this for `target` too. I tested it. And why not just hard code it? image
> 
> Strangely, I didn't have that problem with `target`, but I'll add that just in case.

This is just to fix to warnings with stuff like `String.replceAll()`

> The reason I'm not hardcoding it is so that only the `tsconfig.json` file needs to be changed to change the `target`/`moduleResolution`
I figured that would be your reason. Whatever, I guess

**Comment by theusaf** [comment]
Closing as CI was updated, which appears to fix this issue.

**Pull request closed without merging**
