### PR TITLE
fix(GoGoAnime): domain name change

### PR DESCRIPTION
**Pull request by DMCroww**
## Description 
Adjusted the RegExp to aligh with new domain of GoGoAnime (anitaku), including necessary changes to iFrame RegExp.
Added more natural description alongside with few translations.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

image

</details>

### CODE REVIEW

**Comment by DMCroww** [comment]
Most of the domains I know of redirect to Anitaku domain.
"gogoanime.news" redirects to "gogotaku.info"
They're apparently moving the domains (see img below).
I didn't realize there still were any of the old domains still valid.
I'll update the regex in a way where it would accept both, but considering it wasn't working on the main ones for about 3months now, and only now someone (me) got fed up enough to fix it, i dont think it would be that much of an issue, unless theres more of the old ones that are still in use.


<details>Popup about redirect and domain change:
<summary>

image

</summary>
</details>

**Comment by veryCrunchy** [comment]
Include the page .news redirects to rather than removing it completely.

**Comment by DMCroww** [comment]
Domains added. Any other notes?

**Review by DarkVillager — APPROVED** [review]
LGTM

**Review by theusaf — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
