### PR TITLE
fix(Animevietsub): domain name change

### PR DESCRIPTION
**Pull request by tedomi2705**
## Description 

RegExp is causing some problem on stable extenions so i removed it (https://discord.com/channels/493130730549805057/607524579874832446/1251194240042664087)
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

</details>

### CODE REVIEW

**Review by theusaf — APPROVED** [review]
The old regex looks fine to me, are you certain that it was the regex causing the issue, and not something else?

**Comment by tedomi2705** [comment]
> The old regex looks fine to me, are you certain that it was the regex causing the issue, and not something else?

Yes as i noticed from #8434 it works only in beta extension, after the pull is merged it doesnt work

**Comment by Bas950** [comment]
> > The old regex looks fine to me, are you certain that it was the regex causing the issue, and not something else?
> 
> 
> 
> Yes as i noticed from #8434 it works only in beta extension, after the pull is merged it doesnt work

Was the previous presence version released? @Timeraa

**Comment by Slowlife01** [comment]
The message you linked is from before the extension update so it was still using the old presence version (Before the RegExp update)

**Comment by tedomi2705** [comment]
Okay i will investigate more about this

**Pull request closed without merging**
