### PR TITLE
Updated Maki.gg

### PR DESCRIPTION
**Pull request by m5rian**
I needed to update the code again because of website changes.

### CODE REVIEW

**Comment by Slowlife01** [comment]
Update your fork

**Comment by Slowlife01** [comment]
Bump version and show proof of it working

**Comment by M5rian** [comment]
I already increased the version tag.
Here is the proof: 
image

**Comment by Slowlife01** [comment]
image
don't think so

**Comment by M5rian** [comment]
Huh? I'm confused. What's this then?
https://github.com/PreMiD/Presences/pull/4275/commits/83d4c09e1f948306e7b41e942fbc7eab58bb07de

**Comment by Slowlife01** [comment]
just bump it again

**Comment by Bas950** [comment]
> Huh? I'm confused. What's this then?
> [83d4c09](https://github.com/PreMiD/Presences/commit/83d4c09e1f948306e7b41e942fbc7eab58bb07de)

Thats you bumping it before you fixed your comflicts.  The presence is already that version.

**Comment by M5rian** [comment]
Oh I see. Sorry for the delay

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
