### PR TITLE
ReaperX Presence Update

### PR DESCRIPTION
**Pull request by InwTanRew**
Just change hostname/URL

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Comment by InwTanRew** [comment]
> bump version

Fixed

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of it working

**Comment by InwTanRew** [comment]
Fix missing ) expected

**Comment by ririxichan** [comment]
fix codacy error

**Comment by InwTanRew** [comment]
Fixed the proof i showing when am wake up am going to sleep

**Comment by InwTanRew** [comment]
image
 Here you are

**Review by Bas950 — APPROVED** [review]
upload proof of it working

**Review by Timeraa — APPROVED** [review]

**Pull request merged**
