### PR TITLE
Roblox Developer Forum | devforum.roblox.com

### PR DESCRIPTION
**Pull request by Swardoric**
**Prerequisites and essential questions** 
* [x] Is it a popular site?
* [x] Is the website older than 2 months? 
* [ ] Is the site locked to a specific country/region?
* [ ] Is the site a paid service? (e.g. Netflix, Hulu)
* [ ] Does the website feature NSFW content? (e.g. porn, etc...)
* [ ] Are you a donator/patron?
* [ ] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 
Swardoric#9725
**What's the name of the service?** 
Roblox Developer Forum
**What should the Presence display?** 
Presence will display the post you are reading, the page you are on, the category you are in and if you are set up your account.
**If possible, please provide a logo for the service (512x512 minimum)** 
RDF_icon

### CODE REVIEW

**Comment by Bas950** [comment]
Why dont you just update the current roblox presence and add this?

**Comment by Swardoric** [comment]
> Why dont you just update the current roblox presence and add this?

The Forum is different from the site, that's why I create a presence for it

**Comment by Alanexei** [comment]
Some websites have forums, byte.co for example. You should have still added it to the roblox presence. Also you should remove the heavy lifting function.

**Comment by doomlerd** [comment]
The forum is basically just a sub-domain, and they're supported too but not when they can be part of the main domain. Sorry, but you'll have to revert these changes and add it to the main presence ( don't forget to increment the version! )

**Pull request closed without merging**
