### PR TITLE
fix(Youtube Music): timestamp fix

### PR DESCRIPTION
**Pull request by ION606**
## Description 

* Fixed the issue where the start timestamp would malfunction when changing from `use time left` mode.

This issue was caused due to the [getTimestamps](https://github.com/PreMiD/Extension/blob/release/src/util/presence/devHelper.ts#L527) function, which for SOME REASON completely ignores the first parameter in favor of using `Date.now()`

possibly resolves https://github.com/PreMiD/Presences/issues/8131

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>

image

image

<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by veryCrunchy** [comment]
Will be fixed in the extension.

**Comment by ION606** [comment]
so...should I just remove this or........

**Comment by veryCrunchy** [comment]
Yes

**Comment by ION606** [comment]
I'm keeping the branch open in case there's something in there that'll be needed later

**Comment by veryCrunchy** [comment]
Please use a new branch for new changes

**Pull request closed without merging**
