### PR TITLE
Added Discord.fr presence 

### PR DESCRIPTION
**Pull request by BenNotix**
> **Screenshots of working**

> HomePage	homepage
> Wiki	wiki
> Blog	blog
> Server page 	server
> Forms 1	forms1
> Forms 2	forms2
> Forms 3	forms3
> Privacy 	privacy
> Staff	staff
> Status	status
> Support	support

### CODE REVIEW

**Comment by ririxidev** [comment]
Heya @BenNotix !
We are so sorry but we need to deny your pull request regarding this presence due of:
 - Low quality presence - no DOM readings
 - Site is qualified as not ready for presence in PreMiD.
 
Regards,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721.

**Comment by IchiiDev** [comment]
Hey @ririxidev 
I would like to have some additional infos about the issue here, what do you mean by "Site is qualified as not ready for presence in PreMiD" ?
We searched through your guidelines and there are not any rules our website might break. How do you define that a website is "ready" or not and how can we manage to fix this issue ?

Thank you in advance😄
Ichii

**Comment by ririxidev** [comment]
Yo @IchiiDev,
Like I specified your presence doesn't do DOM readings in anyway, likely we name it "static presence" - that we don't qualify as good presence to be in our store. Other thing is that your site or site that you want in our store is really site that only has wiki and blog and well this blog is not really maintained from what I see. Wiki is what I can say copy of discordia.me and fandom discord wiki. So I mean, I can ask other Presence Reviewers and include their opinions about it because here for you.

**Comment by IchiiDev** [comment]
Hey @ririxidev,
Firstly, it does not seem like it but we're actively working on making new blog posts & introducing more wiki articles, this is something that takes time and we haven't been able to produce much lately due to organizational needs and a lack of free time. Our team is still small and it takes time to produce quality content instead of quantity. More will come during the next weeks. 
Secondly, I understand that the idea of a Discord wiki isn't very new or original but as it was not already done in French, we made this to help French users get informations. Plus, I don't know what you may think about our content, but the wiki articles we add are written in many cases by our community and isn't just a rip-off translation of discordia.me or Discord's Fandom. 
I truly understand that our presence is poorly made and we will work on a valid presence on your terms during the next weeks. But it saddens me to see that our work is rejected because people thinks that it is a rip-off of something that is just already made but not for the public we aim at. Our website is one of the most referenced on Google (at least in France) we won't risk to steal the work of Discordia.me.

Best regards,
Ichii

**Comment by ririxidev** [comment]
About ripping off the content of discordia.me - I never wanted to suggest something like that. More likely I wanted to say that you are just doing same content as their site. So no worries, but yeah. If you all are going to make your presence better, feel free to do so maybe it will land it in our store 😉 Good luck 😄

**Pull request closed without merging**
