### PR TITLE
Removed atomicradio presence

### PR DESCRIPTION
**Pull request by VocalZero**

### CODE REVIEW

**Comment by InstabilSpielt** [comment]
With the commit we delete our entire presence due to the closure of our project (more information [here](https://atomicnetworks.eu)), thank you for the partnership! 💜

**Comment by ririxidev** [comment]
Please contact Bas950 or Fruxh on discord later for removal from our partnership page.

**Comment by ririxidev** [comment]
Also fix conflicts.

**Comment by VocalZero** [comment]
done

**Pull request merged**
