### PR TITLE
fix(dアニメストア): old request

### PR DESCRIPTION
**Pull request by neco222**
"I changed the link from the old one to /animestore/tp_nm."

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Bump metadata version, upload proof of it working.

**Comment by neco222** [comment]
I'm new to GitHub. I don't understand what you mean.
The creator of the code "Eai" said that it can be corrected by changing the link

**Comment by neco222** [comment]
https://github.com/PreMiD/Presences/pull/7295
I wanted to edit in the same place, but I couldn't.

**Comment by neco222** [comment]
Screenshot_20230416_120243_Chrome

**Comment by neco222** [comment]
https://github.com/PreMiD/Presences/pull/7296 Get new request at link

**Pull request closed without merging**
