### PR TITLE
feat(Anime4Life): new presence

### PR DESCRIPTION
**Pull request by AndreiDM00**

### CODE REVIEW

**Comment by ImRodry** [comment]
Please fill out the PR template properly and fix the CI issues. I highly recommend you use an IDE like VSCode to assist you with this

**Comment by AndreiDM00** [comment]
i will try today to fix it

**Comment by AndreiDM00** [comment]
I will try my best to fill out the PR template properly but I don't have time right now because I'm at work.

**Comment by AndreiDM00** [comment]
can someone delete this pull request?

**Comment by ImRodry** [comment]
We can close it. Do you no longer wish to work on it @AndreiDM00?

**Pull request closed without merging**
