### PR TITLE
🌟 Guidelines (Revision 2)

### PR DESCRIPTION
**Pull request by Alanexei**

### CODE REVIEW

**Comment by Alanexei** [comment]
Please check to make sure I didn't miss any details, made any grammar mistakes, or forgot a space around parenthesis.

**Comment by Hans5958** [comment]
Please read

**Comment by doomlerd** [comment]
> Spaces between the parentheses and what they enclose? [Really?](https://english.stackexchange.com/a/6035)

mind explaining this bit?

**Comment by Hans5958** [comment]
> 
> 
> > Spaces between the parentheses and what they enclose? [Really?](https://english.stackexchange.com/a/6035)
> 
> mind explaining this bit?

- ``( content that isn't used often )`` ->``(content that isn't used often)``
- ``( for e.g., wikia pages )`` -> ``(for e.g., wikia pages)``
- ``( or ones with little context )`` -> ``(or ones with little context)``
- ``( for e.g., `http` or `https` )`` -> ``(for e.g., `http` or `https`)``
- ``( for e.g., `%song% by %artist%` )`` -> ``(for e.g., `%song% by %artist%`)``
etc...

**Comment by Alanexei** [comment]
I did it so the text in the parens was a little more distinct from the parens themselves. Though it is a grammatical standard in a English to not do that, I'll update it.

**Comment by Hans5958** [comment]
> 
> 
> I did it so the text in the parens was a little more distinct from the parens themselves. Though it is a grammatical standard in a English to not do that, I'll update it.

I see. Sorry for the late respond, but appreciated the reply.

By the way, did you read my other two comments?

**Pull request merged**
