### PR TITLE
Bionluk | Bionluk.com

### PR DESCRIPTION
**Pull request by ReXulEc**
Most freelancer in Turkey and globally using this site. And most of those who use this site use apps like Discord etc. . That's why I wanted to make this presence.

Presence's photo : https://i.imgur.com/2xGsNBs.png

Best regards
-Mert Doğu / rexulec.com

### CODE REVIEW

**Comment by ReXulEc** [comment]
I wrote var instead of const, can you please change it? Thanks!

**Comment by SlowLife1661** [comment]
> I wrote var instead of const, can you please change it? Thanks!
No one use var nowadays unless you are old people kekw, but no please follow the standard

**Comment by ReXulEc** [comment]
This is not low quality, there are many Turkish design servers and a lot of people need this presence.

**Comment by ririxidev** [comment]
Presence is definetely still low quality. ``var``s, everywhere you create new object, no DOM readings.

**Pull request closed without merging**
