### PR TITLE
Revert "rip bounce"

### PR DESCRIPTION
**Pull request by callumok2004**
Reverts PreMiD/Presences#1096

### CODE REVIEW

**Comment by callumok2004** [comment]
Already incremented version -.-
And Bas, I am literally a developer for bounce haha, the site is not **fully** released, but the API is up for the stats to work, which you can see if you check the API link in the presence itself -.-

**Comment by callumok2004** [comment]
image

**Comment by doomlerd** [comment]
Why did you change the API link?

**Comment by callumok2004** [comment]
Were changing up our API behind the scenes soon, with that new api link, and changes we make will go over that one aswell so it dont break the presence

**Pull request merged**
