### PR TITLE
fix(ITVX): fix live channel presence due to data structure change

### PR DESCRIPTION
**Pull request by hiitsdan**
## Description 
ITVX has slightly changed the structure of the NEXT_DATA page props, and as a result broke the ability to correctly display the presence when viewing live channels.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

</details>

### CODE REVIEW

**Comment by DarkVillager** [comment]
@hiitsdan Now that this request is open also please change the logo to be 512x512

**Comment by DarkVillager** [comment]
> @hiitsdan Now that this request is open also please change the logo to be 512x512

Also here please => https://github.com/PreMiD/Presences/blob/9e1e60072456fdf212197d812132163f8c76852e/websites/I/ITVX/presence.ts#L54

**Review by Bas950 — APPROVED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
Please change it here https://github.com/PreMiD/Presences/pull/7313#issuecomment-1521593765

**Comment by Bas950** [comment]
Closed for inactivity

**Pull request closed without merging**
