### PR TITLE
Add AnimeHeaven presence based off twist.moe

### PR DESCRIPTION
**Pull request by marceau-maubert**

### CODE REVIEW

**Comment by ririxidev** [comment]
Heya @marceau-maubert! We have some news for you that you should take look at:
We are so sorry but we need to deny your pull request regarding this presence due of:
 - Adding your own Prettier config. It shouldn't happen.
 - Literally making your own tsconfig and just uncommenting necessary lines.
 - Your Presence is low quality coded.
 
We are really sorry for that, try changing these things and add more support for subpages than now. We will wait for your fixed pull request!
 
Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by marceau-maubert** [comment]
Maybe there should be some guidelines for making pull requests then, regarding what files should be committed or not, or if presences should be "proven to be working" using screenshots.

I used my own `getTimestamps` function because I was basing my presence off an existing one that does just that, but I will fix it.

What do you mean by "low quality coded"? I've updated the code regarding Codacy issues already, and it's not any more complex / worse than certain other presences already available.

As for adding other routes, it's a streaming website, it doesn't need any more information than when browsing the site, looking through a series' episodes and playback status while watching one.

I've updated the pull request description with screenshots.

**Comment by SlowLife1661** [comment]
> Maybe there should be some guidelines for making pull requests then, regarding what files should be committed or not, or if presences should be "proven to be working" using screenshots.
> 
> I used my own `getTimestamps` function because I was basing my presence off an existing one that does just that, but I will fix it.
> 
> What do you mean by "low quality coded"? I've updated the code regarding Codacy issues already, and it's not any more complex / worse than certain other presences already available.
> 
> As for adding other routes, it's a streaming website, it doesn't need any more information than when browsing the site, looking through a series' episodes and playback status while watching one.
> 
> I've updated the pull request description with screenshots.

There is [guidelines!?!](https://docs.premid.app/en/dev/presence/guidelines)

**Comment by marceau-maubert** [comment]
It does look like I missed them, my bad.

They're not linked anywhere in the README or mentioned while attempting to make a pull request, and it's not my first thought to look inside of the `.github` folder for them, so that's why.

**Comment by SlowLife1661** [comment]
> It does look like I missed them, my bad.
> 
> They're not linked anywhere in the README or mentioned while attempting to make a pull request, and it's not my first thought to look inside of the `.github` folder for them, so that's why.

Pretty sure Github will show you something like this, since it's your first time opening a PR here, so I don't think they are to blame.
- When opening a PR
image

- https://github.com/PreMiD/Presences/pulls
image

**Comment by marceau-maubert** [comment]
Fair enough, I guess I missed that also. 

Either way, let's continue at #3293 which should be better I imagine?

**Pull request closed without merging**
