### PR TITLE
🚀[OGLLE.COM.BR] Mega Update -  V1.2

### PR DESCRIPTION
**Pull request by MateusOFCZ**
- [x]  [New Precense Pages](oglle.com.br)
- [x]  [New Thumbnail](oglle.com.br)
- [x] [New URL](oglle.com.br)
- [x] [New Version](oglle.com.br)

> By: @MateusOFCZ

### CODE REVIEW

**Comment by MateusOFCZ** [comment]
> Add a screenshot to verify that it works. Maybe there are screenshots, but I just can't see them, if so just dismiss this.

I thought I only needed a screenshot if it was a new presence, even though it is quite obvious from the changes that the presence is working. 😐

image

**Comment by Bas950** [comment]
> > Add a screenshot to verify that it works. Maybe there are screenshots, but I just can't see them, if so just dismiss this.
> 
> I thought I only needed a screenshot if it was a new presence, even though it is quite obvious from the changes that the presence is working. 😐
> 
> image

This is a screenshot of old stuff, you need a screenshot of a part that was added.

**Comment by MateusOFCZ** [comment]
> > > Add a screenshot to verify that it works. Maybe there are screenshots, but I just can't see them, if so just dismiss this.
> > 
> > 
> > I thought I only needed a screenshot if it was a new presence, even though it is quite obvious from the changes that the presence is working. 😐
> > image
> 
> This is a screenshot of old stuff, you need a screenshot of a part that was added.

I put this on because my PreMid app is not opening!

**Comment by Bas950** [comment]
> I put this on because my PreMid app is not opening!

Then create a ticket in #support on discord

**Comment by MateusOFCZ** [comment]
image
As I am having trouble opening my PreMiD app, I gave my repository to a friend to download and test it, so it will be with his profile on Discord!

**Comment by Alanexei** [comment]
Have him send you a screenshot and you upload it here.

**Comment by MateusOFCZ** [comment]
> Have him send you a screenshot and you upload it here or screenshot it off of his profile.

He accessed the site with the presence of my repository, then I took a print of his profile, what a bureaucracy, and I think that Brazil was bad ...

**Comment by frozaum** [comment]
Hello @MateusOFCZ, it's not a "bureaucracy", we just need to be assure that you are not delivering a broken update, even if it is some minor changes, you just simply, need to prove with a screenshot that the presence is working, and done.

**Pull request merged**
