### PR TITLE
add Discord Services

### PR DESCRIPTION
**Pull request by un-boxing-man**
adding discordservices.net

### CODE REVIEW

**Comment by un-boxing-man** [comment]
Updated presence.ts to  add browsing time stamp

**Review by Bas950 — CHANGES_REQUESTED** [review]
Fix issues, upload proof

**Review by un-boxing-man — COMMENTED** [review]
fixed

**Comment by un-boxing-man** [comment]
> Fix issues, upload proof

ok . proof of what?

**Comment by Slowlife01** [comment]
Hi hello, thanks for making this but unfortunately we're decided to decline your Pull Request due to the following reason:
- **Unqualified** site.
   - As this site is in the category of Discord server list, bot list, and so on, they will have the extra requirements, let's go with the last one first, the website itself must have a very good quality, design, as far as I have researched, I believe this site is a quite basic design which I wouldn't consider very good design as for quality I believe it's pretty same with the other Discord `x` list site, and I consider that fine, alright now the second requirement, must have 45k unique visitors per day, and according to my research this site doesn't have enough visitors.

[Guidelines](https://docs.premid.app/en/dev/presence/guidelines)

**Pull request closed without merging**
