### PR TITLE
Adding 10fastfingers Presence

### PR DESCRIPTION
**Pull request by u0f**

### CODE REVIEW

**Review by ImRodry — CHANGES_REQUESTED** [review]
Upload proof of it working and please use batch suggestions if you accept these

**Comment by u0f** [comment]
It haves 2 minor issues bc i remove the startTimestamp, but everything is correct rn

**Comment by ImRodry** [comment]
Well fix them then

**Comment by ImRodry** [comment]
Yes because you need to use array deconstructing

**Comment by u0f** [comment]
If I leave it as it was, it will fail because I do not use the start variable and if I leave only [end] the timestamp does not work

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Comment by u0f** [comment]
wait the logo isn't correct

**Comment by u0f** [comment]
logo correct

**Review by ImRodry — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — DISMISSED** [review]
fixes deepscan

**Review by Slowlife01 — DISMISSED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
