### PR TITLE
Fix staff panel pages

### PR DESCRIPTION
**Pull request by Chezzer-ub**
Developer at UpBeat, and we don't want the staff pages being on our public discord profile.

### CODE REVIEW

**Comment by Chezzer-ub** [comment]
I know I cannot edit this, but the developer is inactive and I have tried to contact him about this, we cannot let people see staff panel pages.

**Comment by frozaum** [comment]
I'm talking about the codepen commit, not the staff panel fix. @Chezzer-ub

**Comment by Chezzer-ub** [comment]
o

**Comment by Chezzer-ub** [comment]
u know what, this is a mess, brb

**Pull request closed without merging**
