### PR TITLE
feat(youtube): add playlist title & queue as replaceable string

### PR DESCRIPTION
**Pull request by amardito**
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

- **Using custom string %playlistTitle% & %playlistQueue%**
image

- **Using %title% & %playlistQueue%**
image

- **Using %title% & %playlistTitle% as state**
image

</details>

### CODE REVIEW

**Comment by amardito** [comment]
why failed?

**Comment by amardito** [comment]
hey, @theusaf how am I proof this is working when this isn't updated yet?

should I run something in local?

**Comment by DarkVillager** [comment]
> hey, @theusaf how am I proof this is working when this isn't updated yet?
> 
> should I run something in local?

Compile it and load it. View these:
[Compile Presence](https://docs.premid.app/en/dev/presence#creating-a-presence)
[Load presence](https://docs.premid.app/en/dev/presence#loading-your-presence)

**Comment by amardito** [comment]
> > hey, @theusaf how am I proof this is working when this isn't updated yet?
> > should I run something in local?
> 
> Compile it and load it. View these: [Compile Presence](https://docs.premid.app/en/dev/presence#creating-a-presence) [Load presence](https://docs.premid.app/en/dev/presence#loading-your-presence)
> 
> If you need any help feel free to ask question in the[ #presence-development channel ](https://discord.com/channels/493130730549805057/607524579874832446) in the [discord](https://discord.gg/premid)

thank you my friend

**Review by theusaf — DISMISSED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
Please update the placeholders for both settings in metadata to include the newly added variables.

**Comment by amardito** [comment]
> Please update the placeholders for both settings in metadata to include the newly added variables.

This commit https://github.com/PreMiD/Presences/pull/7495/commits/b2a9fcb59cd8c84d3efdbbf01fcc47042c3aa831 is an updated placeholder with new variables.

thanks for reminding me @Bas950 .

**Comment by amardito** [comment]
Hello @theusaf is there any more issue? Please tell me if there are any.
Thanks.

**Review by theusaf — APPROVED** [review]

**Pull request merged**
