### PR TITLE
feat(Amazon): add german language into description

### PR DESCRIPTION
**Pull request by InvalidLenni**
**Describe the changes in this pull request:**

I added the german language to the description

### CODE REVIEW

**Comment by ImRodry** [comment]
perf means performance. Please fix the PR title and the CI issue

**Comment by InvalidLenni** [comment]
which is the perfect pr title then?

**Comment by InvalidLenni** [comment]
and should I update the version to fix the schema validation check

**Review by Miyakura — APPROVED** [review]

**Review by Miyakura — APPROVED** [review]
german translation approved

**Comment by ImRodry** [comment]
This PR will be closed for inactivity if no changes are applied within the next few days.

**Comment by ImRodry** [comment]
Closing this for inactivity

**Pull request closed without merging**
