### PR TITLE
Page update and adding more feature

### PR DESCRIPTION
**Pull request by Himori-0**

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Run prettier, fix issues

**Comment by Himori-0** [comment]
It should be fine now. right?

**Comment by Himori-0** [comment]
Should be okay now. My Visual Studio Code Vslint doesn't work for some reason

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of it working

**Comment by Himori-0** [comment]
here's the part that has the new code
image
image

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
