### PR TITLE
fix(E621): Recoded presence.

### LINKED ISSUE #5328: [Presence | Feature Request] e621.net
### Discussed in https://github.com/PreMiD/Presences/discussions/4649

<div type='discussions-op-text'>

<sup>Originally posted by **Mr-Foxtrot** November 29, 2020</sup>
**What's the name of the service?**
e621.net

**Is your feature request related to a problem? Please describe.**
Well, I am aware the presence already exists. What I came here to request however was a settings page for it, as unlike other presences which lets you hide your search results or what page you are specifically viewing (an example is the Furaffinity rich presence) the e621 rich presence doesn't have any settings. So anyone who views your discord profile knows exactly what you are searching on the site, what post you are on, etc. A option to hide those details would be great and having it just show "Browsing e621" would be lovely. 

I don't believe a lot of people want to know exactly what you are searching up on e6 =/</div>

### LINKED ISSUE #5506: [Presence | Feature Request] e621 - Add "View Search" and "View Post" Buttons
### Presence name

e621

### Description

Add a "View Search" button when the user is in a search on e621 and add a "View Post" button to replace that one when viewing a post. Most other presences have this kind of feature, and would be much more convenient than attempting to make the search yourself.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
Resolves #5506

**Describe the changes in this pull request:**
- Recoded whole presence;
- Took over Presence. Old owner is inactive; doesn't respond to friendsrequests nor dms;
- Added buttons;
- Added setting to disable buttons;
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

(Blurred due to NSFW pictures/comments.)

</details>

### CODE REVIEW

**Comment by EncryptedDev** [comment]
> Took over Presence. Old owner is inactive; doesn't respond to friendsrequests nor dms;
Add yourself as presence author or contributor then

**Comment by DarkVillager** [comment]
> > Took over Presence. Old owner is inactive; doesn't respond to friendsrequests nor dms;
> 
> Add yourself as presence author or contributor then

I will i forgot

**Review by EncryptedDev — APPROVED** [review]
looks fine

**Review by Slowlife01 — APPROVED** [review]

**Comment by StormeTheCat** [comment]
It looks like in [picture seven](https://user-images.githubusercontent.com/42322979/150984966-e654ce71-399f-4631-8b9a-51838993149d.jpg) it still says "Searching _Artists_ For" when it should say "Searching _Tags_ For"

Also, is there an option to "View Post" once you're actually looking at a post, rather than searching in a gallery? [Here's an example url of what I'm talking about.](https://e621.net/posts/2261604?q=rating%3Asafe+order%3Ascore) (Don't worry, it's SFW) For instance, it would say something like "Viewing Post" in line one and "ID: #2261604" in line two with a button to take you directly to the post that says "View Post".
To help differentiate between a search and a post, I recommend changing [picture two](https://user-images.githubusercontent.com/42322979/150984956-29533f2b-00c4-4201-a004-6cb975723bcc.jpg) and [picture four](https://user-images.githubusercontent.com/42322979/150984960-1c47672b-48a7-4333-9b4a-0978ca321474.jpg)'s buttons to say "View _Search"_ rather than "View _Post"_

_Also_ also, is there a Privacy Mode like what YouTube has? One that would just display "Browsing" text and e621's logo? I think that's probably a good idea, especially considering the nature of the site.

**Comment by Slowlife01** [comment]
@DarkVillager #5328 wasn't fulfilled

**Comment by DarkVillager** [comment]
> @DarkVillager #5328 wasn't fulfilled

Will check..

**Pull request merged**
