### PR TITLE
Uploading LectorManga presence

### PR DESCRIPTION
**Pull request by u0f**
Explication about the url: 
This presence is a page to read manga online, this page, saves the chapters in external domains to lectormanga.com

https://i.imgur.com/MaxkAMH.png If you click a manga episode for read it, the website will redirect you to another domain https://i.imgur.com/xFW8qs7.png (one of three domains: example.)

I see the webpage has 3 domains: (recipesandcook.com, biggestchef.com and indalchef.com) and the website original (lectormanga.com)

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Strings will need to be verified by a Spanish team member too

**Comment by alexbcberio** [comment]
> Strings will need to be verified by a Spanish team member too

I have checked the strings and there is only one error where the details are set in English instead of on Spanish, I have added a comment on the line.

The other strings are ok

**Comment by u0f** [comment]
> 
> 
> > Strings will need to be verified by a Spanish team member too
> 
> I have checked the strings and there is only one error where the details are set in English instead of on Spanish, I have added a comment on the line.
> 
> The other strings are ok

Fixed ✅

**Comment by u0f** [comment]
Anyone here?

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Address my suggestions & run prettier (`prettier --write presence.ts` in the presence's folder)

**Pull request closed without merging**
