### PR TITLE
feat(Bandcamp): add cover

### LINKED ISSUE #6560: Album Art for Bandcamp
### Presence name

Bandcamp

### Description

Allow the large image to be the album art of whatever you're listening to the same way SoundCloud and YouTube does.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Resolves #6560 Add cover

## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by RisingSunLight42** [comment]
You forgot to bump the version

**Comment by DarkVillager** [comment]
> Contributor

 I didn't someone forgot to bump wikia before merging it.

**Comment by DarkVillager** [comment]
> You forgot to bump the version

I didn't someone forgot to bump wikia before merging it.

**Comment by RisingSunLight42** [comment]
My bad

**Review by EncryptedDev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
