### PR TITLE
fix(The Odin Project): fix minor stuff

### PR DESCRIPTION
**Pull request by dogukan-sys**
## Description 
Used right Discord id, fixed tags and removed special characters.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

### CODE REVIEW

**Comment by joerkig** [comment]
You dont have to make a new PR everytime you fix/add stuff. If you commit and push it it will automatically be added to the PR

**Comment by dogukan-sys** [comment]
Im sorry i dont understand this error!
\
image

**Comment by RisingSunLight42** [comment]
> Im sorry i dont understand this error!
> \
> image
> 

When you edit a presence, you have to update the version of it accordingly in the metadata files.
For a fix for example, it will be 1.0.1

**Review by DarkVillager — APPROVED** [review]

**Review by RisingSunLight42 — APPROVED** [review]

**Comment by dogukan-sys** [comment]
2 approved review but i cant merge?

**Comment by RisingSunLight42** [comment]
> 2 approved review but i cant merge?

We are not official reviewers (with write access), but contributors ^^

**Review by EncryptedDev — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
