### PR TITLE
feat(Spectrum TV): add presence

### PR DESCRIPTION
**Pull request by auggeeo**
**Describe the changes in this pull request:**
Adds The Spectrum TV Presence
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

screenshot8
screenshot9
screenshot1
screenshot2
screenshot3
screenshot4
screenshot5
screenshot6
screenshot7
</details>

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Hello @CoopPlayzz!

I'll be closing this as I deem this as a low quality presence - nothing is dynamic and all checks have failed. Please use other presences in the repo as reference when developing a presence in the future. 

Thank you for your contribution!

**Comment by CoopPlayzz** [comment]
ok I understand. I will, thx for feedback!
(btw this is my First one so this is new to me)

**Comment by CoopPlayzz** [comment]
@EncryptedDev do you mind giving some suggestions.

**Comment by ImRodry** [comment]
@CoopPlayzz a suggestion would be to actually put some code in your presence and not copy the one from the documentation which just serves to explain what each property does and doesn't actually work. Also yes once you fix all issues you can submit a new PR

**Comment by CoopPlayzz** [comment]
@ImRodry Ok Thanks you for that

**Pull request closed without merging**
