### PR TITLE
Update Toonily Presence

### LINKED ISSUE #4281: [Presence | Feature Request] Toonily
**Prerequisites and essential questions** 
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** Whitzy#0506

**What's the name of the service?** Toonily.com | Toonily

**What should the Presence display?** Which manga you are reading, if you are browsing etc.

**If possible, please provide a logo for the service (512x512 minimum)**

### PR DESCRIPTION
**Pull request by vahya**
Added toonily.com support

Closes #4281 

Screenshot 2021-08-23 133550
Screenshot 2021-08-23 133615
Screenshot 2021-08-23 133642

### CODE REVIEW

**Review by Slowlife01 — COMMENTED** [review]
It's apparently the different site so better use their logo *at least on the Presence*
logo

**Comment by vahya** [comment]
Done, changed logo everywhere.

**Comment by Slowlife01** [comment]
Change the thumbnail too then

**Comment by vahya** [comment]
> Change the thumbnail too then

Toonily.net should be fine as the thumbnail, Toonily.com looks very NSFW

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
