### PR TITLE
Updated, Presence Animes Vision

### PR DESCRIPTION
**Pull request by Smallkan**
Thanks

### CODE REVIEW

**Comment by Smallkan** [comment]
Sorry xD

**Comment by frozaum** [comment]
also you need a screenshot of your discord profile showing that the presence is working

**Comment by Smallkan** [comment]
> also you need a screenshot of your discord profile showing that the presence is working

How do I make it work?

**Comment by frozaum** [comment]
@Smallkan you need to [follow these steps](https://docs.premid.app/en/dev/presence#loading-the-presence) to temporarily load the presence, after that, you go to the website you're supporting and if it's showing over your discord profile, you screenshot like this 
image
or this
image

**Comment by Bas950** [comment]
Just upload a screenshot aswell

**Comment by Smallkan** [comment]
Hello, I apologize for the delay :)

I finished and fixed the ts file.

Screenshot_11

Screenshot_22

**Comment by Alanexei** [comment]
Yeah make sure you set the large image key. The entire metadata.json file can be found in the documentation.

**Comment by doomlerd** [comment]
Exceeded 7 days, open another PR with the requested changes above.

**Pull request closed without merging**
