### PR TITLE
chore: standardize resources

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Applied changes to resources for them to also be viewable in lightmode & the official custom themes.

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Before:

After:

</details>

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
For the repeat-one, maybe add some transparent space around it, not even the full border is shown rn.
And the downloading & uploading ones dont seem left to right centered

**Comment by DarkVillager** [comment]
Btw the "new"" deepscan issues are from things that were already unfixed. 

Should I fix them?

**Comment by DarkVillager** [comment]
As of now I have a lot, and I really mean it a lot of issues to fix. I'm on it but it may take a bit that's why I turned it into a draft PR.

**Comment by Slowlife01** [comment]
FRI: Viu, TVING, Stan, BetterAnime, WeTV, Emanate, Watcha, Last.fm and Gaia don't use the regular assets

**Comment by DarkVillager** [comment]
> FYI: Viu, TVING, Stan, BetterAnime, WeTV, Emanate, Watcha, Last.fm and Gaia don't use the regular assets

We're standardising Assets other than type of Assets that aren't in .resources.

**Comment by Slowlife01** [comment]
> > FYI: Viu, TVING, Stan, BetterAnime, WeTV, Emanate, Watcha, Last.fm and Gaia don't use the regular assets
> 
> We're standardising Assets other than type of Assets that aren't in .resources.

Why is that? I'm sure my assets work on both theme and they look better, at least just disallow the ones that don't work on both theme...

**Comment by DarkVillager** [comment]
> > > FYI: Viu, TVING, Stan, BetterAnime, WeTV, Emanate, Watcha, Last.fm and Gaia don't use the regular assets
> > 
> > 
> > We're standardising Assets other than type of Assets that aren't in .resources.
> 
> Why is that? I'm sure my assets work on both theme and they look better, at least just disallow the ones that don't work on both theme...
> 
> Edit: I'll just _glady_ accept it if you don't like this idea since I hate arguing
> 
> 

I didn't decide. @Bas950 did.

**Comment by DarkVillager** [comment]
Due toi 865fad7 here is proof that it works:
Screenshot_33

**Review by Bas950 — APPROVED** [review]

**Comment by Bas950** [comment]
> > > FYI: Viu, TVING, Stan, BetterAnime, WeTV, Emanate, Watcha, Last.fm and Gaia don't use the regular assets
> > 
> > 
> > We're standardising Assets other than type of Assets that aren't in .resources.
> 
> Why is that? I'm sure my assets work on both theme and they look better, at least just disallow the ones that don't work on both theme...
> 
> Edit: I'll just _glady_ accept it if you don't like this idea since I hate arguing
> 
> 

Will quickly reply here, it's better to standardize these assets so it is consistent over (all) presences.

**Review by theusaf — APPROVED** [review]

**Review by Timeraa — APPROVED** [review]

**Pull request merged**
