### PR TITLE
Added Discords.com presence.

### PR DESCRIPTION
**Pull request by DiscordAnaxes**

### CODE REVIEW

**Comment by ririxidev** [comment]
I'm not able to check when domain has been bought by owner rn since domain has been registered in 2004 and has been probably bought. Sorry.

**Comment by DiscordAnaxes** [comment]
> I'm not able to check when domain has been bought by owner rn since domain has been registered in 2004 and has been probably bought. Sorry.

I could talk with the owner of the service, regarding when the domain was bought.

**Comment by ririxidev** [comment]
and basically - i would need to have stats from this site too you know - visitors etc :/

**Comment by DiscordAnaxes** [comment]
> and basically - i would need to have stats from this site too you know - visitors etc :/

I'll see what I can do... however they do now own discord.bio, so they must have a lot of visitors.

**Comment by DiscordAnaxes** [comment]
> and basically - i would need to have stats from this site too you know - visitors etc :/

Hey! I have talked with the owner, and they have said that the service has been running for 4 years. However, they switched to the discords.com domain a couple of months ago. And regarding the visitor statistics ~500k unique visitors per month, and the service houses nearly 45k servers.

**Comment by ririxidev** [comment]
Well - then do another pr :/

**Comment by DiscordAnaxes** [comment]
> Well - then do another pr :/

Why are you sad :(

**Pull request closed without merging**
