### PR TITLE
Presences repo update

### PR DESCRIPTION
**Pull request by doomlerd**
(check the commits seprately) basically have to update every single one, the draft will be finished once the rest is added.

@PreMiD/presence-verifiers please don't merge any PRs until this is finished or else it would cause merge conflicts ( i mean they would be caused for current PRs anyways but yeah ).

### CODE REVIEW

**Comment by Timeraa** [comment]
@doomlerd The .vscode folder is there for a reason, some people use the VSC Rich Presence extension and that settings file just disables it for the workspace

**Comment by doomlerd** [comment]
✅

**Comment by doomlerd** [comment]
FIXED :  
[check the previous commits, but technically 70%]

DELETED : 
Neox Scanlator - full of JS errors | definitely needs to be recoded
Newgrounds - iframe not working | can be fixed without recoding
Super Animes - +60 errors within one file | needs to be PROPERLY recoded
Super Hentais - same as above
Super Mangas - same as the two above
Tidal - the whole presence checks for strings in booleans | can be fixed without recoding
Codeforces - broken | can be fixed without recoding
DeviantArt - does not respect TS standards | better coded in native JS

**Comment by doomlerd** [comment]
DELETED : 
`HentaiHeaven` - broken | can be fixed without recoding

`animeflix` - compiled without source files | can be fixed without recoding, decision goes to the author
`IFTTT` - same as above
`Keep Talking and Nobody Explodes` - same as above
`My Nintendo` - same as above
`p90.zone` - same as above
`Radio.net` - same as above
`RadioMe` - same as above
`Rythm` - same as above
`s.to` - same as above
`Vlare` - same as above

**Comment by doomlerd** [comment]
resumes at #1258 due to a bug in deepscan.

**Pull request closed without merging**
