### PR TITLE
feat(Minecraft Wiki): add presence

### LINKED ISSUE #8281: Minecraft Wiki | *.minecraft.wiki
### Website name

Minecraft Wiki

### Website URL

https://minecraft.wiki

### Website logo

https://minecraft.wiki/images/Wiki%402x.png?bbf70
- **Note**: It's different depending of which country/language it is. You can ask me if you need it and I'll try to find it, or you can use the Minecraft Wiki's advanced search to look for the logo file, which is probably under the name `Wiki.png` or something like that.

### Prerequisites

- [ ] It is a paid service
- [ ] It is region restricted

## Short notice
Minecraft Wiki used to be hosted under Gamepedia, as seen on #2588, and Fandom, but nowadays it is under [Weird Gloop](https://weirdgloop.org/)'s hosting and it's been a standalone website driven by the community only. With that stated, it is why I'm opening a new service request about this website again. Proof of this can also be seen on [Minecraft's community official page](https://www.minecraft.net/en-us/community), with Mojang citing the Minecraft Wiki, something that has never happened before when under Gamepedia and/or Fandom:

image

## What is the Minecraft Wiki?
[Click here to know more.](https://minecraft.wiki/w/Minecraft_Wiki_(website))

## What types of user interactions there are?
Here's a list of cool things to add in a presence while the user is browsing the Minecraft Wiki. I might've forgotten some very specific things, but these are the main ones:
1. Reading **Minecraft**'s (base game) article (path `/w/(Article name)`, e.g. [here](https://minecraft.wiki/w/Mob));
1.1. Reading an **user's profile page** (path `/w/User:(User name)`, e.g. [here](https://minecraft.wiki/w/User:MarkusRost));
1.2. Reading a **Minecraft Wiki's article** (path /w/Minecraft_Wiki:(Article name), e.g. [here](https://minecraft.wiki/w/Minecraft_Wiki:Wiki_rules));
1.3. Reading **Minecraft Dungeons**' article (path `/w/MCD:(Article name)`, e.g. [here](https://minecraft.wiki/w/Minecraft_Dungeons:Mob));
1.4. Reading **Minecraft Legends**' article (path `/w/MCL:(Article name)`, e.g. [here](https://minecraft.wiki/w/Minecraft_Legends:Mob));
1.5. Reading **Minecraft Earth**'s article (path `/w/MCE:(Article name)`, e.g. [here](https://minecraft.wiki/w/Minecraft_Earth:Mob));
1.6. Reading **Minecraft: Story Mode**'s article (path `/w/MCSM:(Article name)`, e.g. [here](https://minecraft.wiki/w/Minecraft_Story_Mode:Mob)).
2. Inside a **Minecraft**'s (base game) article discussion page (path `/w/Talk:(Article name)`, e.g. [here](https://minecraft.wiki/w/Talk:Minecraft_Wiki_(website)));
2.1. Inside a **Minecraft Dungeons**' article discussion page (path `/w/Minecraft_Dungeons_talk:(Article name)`);
2.2. Inside a **Minecraft Legends**' article discussion page (path `/w/Minecraft_Legends_talk:(Article name)`);
2.3. Inside a **Minecraft Earth**'s article discussion page (path `/w/Minecraft_Earth_talk:(Article name)`);
2.4. Inside a **Minecraft: Story Mode**'s article discussion page (path `/w/Minecraft_Story_Mode_talk:(Article name)`).
3. Editing an article (path `/w/[Namespace:](Article name)?action=edit`, e.g. [here](https://minecraft.wiki/w/Minecraft_Wiki_(website)?action=edit));
4. Looking at an article's editing history (path `/w/[Namespace:](Article name)?action=history`, e.g. [here](https://minecraft.wiki/w/Minecraft_Wiki_(website)?action=history));
5. Viewing article's protection settings (path `/w/[Namespace:](Article name)?action=protect`, e.g. [here](https://minecraft.wiki/w/Minecraft_Wiki_(website)?action=protect)); 
5.1. **Note:** User need special permissions to perform it.
6. Moving an article (path `/w/Special:MovePage/([Namespace:]Article name)`, e.g. [here](https://minecraft.wiki/w/Special:MovePage/Minecraft_Wiki_(website))).

`[Namespace:]` refers to either the base game (in this case, it **doesn't need it**), Minecraft Dungeons (`MCD:`), Minecraft Legends (`MCL:`), Minecraft Earth (`MCE:`), or Minecraft: Story Mode (`MCSM:`). It could also not be a namespace but `User:` if it's about an user page. Well... I think at this point you get how it works.

### Extras:
- Include a timer to see how long the user is doing one of the actions above.
- Add the button [Visit page] in the presence so anyone seeing it can be redirected to the same page the user is on at the moment when clicking.

## How many languages does it support?
Despite the main language English, at `https://minecraft.wiki`, the Minecraft Wiki currently support 11 ones, which are:

1. Deutsch (German), at `https://de.minecraft.wiki`;
2. Español (Spanish), at `https://es.minecraft.wiki`;
3. Français (French), at `https://fr.minecraft.wiki`;
4. 日本語 (Japanese), at `https://ja.minecraft.wiki`;
5. 한국어 (Korean), at `https://ko.minecraft.wiki`;
6. 文言 (Literary Chinese), at `https://lzh.minecraft.wiki`;
8. Português (Portuguese), at `https://pt.minecraft.wiki`;
9. Русский (Russian), at `https://ru.minecraft.wiki`;
10. ไทย (Thai), at `https://th.minecraft.wiki`;
11. Українська (Ukrainian), at `https://uk.minecraft.wiki`;
12. 中文 (Chinese), at `https://zh.minecraft.wiki`.

—

As an editor and autopatrol of the Portuguese Minecraft Wiki, I would love to see it on PreMiD. Thanks!

### PR DESCRIPTION
**Pull request by theusaf**
## Description 

- Resolves #8281

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image
image
image

</details>

### CODE REVIEW

**Review by kau19an — CHANGES_REQUESTED** [review]
Here's the Portuguese description:
`"pt": "Seja bem-vindo(a) à Wiki mais compreensiva sobre a franquia de Minecraft! Nós somos um site administrado pela comunidade, acessível ao público, e que pode ser melhorado por qualquer pessoa."`

Something else I wanna point is: make it so "wiki" always starts capitalized → "**W**iki" when it is to refer to the website.

**Comment by kau19an** [comment]
How can I test it on my PC?

**Comment by theusaf** [comment]
> How can I test it on my PC?

Check out the [development documentation](https://docs.premid.app/dev/presence). Specifically, you'll want to clone my repo/branch, install the dependencies, and run `npx pmd` to "modify" the Minecraft Wiki presence. Then, follow the instructions listed in the documentation to load the presence into your extension

**Review by kau19an — CHANGES_REQUESTED** [review]
1. Viewing the history of a page considers as "Changing some settings..." and not "Viewing history:" and below the whole page's title (including namespace).

2. Moving a page considers as "Configuring Advanced settings" not "Moving:" and below the whole page's title (including namespace). Also happens when you're just viewing pages like [this one](https://minecraft.wiki/w/Special:RecentChangesLinked?hidebots=1&hidecategorization=1&target=Minecraft_Wiki%3AWiki_rules&limit=50&days=7&enhanced=1&urlversion=2).

2. When reading about an article inside of a namespace (everything that has `(Name:)`), unnecessarily displays twice, for example:
"Reading about: Minecraft Legends" (That's okay)
"**Minecraft Legends**:Mob" (Again the namespace? Could just be "Mob", see?)

3. When you're **only viewing** the source code of a page, it still displays "Editing:" when it could be just "Viewing source of:" and below the whole page's title (including namespace), e.g.: [here](https://minecraft.wiki/w/Minecraft_Wiki:Wiki_rules?action=edit). If you can't make this change, it's fine! It'd just be cool if the presence could detect somehow if the user has the permissions to edit or not pages like exemplified above and display if actually "Editing:" or just "Viewing source of:" even though URL has `?action=edit`, y'know?

4. I once saw "gmail.AdvancedSettings" for some reason.

5. Viewing an user page doesn't display its title below "Viewing user:" if they use `{{DISPLAYTITLE:(Whatever they choose)}}` in their source, e.g.: [here](https://minecraft.wiki/w/User:Faariaz) and [here](https://minecraft.wiki/w/User:CraftianosHard). This is because it doesn't see "User:" anymore, just what the user chose, so try to make it detect through the URL instead. Editing an user page doesn't show "Editing:" for some reason too.

6. When inside `/w/Special:Preferences` ([here](https://minecraft.wiki/w/Special:Preferences)), it could simply display "Changing their preferences" instead of "Configuring Advanced settings" and below "Preferences".

7. When it comes to other languages rather than English, the presence isn't customized with "Viewing a page:", "Viewing user:", "Moving:", "Viewing a thread:" and etc. Also, how can one translate these labels to their own language? Even though most already are, there's still some of them missing.

–

I think that's all I managed to spot so far, but, at all, yes, it is working nicely!

**Comment by theusaf** [comment]
> 1. Viewing the history of a page considers as "Changing some settings..." and not "Viewing history:" and below the whole page's title (including namespace).
> 
>     2. Moving a page considers as "Configuring Advanced settings" not "Moving:" and below the whole page's title (including namespace). Also happens when you're just viewing pages like [this one](https://minecraft.wiki/w/Special:RecentChangesLinked?hidebots=1&hidecategorization=1&target=Minecraft_Wiki%3AWiki_rules&limit=50&days=7&enhanced=1&urlversion=2).
> 
>     3. When reading about an article inside of a namespace (everything that has `(Name:)`), unnecessarily displays twice, for example:
>        "Reading about: Minecraft Legends" (That's okay)
>        "**Minecraft Legends**:Mob" (Again the namespace? Could just be "Mob", see?)
> 
>     4. When you're **only viewing** the source code of a page, it still displays "Editing:" when it could be just "Viewing source of:" and below the whole page's title (including namespace), e.g.: [here](https://minecraft.wiki/w/Minecraft_Wiki:Wiki_rules?action=edit). If you can't make this change, it's fine! It'd just be cool if the presence could detect somehow if the user has the permissions to edit or not pages like exemplified above and display if actually "Editing:" or just "Viewing source of:" even though URL has `?action=edit`, y'know?
> 
>     5. I once saw "gmail.AdvancedSettings" for some reason.
> 
>     6. Viewing an user page doesn't display its title below "Viewing user:" if they use `{{DISPLAYTITLE:(Whatever they choose)}}` in their source, e.g.: [here](https://minecraft.wiki/w/User:Faariaz) and [here](https://minecraft.wiki/w/User:CraftianosHard). This is because it doesn't see "User:" anymore, just what the user chose, so try to make it detect through the URL instead. Editing an user page doesn't show "Editing:" for some reason too.
> 
>     7. When inside `/w/Special:Preferences` ([here](https://minecraft.wiki/w/Special:Preferences)), it could simply display "Changing their preferences" instead of "Configuring Advanced settings" and below "Preferences".
> 
>     8. When it comes to other languages rather than English, the presence isn't customized with "Viewing a page:", "Viewing user:", "Moving:", "Viewing a thread:" and etc. Also, how can one translate these labels to their own language? Even though most already are, there's still some of them missing.
> 
> 
> –
> 
> I think that's all I managed to spot so far, but, at all, yes, it is working nicely!

The labels you see are already translated. You can use the language selector in the Presence's settings to select the language you want. This is also the reason I didn't implement some strings like "moving" or "editing". However, I can create a localization pull request to add those strings. If the strings don't load quickly, it may appear as the string's id, such as `gmail.advancedSettings`.
I'll look into the duplicate namespace issue.

**Comment by kau19an** [comment]
> The labels you see are already translated. You can use the language selector in the Presence's settings to select the language you want. 

Well, mine has "Portuguese" selected but still displays English to me in some labels.

image
image

**Comment by theusaf** [comment]
Strange. That could be an extension-side issue.

**Comment by theusaf** [comment]
Now waiting on https://github.com/PreMiD/Localization/pull/7410

**Comment by theusaf** [comment]
<details>
<summary>New screenshots with changes</summary>




</details>

**Review by kau19an — CHANGES_REQUESTED** [review]
1. When looking a page's history, it shows `minecraft wiki.viewHistory` instead of "Viewing history of:"

2. When moving a page, it shows `minecraft wiki.moving` instead of "Moving:"

3. When **only viewing** the source code of a page, it shows `minecraft wiki.viewSourceOf` instead of "Viewing source of:"

3. An extra, but can you make it so when an user is reading inside the exclusive Portuguese Wiki's namespace, `Comunidade:`, it displays as it does on `MCE:`, `MCD:`, `MCSM:` etc.? E.g.: [here](https://pt.minecraft.wiki/w/Comunidade:Hey_Wiki).

–

Despite these few little issues, it's perfect as far as I've seen! I only wonder why when in any other Wiki rather than the English one, the labels I see in there doesn't apply to the others. Being [here](https://minecraft.wiki/w/Special:Preferences) works perfect and it's even translated, but [the same page in Portuguese](https://pt.minecraft.wiki/w/Especial:Preferências) shows "Viewing a page" as any other, for example, and with this and other labels not translated as well. Maybe it needs something specific to handle these languages, I don't know... Also, not sure if it's normal of PreMiD, but mine delays a little bit to change the presence when switching pages. Nothing to worry about, though! I'm pointing it out just to warn in case it's fixable or whatever.

**Comment by theusaf** [comment]
The issue of `minecraft wiki.x` is not going to be resolved until the localization pr is merged.
Anyways, thanks for doing these tests. There are a lot of assumptions I've made that these tests reveal are not necessarily true.

**Comment by kau19an** [comment]
> The issue of `minecraft wiki.x` is not going to be resolved until the localization pr is merged.

Oh, okay! Got it!

> Anyways, thanks for doing these tests.

You're welcome! I'm glad to know I could help somehow. Also, thanks for all the work you did to make this presence, by the way! I  appreciate it.

**Review by kau19an — CHANGES_REQUESTED** [review]
Aside of waiting for the `minecraft wiki.*` strings' approval, it's nearly perfect! I only spotted one bug when inside user pages in other Wikis! What happens is that it only takes the first four characters of the title, then vanish the next and add below the rest. Look at my page, for example, of name "Faariaz":

image

Also, it displays the title as "Reading about" instead of "Viewing user:" in Portuguese, which is totally fine if browsing through the English Wiki, with it even translated too:

image

–

### `Special:` pages
It's an extra thing, but it'd be cool to have a "Viewing contributions of:" when viewing the list of contributions of an user, e.g. [here](https://minecraft.wiki/w/Special:Contributions/Faariaz). Also, a "Viewing their watchlist" when inside the `/w/Special:Watchlist` [watchlist page](https://minecraft.wiki/w/Special:Watchlist). This way, all the special menu pages would be covered with their special labels:

image

I think to do the same when the user is either creating their account or logging in would be interesting as well, with "Creating their account" ([here](https://minecraft.wiki/w/Special:CreateAccount)) and "Logging in" ([here](https://minecraft.wiki/w/Special:UserLogin)) labels. There's another special page to see recent changes in the entire Wiki, which can be accessed [here](https://minecraft.wiki/w/Special:RecentChanges), and when uploading a file ([here](https://minecraft.wiki/w/Special:Upload)). These could be "Viewing recent changes" and "Uploading a file", respectively.

–

Finally, when inside a namespace talk page, it displays the page's title without it, like in "[Minecraft Dungeons talk:Story](https://minecraft.wiki/w/Minecraft_Dungeons_talk:Story)", for example:

image

It should be:
> Viewing a thread
> Minecraft Dungeons:Story

**Review by Timeraa — APPROVED** [review]

**Review by Timeraa — APPROVED** [review]

**Review by kau19an — CHANGES_REQUESTED** [review]
1. When inside a watchlist, I think "Viewing their subscriptions" is more related to a service than actually in the context of the Wiki, y'know? I get it and there's sense in it, but I'd say adding the label "Viewing their watchlist" or something else rather than "subscriptions" to these pages still. It isn't a "subscription" but pages you decide to watch and keep an eye on and get notifications when users change it.

- Creating an account displays "Logging in". It makes sense, so it's okay.

–

After this, if I don't find anything else, I think this presence will be a 100% complete and ready to go once `minecraft wiki.*` strings gets approved! Again, huge thanks to you for making this presence and doing all these changes! It's truly amazing the result we managed to achieve.

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
