### PR TITLE
Add juniper.bot to presences store

### PR DESCRIPTION
**Pull request by MrLivixx**
Fluffy Discord Bot (Music, Ranking, Reminder, Vk Community bridge, WikiFur) https://juniper.bot
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by 0CherryTea0** [comment]
Awesome

**Comment by Mrsasha45op** [comment]
Needs some refactoring.

**Comment by undefined-1111** [comment]
Хочу это :tada:

**Comment by frozaum** [comment]
Hello, as of right now, we won't be able to review your pull request due to the temporarily locking of this repository that we announced in #1946, so we gladly request your patience until everything is sorted out. :)

**Comment by Bas950** [comment]
Unlocked (No longer on hold) - Please update your fork to get your Pull Request reviewed, if you don't do it within the next 3 days the Pull Request will be closed.

**Comment by MrLivixx** [comment]
All right, I'll fix all the bugs within 2 days

**Comment by MrLivixx** [comment]
I have problems with multilingualism, what should I do? Make it in English? This bot is used most often by Russian users

**Comment by doomlerd** [comment]
If the website is in English then it's a must to do it, you can add russian too and use `navigator.language` to deal with it
also update your fork again

**Comment by MrLivixx** [comment]
I updated fork again, I only made the extension in English

**Comment by doomlerd** [comment]
Open another PR after fixing the issues.

**Pull request closed without merging**
