### PR TITLE
AnimesGG | Fix some typos and other things

### PR DESCRIPTION
**Pull request by MMDDKK6500**
**This presence is in Brazilian Portuguese**

Just fixing some typos in the presence :>

### CODE REVIEW

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
bump version & upload proof of working

**Comment by MMDDKK6500** [comment]
(that last commit was because there were some conflicts, i don't know why or how, did I do something wrong?)
proof of it working
ezgif com-gif-maker (10)

**Review by Slowlife01 — DISMISSED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Comment by MMDDKK6500** [comment]
> bump version

Version was bumped, from 1.0.0 to 1.0.1, should i bump it to 1.1.0?

**Comment by Slowlife01** [comment]
> > bump version
> 
> Version was bumped, from 1.0.0 to 1.0.1, should i bump it to 1.1.0?

It's still 1.0.1 because you chose 1.0.0 when you resolved the conflicts

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
