### PR TITLE
Added button into SoundCloud presence

### PR DESCRIPTION
**Pull request by itsmelouis**
As someone requested it, I made it

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
Actually, if you are going to add button, you need to fix codestyle too. Second; there are functions that are already in our `Presence` class. Please use them instead.

**Comment by Kozou4ever** [comment]
what functions are you talking about?

**Comment by ririxidev** [comment]
getTime(), getTimestamps()

**Comment by Kozou4ever** [comment]
bruh that's not my business, I just wanna add the button feature

**Comment by ririxidev** [comment]
Like I said, if presence is getting updated, you need to fix this stuff too. Sorry...

**Comment by Kozou4ever** [comment]
I guess I'll deal with it :/ 
I have a question, do I add my name in the contributors of the presence or not? 
And you can close the PR, I think I'll have for a long time to redo everything

**Comment by ririxidev** [comment]
no you cannot add yourself as contributor, sorry.

**Pull request closed without merging**
