### PR TITLE
Last.JS Dashboard | dashboard.last-shot.rf.gd

### PR DESCRIPTION
**Pull request by darwinikii**
**Prerequisites and essential questions** 
- [ ] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** darwinikii#0031

**What's the name of the service?** dashboard.last-shot.rf.gd | Last.JS Dashboard

**What should the Presence display?** bot name and logo, editing server name, bot and dashboard buttons

**If possible, please provide a logo for the service (512x512 minimum)** 

last

### CODE REVIEW

**Comment by ririxidev** [comment]
sorry but no :/

**Comment by darwinikii** [comment]
> sorry but no :/

where is the mistake :)

**Comment by ririxidev** [comment]
Mistake is this website :P

**Comment by ririxidev** [comment]
oh also, better check our guidelines :)

**Comment by darwinikii** [comment]
> Mistake is this website :P

Thanks for your interest this was my first presence I'll try my luck again on a more famous site

**Pull request closed without merging**
