### PR TITLE
Plex: Add season and chapter indicator

### PR DESCRIPTION
**Pull request by Rubensei**
Chapter name isn't informative enough when you are watching a tv show
tv-show
Checked to avoid displaying unwanted/duplicated info on other types of media
movie
 PS: Also tested music, news, podcasts

### CODE REVIEW

**Comment by Bas950** [comment]
Why 04x22 instead of S4E22?

**Comment by Bas950** [comment]
And you can add yourself as contributor if you want.

**Comment by Rubensei** [comment]
> Why 04x22 instead of S4E22?

I'm used to that format tbh, never liked the plex one that much but don't really care about the format, just about the info

**Comment by Bas950** [comment]
> I'm used to that format tbh, never liked the plex one that much but don't really care about the format, just about the info

S and E are more used and easier to understand

**Comment by Rubensei** [comment]
I'm changing it right now, also editing the .ts instead of the .js directly

**Comment by Bas950** [comment]
Why did you remove all ; ?

**Comment by Rubensei** [comment]
I think it was my damn linter 🤦‍♂ 
Although they are not necessary in typescript (only in a few situations and my linter didin't notice any of them in the code 🤔 )

**Comment by Alanexei** [comment]
I think the way it was before was fine. The change of the format is a general modification rather than a bug fix.

**Pull request merged**
