### PR TITLE
Adding ESLint

### LINKED ISSUE #1301: Update for Reading/typing RP status when in discord.gg
**Describe the Bug**
The presence isnt being updated on the web client when in the specified page (discord.gg)

**Steps to Reproduce**
1.Open discord.gg. 
2.Log in.
3. Go to any guild, any channel. Presence should not be updated when inside while reading nor typing.

**Expected Behavior**
RP should be updated and show the reading/typing status on the channel/guild/dm

**Screenshots**
self explanatory

**Environment**
Windows 10 Home 64x
Chrome Latest version as of this report

**Additional context**
Nothing needed

### PR DESCRIPTION
**Pull request by doomlerd**
closes #1301

### CODE REVIEW

**Comment by doomlerd** [comment]
deal with it

**Comment by Bas950** [comment]
This is going to take a while xD

**Comment by Bas950** [comment]
Reached B

**Comment by Bas950** [comment]
Reached C

**Comment by Bas950** [comment]
Finished C 
Gonna fix Discord presence first.

**Comment by Bas950** [comment]
closes #1301 
image

**Comment by Bas950** [comment]
Reached D

**Comment by Bas950** [comment]
Skipped DeviantArt since its too broken... @Hans5958 
--------
Reached E

**Comment by Bas950** [comment]
Reached F

**Comment by Bas950** [comment]
Reached G

**Comment by Bas950** [comment]
Reached H

**Comment by Bas950** [comment]
Reached I

**Comment by Bas950** [comment]
Reached I

**Comment by Bas950** [comment]
Reached J

**Comment by Bas950** [comment]
Reached K

**Comment by Bas950** [comment]
Reached L

**Comment by Bas950** [comment]
Reached M

**Comment by Bas950** [comment]
Reached N

**Comment by Bas950** [comment]
Reached O

**Comment by Bas950** [comment]
Reached P

**Comment by Bas950** [comment]
Reached Q

**Comment by Bas950** [comment]
Reached R

**Comment by Bas950** [comment]
Reached S

**Comment by Bas950** [comment]
Reached T

**Comment by Bas950** [comment]
Reached U

**Comment by Bas950** [comment]
Reached V

**Comment by Bas950** [comment]
Reached W

**Comment by Bas950** [comment]
Reached X

**Comment by Bas950** [comment]
Reached Y

**Comment by Bas950** [comment]
Reached Z

**Comment by Bas950** [comment]
Reached "other"

**Pull request merged**
