### PR TITLE
fix(KickAssAnime): change regex

### LINKED ISSUE #7185: Update the kickassanime url please
### Presence name

Kickassanime

### Description

Hello dear devs, i want to request to update the kickassanime url. Its outdated right now. Please update it!

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Resolves #7185
Changed regex to work with www[number].site.com e.g. www5.site.com
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Comment by Bas950** [comment]
image
Old regex should work too?

**Comment by DarkVillager** [comment]
> image
> Old regex should work too?



> image
> Old regex should work too?

1EE8EDFF-3845-4B01-9BCE-19891C655048

**Comment by Bas950** [comment]
Yea @DarkVillager you need a / at the end, and every URI has that.

**Comment by DarkVillager** [comment]
> Yea @DarkVillager you need a / at the end, and every URI has that.

image

**Comment by Bas950** [comment]
> > Yea @DarkVillager you need a / at the end, and every URI has that.
> This then?
> ```js
> /([a-z0-9-]+[.])*kickassanime([.][a-z]+)+[/]?/gm
> ```
> image
> 

Regexp gets matched against the full url see https://github.com/PreMiD/Extension/blob/release/src/util/tabPriority.ts#L67

**Review by EncryptedDev — APPROVED** [review]

**Comment by DarkVillager** [comment]
> > > Yea @DarkVillager you need a / at the end, and every URI has that.
> > > This then?
> > 
> > 
> > ```js
> > /([a-z0-9-]+[.])*kickassanime([.][a-z]+)+[/]?/gm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> Regexp gets matched against the full url see https://github.com/PreMiD/Extension/blob/release/src/util/tabPriority.ts#L67

i see but that doesnt explain why the first regex sometimes doesnt work

**Review by Bas950 — APPROVED** [review]
I don't see why the first one wouldn't work but sure

**Pull request merged**
