### PR TITLE
Updated SiriusXM and Updated/Transfered ownership of Apple Music

### PR DESCRIPTION
**Pull request by snoweyfoxx**
Updated SiriusXM to reflect the change on the web player that changed "On Demand Episode" to "Episode." Updated version number to 1.1.1.
image

### CODE REVIEW

**Comment by snoweyfoxx** [comment]
Updated Apple Music assets to use imgur, as the Gazio links no longer resolve.

**Review by ririxidev — APPROVED** [review]
since ye Bryan doesn't care about presences, you can take ownership of it

**Review by Bas950 — CHANGES_REQUESTED** [review]
Please upload proof of the Apple Music presence still working, if not fix it first.

**Comment by snoweyfoxx** [comment]
image

**Review by Bas950 — APPROVED** [review]
Please upload proof of the Apple Music presence still working, if not fix it first.

**Pull request merged**
