### PR TITLE
fix(Daily Mail): thumbnail and article title fixes

### PR DESCRIPTION
**Pull request by ION606**
## Description 

- fixed an issue where the author of an article would be displayed instead of the title
- added a setting to toggle using the article thumbnail as the large image

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

Off:

image

On:

image

image

</details>

### CODE REVIEW

**Review by theusaf — CHANGES_REQUESTED** [review]
As you added a setting, please provide an image/screenshot of the settings menu

**Comment by ION606** [comment]
> As you added a setting, please provide an image/screenshot of the settings menu

I uhhhh....I can't screenshot it because every time I try it closes

**Comment by ION606** [comment]
sorry about that I updated my comment ^~^

**Review by Bas950 — CHANGES_REQUESTED** [review]
Please rebase your branch

**Comment by ION606** [comment]
> Please rebase your branch

wait why?

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]

**Pull request merged**
