### PR TITLE
Remove Google Classroom presence

### PR DESCRIPTION
**Pull request by Allvaa**
i don't want to maintain it again and might have a lot of bug in the future if i don't maintain it anymore. so please remove the presence

### CODE REVIEW

**Comment by kawakami** [comment]
If it is working, it can stay up. If it would need update someone probably will do it.

**Comment by Allvaa** [comment]
i just want the presence to be removed. can i?

**Comment by kawakami** [comment]
It shouldnt be deleted because site is working presence too. You dont need to be dev of it. If it will break or something. Someone will change you to his id

**Comment by Allvaa** [comment]
ok then

**Pull request closed without merging**
