### PR TITLE
Fix Custom Status

### PR DESCRIPTION
**Pull request by eggsywashere**

### CODE REVIEW

**Comment by eggsywashere** [comment]
omg it's owrking ! ! @doomlerd @Bas950 

image

**Comment by eggsywashere** [comment]
image
hapi

**Comment by doomlerd** [comment]
that first screenshot really seems like it's from the website not the presence itself xD

**Comment by eggsywashere** [comment]
> that first screenshot really seems like it's from the website not the presence itself xD

not going to reply to that..

**Pull request merged**
