### PR TITLE
refactor(Wcostream): update display domain name

### PR DESCRIPTION
**Pull request by Espressocodes**
## Description 
Updated: 
- Domain to .tv 
- **version number this time**

Will change fork name next time to reflect proper naming convention. Never done this before. 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Original Edits
Immense help from crunchy I have no idea what I'm doing.

</details>

### CODE REVIEW

**Comment by Espressocodes** [comment]
As per @veryCrunchy;
- Updated version number to comply

Updated formatting for modification from fork to comply with standards.

**Comment by veryCrunchy** [comment]
> @Espressocodes provide proof that the made changes actually work with the presence.

The change doesn't affect the presence. It only updated the url displayed on the presence store.

**Comment by darkvillager2** [comment]
> > @Espressocodes provide proof that the made changes actually work with the presence.
> 
> The change doesn't affect the presence. It only updates the url displayed on the presence store.

Still, the site could be changed under the hood. So they must provide proof

**Comment by veryCrunchy** [comment]
> Still, the site could be changed under the hood. So they must provide proof 

We usually don't ask for proof of the presence working for these kind of changes. This change doesn't affect how the presence functions. It only reflects the .com domain now redirecting to .tv.

**Review by theusaf — APPROVED** [review]

**Comment by Espressocodes** [comment]
Thank you for the title formatting fix. I tried.

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
