### PR TITLE
itsmelody.pw

### LINKED ISSUE #5850: Melody | itsmelody.pw
### Website name

Melody

### Website URL

itsmelody.pw

### Website logo

https://itsmelody.pw/img/logo.png

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Melody is a radio station

### PR DESCRIPTION
**Pull request by Keiranfromsmash**
**Describe the changes in this pull request:**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

</details>

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Hello @KeiranfromSmash 👋

As you are submitting a pull request to add a radio to the Presence store, radios have specific [guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md) they much reach in order to be valid. Please provide proof of the following: 
> Presences for online radios are only allowed if the radio has at least 100 weekly listeners and 15 concurrent and must have some features other than just showing album/song title, etc.

**Comment by KeiranfromSmash** [comment]
Could we talk over discord?

**Comment by KeiranfromSmash** [comment]
if so my tag is Callum#6648

**Comment by KeiranfromMelody** [comment]
Hi, @EncryptedDev 
we will be getting more listerners a week our dev team made this code so i dont know about it please contact tom at 
https://discord.gg/aRk8sGuC

and also please explain what proof and stuff we need
- Keiran
- Melody radio
- https://itsmelody.pw/

**Comment by EncryptedDev** [comment]
Upon further discussion, this radio station does not fill the requirements for a presence - good luck with future growth and we hope to see you reopen this in the near future.

**Pull request closed without merging**
