### PR TITLE
🔥 "Kitapların Dili" presence - 🔧 Update Dizilla

### PR DESCRIPTION
**Pull request by eggsydev**
🔥 **Kitapların Dili** presence:

image

image

image

🔧 **Dizilla** fix:

works

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of the presence working.

**Comment by eggsydev** [comment]
> Upload proof of the presence working.

Done!

**Review by Bas950 — CHANGES_REQUESTED** [review]
The question mark needs to be added to the readme.md in the .resources folder.

**Comment by eggsydev** [comment]
> The question mark needs to be added to the readme.md in the .resources folder.

Oh, didn't know that 😳

**Review by ririxichan — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
