### PR TITLE
Fix Elements Path with New for JOOX Presence

### PR DESCRIPTION
**Pull request by ryukora**
Path Lines: 30, 37 44

### CODE REVIEW

**Comment by nxzlem** [comment]
This is for fixing elements path on JOOX Presence only.

**Comment by nxzlem** [comment]
The problem that causes errors and needs to fix:
!(https://files.catbox.moe/feol2s.png)[feol2s]

**Review by Slowlife01 — CHANGES_REQUESTED** [review]
Bump version and show proof of it working

**Review by Slowlife01 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
