### PR TITLE
@Timeraa Fix presence settings, maybe try catch works?

### PR DESCRIPTION
**Pull request by Bas950**

### CODE REVIEW

**Comment by Timeraa** [comment]
bruh

**Comment by ririxichan** [comment]
I want say if you will check closed prs you will see my that fixes that xddd

**Comment by Bas950** [comment]
> I want say if you will check closed prs you will see my that fixes that xddd

*cough* *cough* link it then...

**Comment by ririxichan** [comment]
https://github.com/PreMiD/Extension/pull/34

**Pull request closed without merging**
