### PR TITLE
if this is the problem, what the fuck

### PR DESCRIPTION
**Pull request by frozaum**

### CODE REVIEW

**Comment by frozaum** [comment]
@Alanexei still, the presence page of mangadex is broken

**Comment by Alanexei** [comment]
Where is the service type

**Comment by frozaum** [comment]
what do you mean? @Alanexei

**Comment by Alanexei** [comment]
Ignore that, mobile app didn't show the entire file so I thought something was missing

**Comment by frozaum** [comment]
can you approve the pr?

**Pull request closed without merging**
