### PR TITLE
Add buttons to player & browse pages for animepahe

### PR DESCRIPTION
**Pull request by MulverineX**
Also replaced querySelector usage so it should be more efficient.

### CODE REVIEW

**Review by ririxidev — CHANGES_REQUESTED** [review]
I think you don't know but `getTimestamps` function is already in `Presence` class and you need to use this one :3

**Comment by MulverineX** [comment]
Oh huh, must be recent-ish. I'll swap it out.

**Comment by ririxidev** [comment]
~~just to point out~~ it's for 4/5 months or so

**Review by ririxidev — APPROVED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of it working

**Comment by MulverineX** [comment]
@Bas950 https://streamable.com/mg019s

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
