### PR TITLE
chore(Office): update branding

### LINKED ISSUE #7136: Feature Request | Office
### Presence name

Office

### Description

Microsoft has discontinued the "Microsoft Office" brand, with all of its products primarily being branded "Microsoft 365". The icon has also been changed:

image

So, it would be nice to update the presence too, changing the name and logo.

### Alternatives

None

### Additional context

None

### PR DESCRIPTION
**Pull request by kyrie25**
## Description 
Updates presence branding to match current state.
Resolves #7136 

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>
nah im good

</details>

### CODE REVIEW

**Comment by DarkVillager** [comment]
@kyrie25 also update the code, cuz there are bugs.

**Comment by kyrie25** [comment]
> @kyrie25 also update the code, cuz there are bugs.

For another day/time, I'll work on this instead. Or someone else can do it idk.

**Comment by DarkVillager** [comment]
As of #7143 please close this PR

**Comment by kyrie25** [comment]
> Due to #7143 please close this PR

Honestly should have just done it in the first place if you were wanting to fix it without wasting my time, but sure.

**Comment by DarkVillager** [comment]
> > Due to #7143 please close this PR
> 
> Honestly should have just done it in the first place if you were wanting to fix it without wasting my time, but sure.

I didn’t have time before but got some now. Sorry for wasting ur time.

**Pull request closed without merging**
