### PR TITLE
TruckStop Radio Update 1.0.2

### PR DESCRIPTION
**Pull request by DubStepMad**
Updated Element IDs which stops the presence breaking on website updates and changes.

### CODE REVIEW

**Comment by DubStepMad** [comment]
Not sure why @babel/core is being updated here.

**Comment by Bas950** [comment]
> Not sure why @babel/core is being updated here.

just undo it I guess...

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of it working

**Comment by DubStepMad** [comment]
Evidence:

image

image

**Comment by DubStepMad** [comment]
@Bas950 Reverted and implemented the changes, doesn't seem to have affected the PR but now Codacy is failing.

**Pull request closed without merging**
