### PR TITLE
Adding AnimeFillerList Presence

### PR DESCRIPTION
**Pull request by u0f**

### CODE REVIEW

**Review by ImRodry — CHANGES_REQUESTED** [review]

**Review by EncryptedDev — CHANGES_REQUESTED** [review]

**Review by ImRodry — CHANGES_REQUESTED** [review]
Fix your indentation wat

**Review by u0f — COMMENTED** [review]
Good

**Review by EncryptedDev — DISMISSED** [review]

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Why do you always use `Array.prototype.includes()` when it is not required? Seems quite useless

**Review by ImRodry — CHANGES_REQUESTED** [review]
In summary:

- Brush up your English abilities
- Avoid the use of unnecessary capital letters
- Avoid unnecessary characters at the end like "..." or ":"

**Comment by ImRodry** [comment]
Please learn to add suggestions to batch 😭
image

**Review by Bas950 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
