### PR TITLE
fix(Speedtest): fixed ping selectors and live test

### LINKED ISSUE #6374: speedtest.net | Bug Report
### Steps to Reproduce

1. Install the speedtest.net presence.
2. Visit the website
3. Notice in the developer console the errors you are receiving!

### Expected Behavior

It should show just fine.

### Actual Behavior

It gives errors.

### Page URL

https://www.speedtest.net

### Screenshots

image

### Operating System

Windows 11

### Browser and Version

Chrome - Latest

### Additional Comments

The speedtest.net website has had some recent UI changes which are most likely the cause of this, it is an issue several people have noticed.

The UI changes are in this section.
image

### PR DESCRIPTION
**Pull request by StrikerFRFX**
## Description 

Fixed a couple of issues regarding outdated selectors and Live Testing not working
closes #6374

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Discord_Gp7eEoriTJ

Discord_g7W3ziZpoi

Discord_5cRVCbbprc

Discord_oVZZNxtV62

</details>

### CODE REVIEW

**Comment by ImRodry** [comment]
Does this fix #6374?

**Comment by StrikerFRFX** [comment]
> Does this fix #6374?

changed it 👍

**Review by EncryptedDev — CHANGES_REQUESTED** [review]
Please shorten all the querySelectors added

**Review by EncryptedDev — APPROVED** [review]

**Review by ImRodry — APPROVED** [review]
If it works it works

**Pull request merged**
