### PR TITLE
Adding dscjobs.org

### PR DESCRIPTION
**Pull request by AhmedSabry957**

### CODE REVIEW

**Comment by ririxidev** [comment]
image

**Comment by AhmedSabry957** [comment]
We are in beta, we are getting ready and adding ads in most site and presence, u can get beta to test the site

**Comment by ririxidev** [comment]
Hey @AhmedSabry957,
So if site is not even done, why you do presence then? + 
image
Domain must be 2 months old.


Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by AhmedSabry957** [comment]
> Hey @AhmedSabry957,
> So if site is not even done, why you do presence then? +
> image
> Domain must be 2 months old.
> 
> Thanks,
> **ririxi**. PreMiD Reviewer Team.
> Contact: [mail@ririxi.dev](mailto:mail@ririxi.dev), ririxi#2721

The project is 2 months old, and the discord server when bought new domain instead of dsccord.com, also we are getting ready after we get approved we are gonna release we are trying to get everything finished

**Comment by ririxidev** [comment]
Hey @AhmedSabry957 again,
Sorry but, it doesn't matter if you changed to new domain or something. Domain that you want to have presence working on must be 2 months old no matter what - even if it had different domain before.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by AhmedSabry957** [comment]
Alright I will apply after one month anything else than the domain is new, I mean. I can fix then I will re apply after one month

**Pull request closed without merging**
