### PR TITLE
Update Apple Music presence

### PR DESCRIPTION
**Pull request by 7loud**
https://github.com/PreMiD/Presences/pull/5046

Closes #4647

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Use presenceData instead of data for the PresenceData object

**Review by Bas950 — DISMISSED** [review]
Upload proof of it working

**Comment by N0chteil** [comment]
> Upload proof of it working

image
Screenshot_41

**Review by EncryptedDev — APPROVED** [review]
Lgtm

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
