### PR TITLE
fix(Miruro): update timestamp calculation

### PR DESCRIPTION
**Pull request by Neo1912**
## Description 
Changes: Update timestamp logic to correctly set startTimestamp and endTimestamp while the video is playing. This ensures accurate display of the total video duration and current progress.
Issue: The current use of getTimestampsfromMedia causes inaccuracies in the progress bar.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

Screenshot 2024-09-30 1
Screenshot 2024-09-30 2

</details>

### CODE REVIEW

**Comment by Neo1912** [comment]
I apologize for the quick follow-up pull request. I realized the timestamp calculations needed improvement for better accuracy and progress bar functionality. Thank you!

**Comment by Bas950** [comment]
Seems to result in the exact same?

```ts
  /**
   * Similar to `getTimestamps` but takes in a media element and returns snowflake timestamps
   * @param media Media object
   */
  getTimestampsfromMedia(media: HTMLMediaElement) {
    return this.getTimestamps(media.currentTime, media.duration)
  }

  /**
   * Converts time and duration integers into snowflake timestamps
   * @param {number} elementTime Current element time seconds
   * @param {number} elementDuration Element duration seconds
   */
  getTimestamps(elementTime: number, elementDuration: number) {
    const startTime = Math.floor(Date.now() / 1000) - elementTime
    const endTime = startTime + elementDuration
    return [Math.floor(startTime), Math.floor(endTime)]
  }
  ```

**Comment by joerkig** [comment]
@Bas950 It might be the inconsistent use of Math.floor() please try removing Math.floor() from what is shown below since the return is already floored and using it in intermediary steps will just cause unnecessary inaccuracies
```ts
     const startTime = Math.floor(Date.now() / 1000) - elementTime
```

**Comment by Neo1912** [comment]
Thanks to everyone who got involved! I've reverted the timestamp update since manual calculation isn't needed. However, I’ve also added 'www' to the URL in the metadata.

**Review by Bas950 — APPROVED** [review]

**Review by theusaf — APPROVED** [review]

**Pull request merged**
