### PR TITLE
HentaiZ website updated

### PR DESCRIPTION
**Pull request by userzumi**
Hi, I have updated some information for this pull, hopefully it will be approved.

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Please add some more statuses that are read from DOMs / that are interactive.
Also upload proof of it working in Discord

**Comment by userzumi** [comment]
I would like to add some pictures as follows:

1. Source


2. Home page with proof of working on Discord


3. Another page that is interacting with the DOM



4. Print out the element for which I can get some information

**Comment by ririxidev** [comment]
Hey @userzumi,
Next time if you are going to post NSFW images, censor them. It isn't place where you can post images with uncensored dicks or whatever that's why I deleted your comment. Still, like @Bas950, said do more things that are interactive with DOM - if it isn't possible, your presence will be qualified as low quality.
P.S. Your status didn't had logo, why is that? Please add it to discord developers portal tho.

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by StrikerFRFX** [comment]
@userzumi waiting...

**Pull request closed without merging**
