### PR TITLE
Added Iris support

### PR DESCRIPTION
**Pull request by Dzardys**

### CODE REVIEW

**Comment by Slowlife01** [comment]
Prettify it with our config and upload proof of the presence being working

**Comment by Dzardys** [comment]
> Prettify it with our config and upload proof of the presence being working

Wdym saying "our config"? Little bit confused atm.

**Comment by Slowlife01** [comment]
The config on the repo

**Comment by Dzardys** [comment]
But I'm still not sure which file and how am I supposed to use, so I've used the same beautifier as always.

**Comment by EncryptedDev** [comment]
> But I'm still not sure which file and how am I supposed to use, so I've used the same beautifier as always.

In the folder of the presence you made, run`prettier --write .` and it'll format to our repo standard

**Review by Slowlife01 — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
