### PR TITLE
Bounce | Coming soon to a speaker near you!

### PR DESCRIPTION
**Pull request by callumok2004**
New API link, Fixes.

### CODE REVIEW

**Comment by callumok2004** [comment]
bruh if i could provide a screenshot I would, loading a presence never works for me anymore! :(

**Comment by Alanexei** [comment]
How did you test the presence? Lol

**Comment by callumok2004** [comment]
its called magic GIVE ME 2 seconds

**Comment by callumok2004** [comment]
https://i.callumdev.pw/aia9b.png
ok fixed it

**Pull request merged**
