### PR TITLE
fix(Udemy): update title selector

### PR DESCRIPTION
**Pull request by Jaspio**

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version, upload proof

**Comment by Jaspio** [comment]
Proof of selector working:
udemy selector change

**Comment by Bas950** [comment]
> Proof of selector working: udemy selector change

https://docs.premid.app/en/dev/presence#loading-the-presence

**Comment by Jaspio** [comment]
Excuse me first time doing a Presence PR.
Proof of working presence:

image
image

**Comment by Bas950** [comment]
No worries, the only thing left to do is bump the version in the metadata.json file.

**Comment by Jaspio** [comment]
Contrasted to Master version

image
image

**Comment by Jaspio** [comment]
Version bump complete

**Review by Bas950 — APPROVED** [review]

**Review by Slowlife01 — APPROVED** [review]

**Pull request merged**
