### PR TITLE
Fix typo in "Viewing series" presence for VRV

### PR DESCRIPTION
**Pull request by SagaFreya**
It said "Viewing serie" before; I changed it to "Viewing series".

### CODE REVIEW

**Comment by SagaFreya** [comment]
I don't have much experience with TypeScript... should I leave the sourceMappingURL at the bottom of the compiled JavaScript?

**Comment by Bas950** [comment]
> I don't have much experience with TypeScript... should I leave the sourceMappingURL at the bottom of the compiled JavaScript?

Yes sourcemapping should stay and use ES2020

**Comment by Bas950** [comment]
dont forget to bump the version in the metadata

**Comment by doomlerd** [comment]
@SagaFreya re-open the PR after the repository unlocks.

**Comment by Bas950** [comment]
I will fix it. No need to make a new one.

**Comment by Bas950** [comment]
FIxed it in: https://github.com/PreMiD/Presences/pull/1524/commits/ace14e1bc223c65dc20c2e73e8675a285f02ef7c

**Pull request closed without merging**
