### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by Timeraa**
This Pull Request updates all dependencies to their latest possible version but also pins them to that version to prevent other package managers like `pnpm` to use the latest version as no lock file exists.

This PR also updates `pmd` to version 1.0.3 which fixes the directory where the metadata.json is placed.

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Why would we pin these versions? That would prevent future deps being updated by Dependabot, no?

**Comment by Timeraa** [comment]
No, dependabot will still open prs but package managers won't just use the latest version

**Comment by Timeraa** [comment]
> Why would we pin these versions? That would prevent future deps being updated by Dependabot, no?

No, it will only prevent package managers from using the latest available. Dependabot (soon renovate) will still open Pull Requests.

**Comment by Timeraa** [comment]
For example `pnpm` or `npm` use the latest mongodb version which then caused the mongodb type error.

**Review by Bas950 — APPROVED** [review]

**Review by EncryptedDev — APPROVED** [review]

**Pull request merged**
