### PR TITLE
Update HBO Max supported URLs

### PR DESCRIPTION
**Pull request by LieutenantSugar**
I made corrections to #7378 regarding the logo URL. It is from Imgur, so it passes. Otherwise, I have not changed any original code, only the supported URLs and logo URL.

### CODE REVIEW

**Comment by DarkVillager** [comment]
Some countries don’t have max yet and still use hbo max like mine.

**Comment by LieutenantSugar** [comment]
> Some countries don’t have max yet and still use hbo max like mine. IMG_3477 IMG_3478


Perhaps the new "Max" links can be added to the supported URLs, not replacing the old ones. At least until the new change is implemented for every country.

**Review by Bas950 — CHANGES_REQUESTED** [review]
Just like @DarkVillager said, please keep the _old_ urls for now since some areas aren't switched over _yet_

**Comment by theusaf** [comment]
Closing for inactivity. You may open a new PR after resolving the issues mentioned in this one.

**Pull request closed without merging**
