### PR TITLE
Adding Presence : Ornikar

### PR DESCRIPTION
**Pull request by codebyalexx**
Adding presence for ornikar.com

### CODE REVIEW

**Comment by Slowlife01** [comment]
Might be acceptable if you add support for literally every sub-pages

**Comment by darby-development** [comment]
> Might be acceptable if you add support for literally every sub-pages

Done in latest commit ;)

**Comment by Slowlife01** [comment]
Well, then I'll sadly have to decline this.

**Comment by darby-development** [comment]
But, why? ;-;

**Comment by darby-development** [comment]
It supports all pages ...

**Pull request closed without merging**
