### PR TITLE
Update Presences: Mangalib, Ranobelib, Hentailib

### PR DESCRIPTION
**Pull request by Mirazex**
Updated and tested 👌

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of it working

**Comment by Mirazex** [comment]
Proof!

RJ5XVxdaSU


When can I update my presences without proofs?

**Review by Bas950 — CHANGES_REQUESTED** [review]
upload proof of the other 2 working too

**Comment by Mirazex** [comment]
jIXpvipUec
4KqCE5jx5U
and another one

**Review by Bas950 — CHANGES_REQUESTED** [review]
Fix codacy errors

**Review by Bas950 — DISMISSED** [review]

**Review by Alanexei — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
