### PR TITLE
fix(Viki): added relevant details

### PR DESCRIPTION
**Pull request by zvbt**
## Description 

Small fix for #7368
## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

image

</details>

### CODE REVIEW

**Comment by zvbt** [comment]
The main problem is fixed, but there are still some issues that need more attention.

**Comment by DarkVillager** [comment]
Bump the version

**Comment by DarkVillager** [comment]
> The main problem is fixed, but there are still some issues that need more attention.

What other issues?

**Comment by zvbt** [comment]
> > The main problem is fixed, but there are still some issues that need more attention.
> 
> What other issues?

Other part of the site like every class changed and i only updated the main for the title and the episode number

**Comment by zvbt** [comment]
Everything should work as long as they don't change the class name, and I removed some paths that don't exist anymore.

**Review by Bas950 — APPROVED** [review]
Kinda yikes when websites have these class names.

**Review by theusaf — APPROVED** [review]

**Comment by seatofsacrifice** [comment]
the issue is sadly still persisting currently

**Pull request merged**
