### PR TITLE
Discord Presence

### PR DESCRIPTION
**Pull request by Bas950**
Should (only) be used for dev portal and other, altough normal discord also works. Note: You need discord app open for it to work.

### CODE REVIEW

**Comment by Bas950** [comment]
Probs no one will use it but it was fun making it lmao

**Comment by frozaum** [comment]
LOOOOOOOOOOOOOL, make a skype one and we make a deal

**Comment by Bas950** [comment]
Slack is next, then I will see skype @frozaum

**Comment by frozaum** [comment]
nice @Bas950

**Pull request merged**
