### PR TITLE
feat(TeleCine): add SmallImageKey

### PR DESCRIPTION
**Pull request by anaooz**

### CODE REVIEW

**Comment by EncryptedDev** [comment]
Hello, thank you for creating a pull request. Please take action on the following:
- You have not bumped the version as shown in the workflow annotation
- You have not attached proof that the changes are functional

Until this has been addressed, this pull request cannot be merged.

**Comment by anaooz** [comment]
image
image

**Comment by EncryptedDev** [comment]
Schema Validation Check still has not passed - you must bump the version

**Review by Slowlife01 — APPROVED** [review]

**Comment by fr0r** [comment]
Just pointing out something minor, i would personally recommend renaming the presence to ``Telecine`` (without the capital C) since that's how they stylized it.

**Pull request closed without merging**
