### PR TITLE
Add presence for Animes Vision

### PR DESCRIPTION
**Pull request by Sazzo**
Animes Vision is a Brazilian anime website.
https://animesvision.biz/

[Screenshot](https://i.imgur.com/gCmOyW3.png)

### CODE REVIEW

**Comment by frozaum** [comment]
Please fix the issues that DeepScan said

**Comment by Sazzo** [comment]
Sure.

**Comment by doomlerd** [comment]
Please upload the image in the PR, not in an external host.

**Comment by frozaum** [comment]
that as well

**Comment by Sazzo** [comment]
sure (=
yay

**Comment by doomlerd** [comment]
You need to recompile your presence after those changes.

**Comment by Sazzo** [comment]
^

**Pull request merged**
