### PR TITLE
added support for gogoanime.news (upon request from some users)

### PR DESCRIPTION
**Pull request by PsychoPast**
image

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version

**Comment by PsychoPast** [comment]
> Why add more and more fallback URLs to the URL list when you have a way to detect any URL (regex)? Just curious of course.

I was told to add one or more fallback URLs in case regex fails. So I wanted to capture the biggest amount of "valid" domains. Not every domain captured by regex is authentic. The extension compares the current one against a list of valid domains (returned by an API). There are a lot of gogoanime rip-offs which are not supported by the extension.

**Review by Bas950 — DISMISSED** [review]
bump version

**Comment by Bas950** [comment]
think something went wrong with your pr?

**Comment by PsychoPast** [comment]
> think something went wrong with your pr?

*sigh* idk what happened. Better to close this one and open a new one?

**Comment by Bas950** [comment]
Try updating fork maybe that fixes it.

**Comment by PsychoPast** [comment]
> Try updating fork maybe that fixes it.

all good?

**Review by Bas950 — APPROVED** [review]

**Review by StrikerFRFX — APPROVED** [review]

**Pull request merged**
