### PR TITLE
fix(UKTV): fix title & add series

### PR DESCRIPTION
**Pull request by DarkVillager**
## Description 

Fixed title not being shown
## Acknowledgements
- [X] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [X] I linted the code by running `yarn format`
- [X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

</details>

### CODE REVIEW

**Review by sivelswhy — APPROVED** [review]
great 👌

**Review by EncryptedDev — APPROVED** [review]

**Comment by DarkVillager** [comment]
@EncryptedDev wrong label

**Comment by EncryptedDev** [comment]
Resolve ocnflicts and rebase

**Comment by EncryptedDev** [comment]
Sorry, please rebase your branch again

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
