### PR TITLE
🎉 Blockbench Presence

### PR DESCRIPTION
**Pull request by v30xy**

### CODE REVIEW

**Comment by v30xy** [comment]
image
image
image
image

**Review by ririxidev — COMMENTED** [review]
Hey @v30xy,
Isn't it possible to get more from this site to display on status?

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by v30xy** [comment]
> Hey @v30xy,
> Isn't it possible to get more from this site to display on status?
> 
> Thanks,
> **ririxi**. PreMiD Reviewer Team.
> Contact: [mail@ririxi.dev](mailto:mail@ririxi.dev), ririxi#2721

Sorry but probably not. Model types actually did not exist, but I added it with the developer's instructions. If more things are added in the future, I will add anyway.

**Review by ririxidev — APPROVED** [review]
lgtm i guess then 🤷

**Review by Bas950 — APPROVED** [review]
LGTM

**Pull request merged**
