### PR TITLE
Presence | Epic Games

### PR DESCRIPTION
**Pull request by marinofranz**
image
image

### CODE REVIEW

**Review by Bas950 — CHANGES_REQUESTED** [review]
Make support for all languages of the website not only en-US

**Comment by marinofranz** [comment]
Ok 👌

**Comment by marinofranz** [comment]
image
image

**Review by Bas950 — DISMISSED** [review]

**Review by doomlerd — CHANGES_REQUESTED** [review]
Fix the [reported issues](https://app.codacy.com/gh/PreMiD/Presences/pullRequest?prid=6113508).

**Review by doomlerd — APPROVED** [review]

**Review by Bas950 — APPROVED** [review]

**Pull request merged**
