### PR TITLE
grailed fix

### PR DESCRIPTION
**Pull request by kznvii**

### CODE REVIEW

**Comment by kznvii** [comment]
ok i re did the fork and i think that fixed it

**Review by Bas950 — CHANGES_REQUESTED** [review]
bump version, upload proof of working

**Comment by kznvii** [comment]
i already set version to 1.0.1. should i set it to 1.0.2?

**Comment by kznvii** [comment]
proof

**Comment by kznvii** [comment]
image

**Comment by kznvii** [comment]
image

**Comment by kznvii** [comment]
image

**Comment by Bas950** [comment]
> i already set version to 1.0.1. should i set it to 1.0.2?

check files editted I dont see a version bump :/

**Comment by kznvii** [comment]
image

**Comment by kznvii** [comment]
the version says 1.0.1, but it seems that it was that before though. so should i set it to be 1.0.2?

**Comment by kznvii** [comment]
oh, the version on the store currently says 1.0.1. so i guess ill just set it to be ver 1.0.2

**Review by Bas950 — APPROVED** [review]
bump version, upload proof of working

**Review by ririxidev — APPROVED** [review]

**Pull request merged**
