### PR TITLE
TruckersFM - Fixed AutoDJ Bug

### PR DESCRIPTION
**Pull request by NinjaLabs-Dev**
Fixing existing bug when AutoDJ causes errors due to empty DOM element. 
Also removed 'until' time from presence.

Evidence of testing:

Image of presence

### CODE REVIEW

**Review by ririxidev — CHANGES_REQUESTED** [review]
Heya @NinjaLabs-Dev!
You should check out thing(s) that I requested to change in my review. Please look at them!
 - Bump version

Thanks,
**ririxi**. PreMiD Reviewer Team.
Contact: mail@ririxi.dev, ririxi#2721

**Comment by NinjaLabs-Dev** [comment]
Bumped version to 1.3.0

**Review by Bas950 — APPROVED** [review]
LGTM

**Comment by ririxidev** [comment]
LGTM!

**Review by ririxidev — APPROVED** [review]
LGTM!

**Comment by ririxidev** [comment]
Codacy borked today or what

**Pull request merged**
