### PR TITLE
BeastFM | change artist & song seperator

### PR DESCRIPTION
**Pull request by marinofranz**

### CODE REVIEW

**Review by ririxichan — CHANGES_REQUESTED** [review]
bump version

**Review by Bas950 — APPROVED** [review]

**Review by Bas950 — CHANGES_REQUESTED** [review]
Upload proof of it working

**Comment by marinofranz** [comment]
cannot upload proof at the moment because their API & website is down unfortunately

**Comment by MicroBotCodes** [comment]
https://uhpeople.is-inside.me/nqftAabg.png
Here is the old one but I would like to switch to the new API just so if people see the code of this pr they cant know where are azuracast is and it would look nicer with the editing the song separator.
@Bas950 
@ririxichan 
@Timeraa

**Comment by Bas950** [comment]
> https://uhpeople.is-inside.me/nqftAabg.png
> Here is the old one but I would like to switch to the new API just so if people see the code of this pr they cant know where are azuracast is and it would look nicer with the editing the song separator.
> @Bas950
> @ririxichan
> @Timeraa

we need proof of it working with this update.

**Comment by MicroBotCodes** [comment]
I don't know how to give proof I am the owner of beastfm I did not make the pr so I don't know-how. I paid Marino to make it.

**Comment by MicroBotCodes** [comment]
Please close this Pull Request.
I will create a new one when I edit it a lot.

**Comment by marinofranz** [comment]
> Please close this Pull Request.
> I will create a new one when I edit it a lot.

no need to close this, ill make it a draft

**Pull request closed without merging**
