### PR TITLE
feat(Mugzone): fix some stuff, add a new mode on leaderboard 

### PR DESCRIPTION
**Pull request by Himori-0**
**Describe the changes in this pull request:**

<details>
<summary> Proof showing the creation/modification is working as expected </summary>
<br>

image

</details>

### CODE REVIEW

**Comment by Slowlife01** [comment]
Please rebase and resolve conflicts.

**Comment by Himori-0** [comment]
> Please rebase and resolve conflicts.

It said this branch can't be rebased Should I make a new branch?

**Comment by Himori-0** [comment]
> Please rebase and resolve conflicts.

Should I use update rebase or something like that? Also I can't find the resolve conflict button

**Comment by EncryptedDev** [comment]
I will be closing this pull request as there has been no activity since it was opened. Reopen the pull request once you have dealt with this

**Pull request closed without merging**
