### PR TITLE
feat(4chan): add setting to show thumbnail

### PR DESCRIPTION
**Pull request by beardotpy**
## Description 

Add a setting to display the image of the thread.

## Acknowledgements
- [x] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [x] I linted the code by running `yarn format`
- [x] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

## Screenshots
<details>
<summary> Proof showing the creation/modification is working as expected </summary>

https://github.com/PreMiD/Presences/assets/82332776/8e283a7b-7c6a-4305-a333-3b02103785a8

image

image

If the OP image is deleted or nonexistent, the 4chan logo is displayed instead:
image

</details>

### CODE REVIEW

**Comment by DarkVillager** [comment]
@Bas950 this could break the NSFW rule i think?

**Comment by tag27** [comment]
> @Bas950 this could break the NSFW rule i think? Since some thumbnails can be NSFW.

I was thinking about that too. My solution is for the code to ignore images from NSFW boards if the thumbs option is active, showing only the presence's default largeimg.

**Comment by beardotpy** [comment]
The code that displays the thumbnail never gets run if the thread is from an NSFW board. Sorry, I should have made that more clear in my PR.

**Review by Bas950 — APPROVED** [review]
image
LGTM

**Review by theusaf — APPROVED** [review]

**Pull request merged**
